### ISSUE TITLE
PacketEvents caught an unhandled exception while calling your listener

### ISSUE THREAD

**Issue by gummianka** [GrimAnticheat/Grim#1012]
### Stack trace

java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 16
	at ac.grim.grimac.utils.latency.CompensatedWorld.updateBlock(CompensatedWorld.java:270) ~[?:?]
	at ac.grim.grimac.events.packets.CheckManagerListener.onPacketReceive(CheckManagerListener.java:434) ~[?:?]
	at ac.grim.grimac.shaded.com.github.retrooper.packetevents.event.PacketReceiveEvent.call(PacketReceiveEvent.java:45) ~[?:?]
	at ac.grim.grimac.shaded.com.github.retrooper.packetevents.event.EventManager.callEvent(EventManager.java:54) ~[?:?]
	at ac.grim.grimac.shaded.com.github.retrooper.packetevents.util.PacketEventsImplHelper.handleServerBoundPacket(PacketEventsImplHelper.java:43) ~[?:?]
	at ac.grim.grimac.shaded.io.github.retrooper.packetevents.injector.handlers.PacketEventsDecoder.read(PacketEventsDecoder.java:51) ~[?:?]
	at ac.grim.grimac.shaded.io.github.retrooper.packetevents.injector.handlers.PacketEventsDecoder.decode(PacketEventsDecoder.java:58) ~[?:?]
	at ac.grim.grimac.shaded.io.github.retrooper.packetevents.injector.handlers.PacketEventsDecoder.decode(PacketEventsDecoder.java:35) ~[?:?]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88) ~[server.jar:git-Purpur-1171]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[server.jar:git-Purpur-1171]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[server.jar:git-Purpur-1171]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[server.jar:git-Purpur-1171]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[server.jar:git-Purpur-1171]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[server.jar:git-Purpur-1171]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[server.jar:git-Purpur-1171]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[server.jar:git-Purpur-1171]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) ~[server.jar:git-Purpur-1171]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) ~[server.jar:git-Purpur-1171]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[server.jar:git-Purpur-1171]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[server.jar:git-Purpur-1171]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[server.jar:git-Purpur-1171]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) ~[server.jar:git-Purpur-1171]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) ~[server.jar:git-Purpur-1171]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[server.jar:git-Purpur-1171]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[server.jar:git-Purpur-1171]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[server.jar:git-Purpur-1171]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[server.jar:git-Purpur-1171]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[server.jar:git-Purpur-1171]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[server.jar:git-Purpur-1171]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[server.jar:git-Purpur-1171]
	at io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:152) ~[server.jar:git-Purpur-1171]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[server.jar:git-Purpur-1171]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[server.jar:git-Purpur-1171]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[server.jar:git-Purpur-1171]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[server.jar:git-Purpur-1171]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[server.jar:git-Purpur-1171]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[server.jar:git-Purpur-1171]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[server.jar:git-Purpur-1171]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:792) ~[server.jar:git-Purpur-1171]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:475) ~[server.jar:git-Purpur-1171]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378) ~[server.jar:git-Purpur-1171]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[server.jar:git-Purpur-1171]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[server.jar:git-Purpur-1171]
	at java.lang.Thread.run(Thread.java:833) [?:?]
[15:50:51] [Netty Epoll Server IO #5/INFO]: An error has occurred when running transactions for player: im_lifemane
[15:50:51] [Netty Epoll Server IO #5/WARN]: java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 16
[15:50:51] [Netty Epoll Server IO #5/WARN]: 	at ac.grim.grimac.utils.latency.CompensatedWorld.updateBlock(CompensatedWorld.java:270)
[15:50:51] [Netty Epoll Server IO #5/WARN]: 	at ac.grim.grimac.utils.latency.CompensatedWorld.handleAck(CompensatedWorld.java:140)
[15:50:51] [Netty Epoll Server IO #5/WARN]: 	at ac.grim.grimac.utils.latency.CompensatedWorld.lambda$handleBlockBreakAck$0(CompensatedWorld.java:109)
[15:50:51] [Netty Epoll Server IO #5/WARN]: 	at ac.grim.grimac.utils.latency.LatencyUtils.handleNettySyncTransaction(LatencyUtils.java:44)
[15:50:51] [Netty Epoll Server IO #5/WARN]: 	at ac.grim.grimac.player.GrimPlayer.addTransactionResponse(GrimPlayer.java:313)
[15:50:51] [Netty Epoll Server IO #5/WARN]: 	at ac.grim.grimac.events.packets.PacketPingListener.onPacketReceive(PacketPingListener.java:35)
[15:50:51] [Netty Epoll Server IO #5/WARN]: 	at ac.grim.grimac.shaded.com.github.retrooper.packetevents.event.PacketReceiveEvent.call(PacketReceiveEvent.java:45)
[15:50:51] [Netty Epoll Server IO #5/WARN]: 	at ac.grim.grimac.shaded.com.github.retrooper.packetevents.event.EventManager.callEvent(EventManager.java:54)
[15:50:51] [Netty Epoll Server IO #5/WARN]: 	at ac.grim.grimac.shaded.com.github.retrooper.packetevents.util.PacketEventsImplHelper.handleServerBoundPacket(PacketEventsImplHelper.java:43)
[15:50:51] [Netty Epoll Server IO #5/WARN]: 	at ac.grim.grimac.shaded.io.github.retrooper.packetevents.injector.handlers.PacketEventsDecoder.read(PacketEventsDecoder.java:51)
[15:50:51] [Netty Epoll Server IO #5/WARN]: 	at ac.grim.grimac.shaded.io.github.retrooper.packetevents.injector.handlers.PacketEventsDecoder.decode(PacketEventsDecoder.java:58)
[15:50:51] [Netty Epoll Server IO #5/WARN]: 	at ac.grim.grimac.shaded.io.github.retrooper.packetevents.injector.handlers.PacketEventsDecoder.decode(PacketEventsDecoder.java:35)
[15:50:51] [Netty Epoll Server IO #5/WARN]: 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88)
[15:50:51] [Netty Epoll Server IO #5/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[15:50:51] [Netty Epoll Server IO #5/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[15:50:51] [Netty Epoll Server IO #5/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[15:50:51] [Netty Epoll Server IO #5/WARN]: 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
[15:50:51] [Netty Epoll Server IO #5/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[15:50:51] [Netty Epoll Server IO #5/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[15:50:51] [Netty Epoll Server IO #5/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[15:50:51] [Netty Epoll Server IO #5/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
[15:50:51] [Netty Epoll Server IO #5/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
[15:50:51] [Netty Epoll Server IO #5/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[15:50:51] [Netty Epoll Server IO #5/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[15:50:51] [Netty Epoll Server IO #5/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[15:50:51] [Netty Epoll Server IO #5/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
[15:50:51] [Netty Epoll Server IO #5/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
[15:50:51] [Netty Epoll Server IO #5/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[15:50:51] [Netty Epoll Server IO #5/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[15:50:51] [Netty Epoll Server IO #5/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[15:50:51] [Netty Epoll Server IO #5/WARN]: 	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
[15:50:51] [Netty Epoll Server IO #5/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[15:50:51] [Netty Epoll Server IO #5/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[15:50:51] [Netty Epoll Server IO #5/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[15:50:51] [Netty Epoll Server IO #5/WARN]: 	at io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:152)
[15:50:51] [Netty Epoll Server IO #5/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[15:50:51] [Netty Epoll Server IO #5/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[15:50:51] [Netty Epoll Server IO #5/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[15:50:51] [Netty Epoll Server IO #5/WARN]: 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
[15:50:51] [Netty Epoll Server IO #5/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[15:50:51] [Netty Epoll Server IO #5/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[15:50:51] [Netty Epoll Server IO #5/WARN]: 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
[15:50:51] [Netty Epoll Server IO #5/WARN]: 	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:792)
[15:50:51] [Netty Epoll Server IO #5/WARN]: 	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:475)
[15:50:51] [Netty Epoll Server IO #5/WARN]: 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
[15:50:51] [Netty Epoll Server IO #5/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
[15:50:51] [Netty Epoll Server IO #5/WARN]: 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[15:50:51] [Netty Epoll Server IO #5/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)

### How to replicate it if known

Exceptions in the console, I dont know the reason

### Grim version

2.3.39

### Server version

Purpur 1171, 1.16.5

### Plugins

Grim, AnkaAPI, AnkaCorePlugin, AnkaDuels, AnkaMenu, AnkaPerms, AnkaPunishments, FastAsyncWorldEdit (WorldEdit), LibsDisguises, ProtocolLib, spark, Vault, ViaBackwards, ViaVersion, WorldGuard

**Comment by MWHunter** [comment]
Duplicate https://github.com/GrimAnticheat/Grim/issues/911
