### ISSUE TITLE
[GrimAC] Global task for GrimAC v2.3.40 generated an exception java.lang.UnsupportedOperationException: null

### ISSUE THREAD

**Issue by AVuTuVA** [GrimAnticheat/Grim#1026]
### Stack trace

[16:17:26 WARN]: [GrimAC] Global task for GrimAC v2.3.40 generated an exception
java.lang.UnsupportedOperationException: null
        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftScheduler.handle(CraftScheduler.java:536) ~[folia-1.19.4.jar:git-Folia-"043f070"]
        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:236) ~[folia-1.19.4.jar:git-Folia-"043f070"]
        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:212) ~[folia-1.19.4.jar:git-Folia-"043f070"]
        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftScheduler.runTaskLater(CraftScheduler.java:176) ~[folia-1.19.4.jar:git-Folia-"043f070"]
        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftScheduler.runTask(CraftScheduler.java:145) ~[folia-1.19.4.jar:git-Folia-"043f070"]
        at ac.grim.grimac.utils.lists.CorrectingPlayerInventoryStorage.checkThatBukkitIsSynced(CorrectingPlayerInventoryStorage.java:108) ~[grimac-2.3.40.jar:?]
        at ac.grim.grimac.utils.lists.CorrectingPlayerInventoryStorage.tickWithBukkit(CorrectingPlayerInventoryStorage.java:123) ~[grimac-2.3.40.jar:?]
        at ac.grim.grimac.manager.tick.impl.TickInventory.tick(TickInventory.java:11) ~[grimac-2.3.40.jar:?]
        at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422) ~[guava-31.1-jre.jar:?]
        at ac.grim.grimac.manager.TickManager.tickAsync(TickManager.java:34) ~[grimac-2.3.40.jar:?]
        at ac.grim.grimac.manager.init.start.TickRunner.lambda$start$0(TickRunner.java:17) ~[grimac-2.3.40.jar:?]
        at io.papermc.paper.threadedregions.scheduler.FoliaGlobalRegionScheduler$GlobalScheduledTask.run(FoliaGlobalRegionScheduler.java:178) ~[folia-1.19.4.jar:?]
        at io.papermc.paper.threadedregions.scheduler.FoliaGlobalRegionScheduler.tick(FoliaGlobalRegionScheduler.java:36) ~[folia-1.19.4.jar:?]
        at io.papermc.paper.threadedregions.RegionizedServer.globalTick(RegionizedServer.java:194) ~[folia-1.19.4.jar:git-Folia-"043f070"]
        at io.papermc.paper.threadedregions.RegionizedServer$GlobalTickTickHandle.tickRegion(RegionizedServer.java:149) ~[folia-1.19.4.jar:git-Folia-"043f070"]
        at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:385) ~[folia-1.19.4.jar:git-Folia-"043f070"]
        at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[folia-1.19.4.jar:git-Folia-"043f070"]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

### Grim version

v2.3.40

### Server version

Folia-last

### Plugins

Grim

**Comment by MWHunter** [comment]
oops, forgot to use the folia scheduler for that file

**Comment by ghost** [comment]
@AVuTuVA привет

**Comment by SamB440** [comment]
This seems to be using the folia scheduler now.
