### ISSUE TITLE
Can't use api with folia or folia fork.

### ISSUE THREAD

**Issue by TheForgTN** [GrimAnticheat/Grim#1029]
### Describe the bug and how to replicate it

@Override
public void onEnable() {
    // Plugin startup logic
    Bukkit.getPluginManager().registerEvents(this, this);
    RegisteredServiceProvider<GrimAbstractAPI> provider = Bukkit.getServicesManager().getRegistration(GrimAbstractAPI.class);
    if (provider != null) {
        GrimAbstractAPI api = provider.getProvider();
    }
    getLogger().info("GrimApi enabled!");
}

@EventHandler
public void onflag(FlagEvent e){
    e.setCancelled(true);
}

[18:50:45 WARN]: [GrimAC] Global task for GrimAC v2.3.40 generated an exception
java.lang.UnsupportedOperationException: null
        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftScheduler.handle(CraftScheduler.java:536) ~[kaiiju-1.19.4.jar:git-Kaiiju-"8664b13"]
        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:236) ~[kaiiju-1.19.4.jar:git-Kaiiju-"8664b13"]
        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:212) ~[kaiiju-1.19.4.jar:git-Kaiiju-"8664b13"]
        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftScheduler.runTaskLater(CraftScheduler.java:176) ~[kaiiju-1.19.4.jar:git-Kaiiju-"8664b13"]
        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftScheduler.runTask(CraftScheduler.java:145) ~[kaiiju-1.19.4.jar:git-Kaiiju-"8664b13"]
        at ac.grim.grimac.utils.lists.CorrectingPlayerInventoryStorage.checkThatBukkitIsSynced(CorrectingPlayerInventoryStorage.java:108) ~[grimac-2.3.40.jar:?]
        at ac.grim.grimac.utils.lists.CorrectingPlayerInventoryStorage.tickWithBukkit(CorrectingPlayerInventoryStorage.java:149) ~[grimac-2.3.40.jar:?]
        at ac.grim.grimac.manager.tick.impl.TickInventory.tick(TickInventory.java:11) ~[grimac-2.3.40.jar:?]
        at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422) ~[guava-31.1-jre.jar:?]
        at ac.grim.grimac.manager.TickManager.tickAsync(TickManager.java:34) ~[grimac-2.3.40.jar:?]
        at ac.grim.grimac.manager.init.start.TickRunner.lambda$start$0(TickRunner.java:17) ~[grimac-2.3.40.jar:?]
        at io.papermc.paper.threadedregions.scheduler.FoliaGlobalRegionScheduler$GlobalScheduledTask.run(FoliaGlobalRegionScheduler.java:178) ~[kaiiju-1.19.4.jar:?]
        at io.papermc.paper.threadedregions.scheduler.FoliaGlobalRegionScheduler.tick(FoliaGlobalRegionScheduler.java:36) ~[kaiiju-1.19.4.jar:?]
        at io.papermc.paper.threadedregions.RegionizedServer.globalTick(RegionizedServer.java:194) ~[kaiiju-1.19.4.jar:git-Kaiiju-"8664b13"]
        at io.papermc.paper.threadedregions.RegionizedServer$GlobalTickTickHandle.tickRegion(RegionizedServer.java:149) ~[kaiiju-1.19.4.jar:git-Kaiiju-"8664b13"]
        at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:385) ~[kaiiju-1.19.4.jar:git-Kaiiju-"8664b13"]
        at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[kaiiju-1.19.4.jar:git-Kaiiju-"8664b13"]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

### Grim version

GrimAC version 2.3.40

### Server version

git-Kaiiju-"8664b13"
https://github.com/KaiijuMC/Kaiiju/releases 

### Plugins

Essentials, FoliaPort, GrimAC, GrimLeash, PlaceholderAPI, ViaBackwards, ViaVersion

**Comment by MWHunter** [comment]
Duplicate #1026
