### ISSUE TITLE
Null event on player join

### ISSUE THREAD

**Issue by CSutter5** [GrimAnticheat/Grim#1071]
### Stack trace

```
[15:19:31] [User Authenticator #4/INFO]: UUID of player Pizzarules668 is 60c64411-c692-4999-8706-616f488a4a7c
[15:19:31] [Server thread/ERROR]: Could not pass event PlayerJoinEvent to GrimAC v2.3.43
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.players.PlayerList.a(PlayerList.java:308) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3811-Spigot-c62f4bd-85b89c3]
        at net.minecraft.server.network.LoginListener.a(LoginListener.java:183) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3811-Spigot-c62f4bd-85b89c3]
        at net.minecraft.server.network.LoginListener.d(LoginListener.java:169) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3811-Spigot-c62f4bd-85b89c3]
        at net.minecraft.server.network.LoginListener.c(LoginListener.java:75) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3811-Spigot-c62f4bd-85b89c3]
        at net.minecraft.network.NetworkManager.a(NetworkManager.java:285) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3811-Spigot-c62f4bd-85b89c3]
        at net.minecraft.server.network.ServerConnection.c(ServerConnection.java:175) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3811-Spigot-c62f4bd-85b89c3]
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1324) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3811-Spigot-c62f4bd-85b89c3]
        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:388) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3811-Spigot-c62f4bd-85b89c3]
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1198) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3811-Spigot-c62f4bd-85b89c3]
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1015) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3811-Spigot-c62f4bd-85b89c3]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3811-Spigot-c62f4bd-85b89c3]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NoSuchMethodError: 'io.papermc.paper.threadedregions.scheduler.AsyncScheduler org.bukkit.Bukkit.getAsyncScheduler()'
        at co.aikar.commands.ACFFoliaScheduler.createDelayedTask(ACFFoliaScheduler.java:45) ~[?:?]
        at co.aikar.commands.ACFBukkitListener.onPlayerJoin(ACFBukkitListener.java:58) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        ... 15 more
[15:19:31] [Server thread/INFO]: Pizzarules668 joined the game
[15:19:31] [Server thread/INFO]: Pizzarules668[/10.145.24.131:44138] logged in with entity id 11055 at ([world]-2148.5, 64.0, -1081.5)
```

### How to replicate it if known

When any user joins the server this happens

### Grim version

I am running v2.4.43 downloaded from spigot

### Server version

This server is running CraftBukkit version 3811-Spigot-c62f4bd-85b89c3 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT)

### Plugins

Plugins (17): SimpleTpa, LuckPerms, WorldEdit, SerialKey, OpenInv, iShop, Nicknames, floodgate, ProtocolLib, dynmap, XClaim, DiscordSRV, VanishNoPacket, Orebfuscator, DiscordSRV-Staff-Chat, Geyser-Spigot, GrimAC

**Comment by SamB440** [comment]
Feel free to comment if you can reproduce this on the latest Grim. This has most likely been fixed by ACF.
