### ISSUE TITLE
Failed to map the Packet ID 111 to a PacketType constant

### ISSUE THREAD

**Issue by tomkimberlin** [GrimAnticheat/Grim#1183]
### Stack trace

```
[17:22:27 WARN]: io.netty.handler.codec.EncoderException: ac.grim.grimac.shaded.com.github.retrooper.packetevents.exception.PacketProcessException: Failed to map the Packet ID 111 to a PacketType constant. Bound: CLIENT, Connection state: PLAY, Server version: 1.20.1
[17:22:27 WARN]:        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:107)
[17:22:27 WARN]:        at grimac-2.3.45.jar//ac.grim.grimac.shaded.io.github.retrooper.packetevents.injector.handlers.PacketEventsEncoder.write(PacketEventsEncoder.java:101)
[17:22:27 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[17:22:27 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[17:22:27 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[17:22:27 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[17:22:27 WARN]:        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113)
[17:22:27 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[17:22:27 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[17:22:27 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[17:22:27 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[17:22:27 WARN]:        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:113)
[17:22:27 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[17:22:27 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:940)
[17:22:27 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:966)
[17:22:27 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:934)
[17:22:27 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:984)
[17:22:27 WARN]:        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025)
[17:22:27 WARN]:        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306)
[17:22:27 WARN]:        at net.minecraft.network.NetworkManager.c(NetworkManager.java:448)
[17:22:27 WARN]:        at net.minecraft.network.NetworkManager.lambda$sendPacket$10(NetworkManager.java:433)
[17:22:27 WARN]:        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
[17:22:27 WARN]:        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
[17:22:27 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
[17:22:27 WARN]:        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:413)
[17:22:27 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[17:22:27 WARN]:        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[17:22:27 WARN]:        at java.base/java.lang.Thread.run(Unknown Source)
[17:22:27 WARN]: Caused by: ac.grim.grimac.shaded.com.github.retrooper.packetevents.exception.PacketProcessException: Failed to map the Packet ID 111 to a PacketType constant. Bound: CLIENT, Connection state: PLAY, Server version: 1.20.1
[17:22:27 WARN]:        at grimac-2.3.45.jar//ac.grim.grimac.shaded.com.github.retrooper.packetevents.event.ProtocolPacketEvent.<init>(ProtocolPacketEvent.java:88)
[17:22:27 WARN]:        at grimac-2.3.45.jar//ac.grim.grimac.shaded.com.github.retrooper.packetevents.event.PacketSendEvent.<init>(PacketSendEvent.java:37)
[17:22:27 WARN]:        at grimac-2.3.45.jar//ac.grim.grimac.shaded.com.github.retrooper.packetevents.event.simple.PacketPlaySendEvent.<init>(PacketPlaySendEvent.java:33)
[17:22:27 WARN]:        at grimac-2.3.45.jar//ac.grim.grimac.shaded.com.github.retrooper.packetevents.util.EventCreationUtil.createSendEvent(EventCreationUtil.java:53)
[17:22:27 WARN]:        at grimac-2.3.45.jar//ac.grim.grimac.shaded.com.github.retrooper.packetevents.util.PacketEventsImplHelper.handleClientBoundPacket(PacketEventsImplHelper.java:42)
[17:22:27 WARN]:        at grimac-2.3.45.jar//ac.grim.grimac.shaded.io.github.retrooper.packetevents.injector.handlers.PacketEventsEncoder.handleClientBoundPacket(PacketEventsEncoder.java:82)
[17:22:27 WARN]:        at grimac-2.3.45.jar//ac.grim.grimac.shaded.io.github.retrooper.packetevents.injector.handlers.PacketEventsEncoder.encode(PacketEventsEncoder.java:67)
[17:22:27 WARN]:        at grimac-2.3.45.jar//ac.grim.grimac.shaded.io.github.retrooper.packetevents.injector.handlers.PacketEventsEncoder.encode(PacketEventsEncoder.java:46)
[17:22:27 WARN]:        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:90)
[17:22:27 WARN]:        ... 27 more
[17:22:27 WARN]: io.netty.handler.codec.EncoderException: ac.grim.grimac.shaded.com.github.retrooper.packetevents.exception.PacketProcessException: Failed to map the Packet ID 111 to a PacketType constant. Bound: CLIENT, Connection state: PLAY, Server version: 1.20.1
[17:22:27 WARN]:        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:107)
[17:22:27 WARN]:        at grimac-2.3.45.jar//ac.grim.grimac.shaded.io.github.retrooper.packetevents.injector.handlers.PacketEventsEncoder.write(PacketEventsEncoder.java:101)
[17:22:27 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[17:22:27 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[17:22:27 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[17:22:27 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[17:22:27 WARN]:        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113)
[17:22:27 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[17:22:27 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[17:22:27 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[17:22:27 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[17:22:27 WARN]:        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:113)
[17:22:27 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[17:22:27 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:940)
[17:22:27 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:966)
[17:22:27 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:934)
[17:22:27 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:984)
[17:22:27 WARN]:        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025)
[17:22:27 WARN]:        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306)
[17:22:27 WARN]:        at net.minecraft.network.NetworkManager.c(NetworkManager.java:448)
[17:22:27 WARN]:        at net.minecraft.network.NetworkManager.lambda$sendPacket$10(NetworkManager.java:433)
[17:22:27 WARN]:        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
[17:22:27 WARN]:        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
[17:22:27 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
[17:22:27 WARN]:        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:413)
[17:22:27 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[17:22:27 WARN]:        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[17:22:27 WARN]:        at java.base/java.lang.Thread.run(Unknown Source)
[17:22:27 WARN]: Caused by: ac.grim.grimac.shaded.com.github.retrooper.packetevents.exception.PacketProcessException: Failed to map the Packet ID 111 to a PacketType constant. Bound: CLIENT, Connection state: PLAY, Server version: 1.20.1
[17:22:27 WARN]:        at grimac-2.3.45.jar//ac.grim.grimac.shaded.com.github.retrooper.packetevents.event.ProtocolPacketEvent.<init>(ProtocolPacketEvent.java:88)
[17:22:27 WARN]:        at grimac-2.3.45.jar//ac.grim.grimac.shaded.com.github.retrooper.packetevents.event.PacketSendEvent.<init>(PacketSendEvent.java:37)
[17:22:27 WARN]:        at grimac-2.3.45.jar//ac.grim.grimac.shaded.com.github.retrooper.packetevents.event.simple.PacketPlaySendEvent.<init>(PacketPlaySendEvent.java:33)
[17:22:27 WARN]:        at grimac-2.3.45.jar//ac.grim.grimac.shaded.com.github.retrooper.packetevents.util.EventCreationUtil.createSendEvent(EventCreationUtil.java:53)
[17:22:27 WARN]:        at grimac-2.3.45.jar//ac.grim.grimac.shaded.com.github.retrooper.packetevents.util.PacketEventsImplHelper.handleClientBoundPacket(PacketEventsImplHelper.java:42)
[17:22:27 WARN]:        at grimac-2.3.45.jar//ac.grim.grimac.shaded.io.github.retrooper.packetevents.injector.handlers.PacketEventsEncoder.handleClientBoundPacket(PacketEventsEncoder.java:82)
[17:22:27 WARN]:        at grimac-2.3.45.jar//ac.grim.grimac.shaded.io.github.retrooper.packetevents.injector.handlers.PacketEventsEncoder.encode(PacketEventsEncoder.java:67)
[17:22:27 WARN]:        at grimac-2.3.45.jar//ac.grim.grimac.shaded.io.github.retrooper.packetevents.injector.handlers.PacketEventsEncoder.encode(PacketEventsEncoder.java:46)
[17:22:27 WARN]:        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:90)
[17:22:27 WARN]:        ... 27 more
[17:22:27 WARN]: [ac.grim.grimac.shaded.com.github.retrooper.packetevents.PacketEventsAPI] PacketEvents caught an unhandled exception while calling your listener.
java.lang.IndexOutOfBoundsException: readerIndex(1) + length(8) exceeds writerIndex(6): PooledUnsafeDirectByteBuf(ridx: 1, widx: 6, cap: 256)
        at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1442) ~[netty-buffer-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.buffer.AbstractByteBuf.readLong(AbstractByteBuf.java:835) ~[netty-buffer-4.1.97.Final.jar:4.1.97.Final]
        at ac.grim.grimac.shaded.io.github.retrooper.packetevents.netty.buffer.ByteBufOperatorModernImpl.readLong(ByteBufOperatorModernImpl.java:94) ~[grimac-2.3.45.jar:?]
        at ac.grim.grimac.shaded.com.github.retrooper.packetevents.netty.buffer.ByteBufOperator.readDouble(ByteBufOperator.java:84) ~[grimac-2.3.45.jar:?]
        at ac.grim.grimac.shaded.com.github.retrooper.packetevents.netty.buffer.ByteBufHelper.readDouble(ByteBufHelper.java:135) ~[grimac-2.3.45.jar:?]
        at ac.grim.grimac.shaded.com.github.retrooper.packetevents.wrapper.PacketWrapper.readDouble(PacketWrapper.java:510) ~[grimac-2.3.45.jar:?]
        at ac.grim.grimac.shaded.com.github.retrooper.packetevents.wrapper.play.server.WrapperPlayServerExplosion.read(WrapperPlayServerExplosion.java:54) ~[grimac-2.3.45.jar:?]
        at ac.grim.grimac.shaded.com.github.retrooper.packetevents.wrapper.PacketWrapper.readEvent(PacketWrapper.java:175) ~[grimac-2.3.45.jar:?]
        at ac.grim.grimac.shaded.com.github.retrooper.packetevents.wrapper.PacketWrapper.<init>(PacketWrapper.java:120) ~[grimac-2.3.45.jar:?]
        at ac.grim.grimac.shaded.com.github.retrooper.packetevents.wrapper.PacketWrapper.<init>(PacketWrapper.java:110) ~[grimac-2.3.45.jar:?]
        at ac.grim.grimac.shaded.com.github.retrooper.packetevents.wrapper.play.server.WrapperPlayServerExplosion.<init>(WrapperPlayServerExplosion.java:40) ~[grimac-2.3.45.jar:?]
        at ac.grim.grimac.checks.impl.velocity.ExplosionHandler.onPacketSend(ExplosionHandler.java:42) ~[grimac-2.3.45.jar:?]
        at ac.grim.grimac.manager.CheckManager.onPacketSend(CheckManager.java:189) ~[grimac-2.3.45.jar:?]
        at ac.grim.grimac.events.packets.CheckManagerListener.onPacketSend(CheckManagerListener.java:793) ~[grimac-2.3.45.jar:?]
        at ac.grim.grimac.shaded.com.github.retrooper.packetevents.event.PacketSendEvent.call(PacketSendEvent.java:51) ~[grimac-2.3.45.jar:?]
        at ac.grim.grimac.shaded.com.github.retrooper.packetevents.event.EventManager.callEvent(EventManager.java:52) ~[grimac-2.3.45.jar:?]
        at ac.grim.grimac.shaded.com.github.retrooper.packetevents.util.PacketEventsImplHelper.handleClientBoundPacket(PacketEventsImplHelper.java:44) ~[grimac-2.3.45.jar:?]
        at ac.grim.grimac.shaded.io.github.retrooper.packetevents.injector.handlers.PacketEventsEncoder.handleClientBoundPacket(PacketEventsEncoder.java:82) ~[grimac-2.3.45.jar:?]
        at ac.grim.grimac.shaded.io.github.retrooper.packetevents.injector.handlers.PacketEventsEncoder.encode(PacketEventsEncoder.java:67) ~[grimac-2.3.45.jar:?]
        at ac.grim.grimac.shaded.io.github.retrooper.packetevents.injector.handlers.PacketEventsEncoder.encode(PacketEventsEncoder.java:46) ~[grimac-2.3.45.jar:?]
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:90) ~[netty-codec-4.1.97.Final.jar:4.1.97.Final]
        at ac.grim.grimac.shaded.io.github.retrooper.packetevents.injector.handlers.PacketEventsEncoder.write(PacketEventsEncoder.java:101) ~[grimac-2.3.45.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113) ~[netty-codec-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:113) ~[netty-codec-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:940) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:966) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:934) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:984) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at net.minecraft.network.Connection.doSendPacket(Connection.java:448) ~[?:?]
        at net.minecraft.network.Connection.lambda$sendPacket$10(Connection.java:433) ~[?:?]
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:413) ~[netty-transport-classes-epoll-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
        at java.lang.Thread.run(Unknown Source) ~[?:?]
[17:22:27 WARN]: [ac.grim.grimac.shaded.com.github.retrooper.packetevents.PacketEventsAPI] PacketEvents caught an unhandled exception while calling your listener.
java.lang.IndexOutOfBoundsException: readerIndex(35) + length(1) exceeds writerIndex(35): PooledUnsafeDirectByteBuf(ridx: 35, widx: 35, cap: 256)
        at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1442) ~[netty-buffer-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.buffer.AbstractByteBuf.readByte(AbstractByteBuf.java:730) ~[netty-buffer-4.1.97.Final.jar:4.1.97.Final]
        at ac.grim.grimac.shaded.io.github.retrooper.packetevents.netty.buffer.ByteBufOperatorModernImpl.readByte(ByteBufOperatorModernImpl.java:74) ~[grimac-2.3.45.jar:?]
        at ac.grim.grimac.shaded.com.github.retrooper.packetevents.netty.buffer.ByteBufHelper.readByte(ByteBufHelper.java:67) ~[grimac-2.3.45.jar:?]
        at ac.grim.grimac.shaded.com.github.retrooper.packetevents.wrapper.PacketWrapper.readByte(PacketWrapper.java:218) ~[grimac-2.3.45.jar:?]
        at ac.grim.grimac.shaded.com.github.retrooper.packetevents.wrapper.PacketWrapper.readVarInt(PacketWrapper.java:250) ~[grimac-2.3.45.jar:?]
        at ac.grim.grimac.shaded.com.github.retrooper.packetevents.wrapper.play.server.WrapperPlayServerDestroyEntities.read(WrapperPlayServerDestroyEntities.java:58) ~[grimac-2.3.45.jar:?]
        at ac.grim.grimac.shaded.com.github.retrooper.packetevents.wrapper.PacketWrapper.readEvent(PacketWrapper.java:175) ~[grimac-2.3.45.jar:?]
        at ac.grim.grimac.shaded.com.github.retrooper.packetevents.wrapper.PacketWrapper.<init>(PacketWrapper.java:120) ~[grimac-2.3.45.jar:?]
        at ac.grim.grimac.shaded.com.github.retrooper.packetevents.wrapper.PacketWrapper.<init>(PacketWrapper.java:110) ~[grimac-2.3.45.jar:?]
        at ac.grim.grimac.shaded.com.github.retrooper.packetevents.wrapper.play.server.WrapperPlayServerDestroyEntities.<init>(WrapperPlayServerDestroyEntities.java:30) ~[grimac-2.3.45.jar:?]
        at ac.grim.grimac.events.packets.PacketEntityReplication.onPacketSend(PacketEntityReplication.java:289) ~[grimac-2.3.45.jar:?]
        at ac.grim.grimac.manager.CheckManager.onPacketSend(CheckManager.java:186) ~[grimac-2.3.45.jar:?]
        at ac.grim.grimac.events.packets.CheckManagerListener.onPacketSend(CheckManagerListener.java:793) ~[grimac-2.3.45.jar:?]
        at ac.grim.grimac.shaded.com.github.retrooper.packetevents.event.PacketSendEvent.call(PacketSendEvent.java:51) ~[grimac-2.3.45.jar:?]
        at ac.grim.grimac.shaded.com.github.retrooper.packetevents.event.EventManager.callEvent(EventManager.java:52) ~[grimac-2.3.45.jar:?]
        at ac.grim.grimac.shaded.com.github.retrooper.packetevents.util.PacketEventsImplHelper.handleClientBoundPacket(PacketEventsImplHelper.java:44) ~[grimac-2.3.45.jar:?]
        at ac.grim.grimac.shaded.io.github.retrooper.packetevents.injector.handlers.PacketEventsEncoder.handleClientBoundPacket(PacketEventsEncoder.java:82) ~[grimac-2.3.45.jar:?]
        at ac.grim.grimac.shaded.io.github.retrooper.packetevents.injector.handlers.PacketEventsEncoder.encode(PacketEventsEncoder.java:67) ~[grimac-2.3.45.jar:?]
        at ac.grim.grimac.shaded.io.github.retrooper.packetevents.injector.handlers.PacketEventsEncoder.encode(PacketEventsEncoder.java:46) ~[grimac-2.3.45.jar:?]
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:90) ~[netty-codec-4.1.97.Final.jar:4.1.97.Final]
        at ac.grim.grimac.shaded.io.github.retrooper.packetevents.injector.handlers.PacketEventsEncoder.write(PacketEventsEncoder.java:101) ~[grimac-2.3.45.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113) ~[netty-codec-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:113) ~[netty-codec-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:940) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:966) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:934) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:984) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at net.minecraft.network.Connection.doSendPacket(Connection.java:448) ~[?:?]
        at net.minecraft.network.Connection.lambda$sendPacket$10(Connection.java:433) ~[?:?]
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:413) ~[netty-transport-classes-epoll-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
        at java.lang.Thread.run(Unknown Source) ~[?:?]
```

### How to replicate it if known

Join a 1.20.2 Paper server with GrimAC installed

### Grim version

2.3.45

### Server version

git-Paper-230 (MC: 1.20.2)

### Plugins

GrimAC

**Comment by AoElite** [comment]
@tomkimberlin Please use the latest commit, it was just pushed a few minutes ago.
