### ISSUE TITLE
Server crashes when I login from another location

### ISSUE THREAD

**Issue by wafflerdot** [GrimAnticheat/Grim#1189]
### Stack trace

[21:14:06 ERROR]: Encountered an unexpected exception
java.lang.IllegalArgumentException: Can't get common connection state: LOGIN != CONFIGURATION
        at ac.grim.grimac.shaded.com.github.retrooper.packetevents.protocol.player.User.getConnectionState(User.java:77) ~[grimac-2.3.46.jar:?]
        at ac.grim.grimac.player.GrimPlayer.sendTransaction(GrimPlayer.java:358) ~[grimac-2.3.46.jar:?]
        at ac.grim.grimac.events.packets.PacketEntityReplication.onEndOfTickEvent(PacketEntityReplication.java:444) ~[grimac-2.3.46.jar:?]
        at ac.grim.grimac.manager.init.start.TickEndEvent.tickRelMove(TickEndEvent.java:25) ~[grimac-2.3.46.jar:?]
        at ac.grim.grimac.manager.init.start.TickEndEvent.access$000(TickEndEvent.java:19) ~[grimac-2.3.46.jar:?]
        at ac.grim.grimac.manager.init.start.TickEndEvent$1.onIterator(TickEndEvent.java:51) ~[grimac-2.3.46.jar:?]
        at ac.grim.grimac.utils.lists.HookedListWrapper.iterator(HookedListWrapper.java:35) ~[grimac-2.3.46.jar:?]
        at java.util.Collections$SynchronizedCollection.iterator(Collections.java:2100) ~[?:?]
        at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:232) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1607) ~[purpur-1.20.2.jar:git-Purpur-2083]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:486) ~[purpur-1.20.2.jar:git-Purpur-2083]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1406) ~[purpur-1.20.2.jar:git-Purpur-2083]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1177) ~[purpur-1.20.2.jar:git-Purpur-2083]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[purpur-1.20.2.jar:git-Purpur-2083]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

### How to replicate it if known

1. Login to the server
2. Login from another game window using the same account to the server
3. First account gets kicked, server immediately crashes

### Grim version

Commit 72751d3 (latest)

### Server version

git-Purpur-2084 (MC: 1.20.2)
Latest version

### Plugins

![image](https://github.com/GrimAnticheat/Grim/assets/35065682/9213a978-2e8e-44cf-92ee-e716df619a41)

**Comment by MWHunter** [comment]
PacketEvents issue, not a grim issue
