### ISSUE TITLE
Error on Paper 1.16.5 and ViaVersion

### ISSUE THREAD

**Issue by iSnakeBuzz** [GrimAnticheat/Grim#1300]
### Stack trace

```shell
[22:20:13] [Netty Epoll Server IO #1/WARN]: io.netty.handler.codec.EncoderException: ac.grim.grimac.shaded.com.github.retrooper.packetevents.exception.PacketProcessException: Failed to map the Packet ID 36 to a PacketType constant. Bound: CLIENT, Connection state: LOGIN, Server version: 1.8.8
[22:20:13] [Netty Epoll Server IO #1/WARN]: 	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:104)
[22:20:13] [Netty Epoll Server IO #1/WARN]: 	at ac.grim.grimac.shaded.io.github.retrooper.packetevents.injector.handlers.PacketEventsEncoder.write(PacketEventsEncoder.java:101)
[22:20:13] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[22:20:13] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
[22:20:13] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
[22:20:13] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
[22:20:13] [Netty Epoll Server IO #1/WARN]: 	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113)
[22:20:13] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[22:20:13] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)
[22:20:13] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
[22:20:13] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758)
[22:20:13] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:767)
[22:20:13] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
[22:20:13] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758)
[22:20:13] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:767)
[22:20:13] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
[22:20:13] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758)
[22:20:13] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:808)
[22:20:13] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025)
[22:20:13] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:294)
[22:20:13] [Netty Epoll Server IO #1/WARN]: 	at net.minecraft.server.v1_16_R3.NetworkManager$1.run(NetworkManager.java:450)
[22:20:13] [Netty Epoll Server IO #1/WARN]: 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
[22:20:13] [Netty Epoll Server IO #1/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
[22:20:13] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384)
[22:20:13] [Netty Epoll Server IO #1/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
[22:20:13] [Netty Epoll Server IO #1/WARN]: 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[22:20:13] [Netty Epoll Server IO #1/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:840)
[22:20:13] [Netty Epoll Server IO #1/WARN]: Caused by: ac.grim.grimac.shaded.com.github.retrooper.packetevents.exception.PacketProcessException: Failed to map the Packet ID 36 to a PacketType constant. Bound: CLIENT, Connection state: LOGIN, Server version: 1.8.8
[22:20:13] [Netty Epoll Server IO #1/WARN]: 	at ac.grim.grimac.shaded.com.github.retrooper.packetevents.event.ProtocolPacketEvent.<init>(ProtocolPacketEvent.java:89)
[22:20:13] [Netty Epoll Server IO #1/WARN]: 	at ac.grim.grimac.shaded.com.github.retrooper.packetevents.event.PacketSendEvent.<init>(PacketSendEvent.java:37)
[22:20:13] [Netty Epoll Server IO #1/WARN]: 	at ac.grim.grimac.shaded.com.github.retrooper.packetevents.event.simple.PacketLoginSendEvent.<init>(PacketLoginSendEvent.java:32)
[22:20:13] [Netty Epoll Server IO #1/WARN]: 	at ac.grim.grimac.shaded.com.github.retrooper.packetevents.util.EventCreationUtil.createSendEvent(EventCreationUtil.java:53)
[22:20:13] [Netty Epoll Server IO #1/WARN]: 	at ac.grim.grimac.shaded.com.github.retrooper.packetevents.util.PacketEventsImplHelper.handleClientBoundPacket(PacketEventsImplHelper.java:42)
[22:20:13] [Netty Epoll Server IO #1/WARN]: 	at ac.grim.grimac.shaded.io.github.retrooper.packetevents.injector.handlers.PacketEventsEncoder.handleClientBoundPacket(PacketEventsEncoder.java:82)
[22:20:13] [Netty Epoll Server IO #1/WARN]: 	at ac.grim.grimac.shaded.io.github.retrooper.packetevents.injector.handlers.PacketEventsEncoder.encode(PacketEventsEncoder.java:67)
[22:20:13] [Netty Epoll Server IO #1/WARN]: 	at ac.grim.grimac.shaded.io.github.retrooper.packetevents.injector.handlers.PacketEventsEncoder.encode(PacketEventsEncoder.java:46)
[22:20:13] [Netty Epoll Server IO #1/WARN]: 	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:89)
[22:20:13] [Netty Epoll Server IO #1/WARN]: 	... 26 more
``` 

### How to replicate it if known

Just try to join with minecraft client 1.20.4

### Grim version

2.3.54

### Server version

Paper 1.16.5

### Plugins

[ViaVersion-4.9.3](https://ci.viaversion.com/job/ViaVersion/lastSuccessfulBuild/artifact/build/libs/ViaVersion-4.9.3-SNAPSHOT.jar)
PlaceholderAPI
Custom Core

**Comment by SamB440** [comment]
Feel free to open a new issue if you can reproduce this on the latest Grim.
