### ISSUE TITLE
can't load in folia 1.20.2

### ISSUE THREAD

**Issue by MCFurina** [GrimAnticheat/Grim#1341]
### Stack trace

[17:12:54 INFO]: [GrimAC] Enabling GrimAC v2.3.55
[17:12:54 INFO]: [GrimAC] Registering singular bukkit event... (PistonEvent)
[17:12:54 INFO]: [GrimAC] Registering packets...
[17:12:54 WARN]: java.lang.NoSuchMethodException: net.minecraft.world.item.ItemStack.<init>(net.minecraft.world.item.Item,int)
[17:12:54 WARN]:        at java.base/java.lang.Class.getConstructor0(Unknown Source)
[17:12:54 WARN]:        at java.base/java.lang.Class.getConstructor(Unknown Source)
[17:12:54 WARN]:        at grimac-2.3.55.jar//ac.grim.grimac.shaded.io.github.retrooper.packetevents.util.SpigotReflectionUtil.initConstructors(SpigotReflectionUtil.java:104)
[17:12:54 WARN]:        at grimac-2.3.55.jar//ac.grim.grimac.shaded.io.github.retrooper.packetevents.util.SpigotReflectionUtil.init(SpigotReflectionUtil.java:268)
[17:12:54 WARN]:        at grimac-2.3.55.jar//ac.grim.grimac.shaded.io.github.retrooper.packetevents.factory.spigot.SpigotPacketEventsBuilder$1.load(SpigotPacketEventsBuilder.java:103)
[17:12:54 WARN]:        at grimac-2.3.55.jar//ac.grim.grimac.shaded.io.github.retrooper.packetevents.factory.spigot.SpigotPacketEventsBuilder$1.init(SpigotPacketEventsBuilder.java:136)
[17:12:54 WARN]:        at grimac-2.3.55.jar//ac.grim.grimac.manager.init.start.PacketManager.start(PacketManager.java:44)
[17:12:54 WARN]:        at grimac-2.3.55.jar//ac.grim.grimac.manager.InitManager.start(InitManager.java:50)
[17:12:54 WARN]:        at grimac-2.3.55.jar//ac.grim.grimac.GrimAPI.start(GrimAPI.java:33)
[17:12:54 WARN]:        at grimac-2.3.55.jar//ac.grim.grimac.GrimAC.onEnable(GrimAC.java:19)
[17:12:54 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281)
[17:12:54 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189)
[17:12:54 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104)
[17:12:54 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507)
[17:12:54 WARN]:        at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugin(CraftServer.java:652)
[17:12:54 WARN]:        at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugins(CraftServer.java:563)
[17:12:54 WARN]:        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:670)
[17:12:54 WARN]:        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:452)
[17:12:54 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308)
[17:12:54 WARN]:        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173)
[17:12:54 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:343)
[17:12:54 WARN]:        at java.base/java.lang.Thread.run(Unknown Source)
[17:12:54 ERROR]: Error occurred while enabling GrimAC v2.3.55 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "java.lang.reflect.Field.get(Object)" because the return value of "ac.grim.grimac.shaded.com.github.retrooper.packetevents.util.reflection.Reflection.getField(java.lang.Class, java.lang.Class, int)" is null
        at ac.grim.grimac.shaded.io.github.retrooper.packetevents.util.SpigotReflectionUtil.getMinecraftServerConnectionInstance(SpigotReflectionUtil.java:309) ~[grimac-2.3.55.jar:?]
        at ac.grim.grimac.shaded.io.github.retrooper.packetevents.injector.SpigotChannelInjector.isServerBound(SpigotChannelInjector.java:63) ~[grimac-2.3.55.jar:?]
        at ac.grim.grimac.shaded.io.github.retrooper.packetevents.factory.spigot.SpigotPacketEventsBuilder$1.load(SpigotPacketEventsBuilder.java:114) ~[grimac-2.3.55.jar:?]
        at ac.grim.grimac.shaded.io.github.retrooper.packetevents.factory.spigot.SpigotPacketEventsBuilder$1.init(SpigotPacketEventsBuilder.java:136) ~[grimac-2.3.55.jar:?]
        at ac.grim.grimac.manager.init.start.PacketManager.start(PacketManager.java:44) ~[grimac-2.3.55.jar:?]
        at ac.grim.grimac.manager.InitManager.start(InitManager.java:50) ~[grimac-2.3.55.jar:?]
        at ac.grim.grimac.GrimAPI.start(GrimAPI.java:33) ~[grimac-2.3.55.jar:?]
        at ac.grim.grimac.GrimAC.onEnable(GrimAC.java:19) ~[grimac-2.3.55.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[folia-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[folia-1.20.2.jar:git-Folia-"1e5e215"]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[folia-1.20.2.jar:git-Folia-"1e5e215"]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[folia-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugin(CraftServer.java:652) ~[folia-1.20.2.jar:git-Folia-"1e5e215"]
        at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugins(CraftServer.java:563) ~[folia-1.20.2.jar:git-Folia-"1e5e215"]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:670) ~[folia-1.20.2.jar:git-Folia-"1e5e215"]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:452) ~[folia-1.20.2.jar:git-Folia-"1e5e215"]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[folia-1.20.2.jar:git-Folia-"1e5e215"]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[folia-1.20.2.jar:git-Folia-"1e5e215"]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:343) ~[folia-1.20.2.jar:git-Folia-"1e5e215"]
        at java.lang.Thread.run(Unknown Source) ~[?:?]
[17:12:54 INFO]: [GrimAC] Disabling GrimAC v2.3.55
[17:12:54 INFO]: [GrimAC] Terminating PacketEvents...

### Grim version

grimac-2.3.55

### Server version

git-Folia-"1e5e215" (MC: 1.20.2)

### Plugins

[17:18:47 INFO]: Server Plugins (22):
[17:18:47 INFO]: Paper Plugins:
[17:18:47 INFO]:  - HuskHomes, MiniPlaceholders
[17:18:47 INFO]: Bukkit Plugins:
[17:18:47 INFO]:  - BetterRTP, BlockLocker, CoreProtect, FoliaFlow, GrimAC, GSit, LuckPerms, MiniMOTD, *NoCommands, PlaceholderAPI
[17:18:47 INFO]:  ProtocolLib, *Suicide, TAB, Towny, TownyChat, TownyMenus, ViaBackwards, ViaRewind, ViaVersion

**Comment by SamB440** [comment]
#1359
