### ISSUE TITLE
PacketEvents caught an unhandled exception while calling your listener.

### ISSUE THREAD

**Issue by ZatonDEV** [GrimAnticheat/Grim#1351]
### Stack trace

[22:28:10 WARN]: [ac.grim.grimac.shaded.com.github.retrooper.packetevents.PacketEventsAPI] PacketEvents caught an unhandled exception while calling your listener.
java.lang.RuntimeException: Depth limit reached while decoding component: 13 > 12
        at ac.grim.grimac.shaded.com.github.retrooper.packetevents.util.adventure.AdventureNBTSerialization.readComponent(AdventureNBTSerialization.java:610) ~[grimac-2.3.56.jar:?]
        at ac.grim.grimac.shaded.com.github.retrooper.packetevents.util.adventure.AdventureNBTSerialization.readComponentList(AdventureNBTSerialization.java:952) ~[grimac-2.3.56.jar:?]
        at ac.grim.grimac.shaded.com.github.retrooper.packetevents.util.adventure.AdventureNBTSerialization.readComponent(AdventureNBTSerialization.java:728) ~[grimac-2.3.56.jar:?]
        at ac.grim.grimac.shaded.com.github.retrooper.packetevents.util.adventure.AdventureNBTSerialization.readComponentList(AdventureNBTSerialization.java:952) ~[grimac-2.3.56.jar:?]
        at ac.grim.grimac.shaded.com.github.retrooper.packetevents.util.adventure.AdventureNBTSerialization.readComponent(AdventureNBTSerialization.java:728) ~[grimac-2.3.56.jar:?]
        at ac.grim.grimac.shaded.com.github.retrooper.packetevents.util.adventure.AdventureNBTSerialization.readComponentList(AdventureNBTSerialization.java:952) ~[grimac-2.3.56.jar:?]
        at ac.grim.grimac.shaded.com.github.retrooper.packetevents.util.adventure.AdventureNBTSerialization.readComponent(AdventureNBTSerialization.java:728) ~[grimac-2.3.56.jar:?]
        at ac.grim.grimac.shaded.com.github.retrooper.packetevents.util.adventure.AdventureNBTSerialization.readComponentList(AdventureNBTSerialization.java:952) ~[grimac-2.3.56.jar:?]
        at ac.grim.grimac.shaded.com.github.retrooper.packetevents.util.adventure.AdventureNBTSerialization.readComponent(AdventureNBTSerialization.java:728) ~[grimac-2.3.56.jar:?]
        at ac.grim.grimac.shaded.com.github.retrooper.packetevents.util.adventure.AdventureNBTSerialization.readComponentList(AdventureNBTSerialization.java:952) ~[grimac-2.3.56.jar:?]
        at ac.grim.grimac.shaded.com.github.retrooper.packetevents.util.adventure.AdventureNBTSerialization.readComponent(AdventureNBTSerialization.java:728) ~[grimac-2.3.56.jar:?]
        at ac.grim.grimac.shaded.com.github.retrooper.packetevents.util.adventure.AdventureNBTSerialization.readComponentList(AdventureNBTSerialization.java:952) ~[grimac-2.3.56.jar:?]
        at ac.grim.grimac.shaded.com.github.retrooper.packetevents.util.adventure.AdventureNBTSerialization.readComponent(AdventureNBTSerialization.java:728) ~[grimac-2.3.56.jar:?]
        at ac.grim.grimac.shaded.com.github.retrooper.packetevents.util.adventure.AdventureNBTSerialization.readComponentList(AdventureNBTSerialization.java:952) ~[grimac-2.3.56.jar:?]
        at ac.grim.grimac.shaded.com.github.retrooper.packetevents.util.adventure.AdventureNBTSerialization.readComponent(AdventureNBTSerialization.java:728) ~[grimac-2.3.56.jar:?]
        at ac.grim.grimac.shaded.com.github.retrooper.packetevents.util.adventure.AdventureNBTSerialization.readComponentList(AdventureNBTSerialization.java:952) ~[grimac-2.3.56.jar:?]
        at ac.grim.grimac.shaded.com.github.retrooper.packetevents.util.adventure.AdventureNBTSerialization.readComponent(AdventureNBTSerialization.java:728) ~[grimac-2.3.56.jar:?]
        at ac.grim.grimac.shaded.com.github.retrooper.packetevents.util.adventure.AdventureNBTSerialization.readComponentList(AdventureNBTSerialization.java:952) ~[grimac-2.3.56.jar:?]
        at ac.grim.grimac.shaded.com.github.retrooper.packetevents.util.adventure.AdventureNBTSerialization.readComponent(AdventureNBTSerialization.java:728) ~[grimac-2.3.56.jar:?]
        at ac.grim.grimac.shaded.com.github.retrooper.packetevents.util.adventure.AdventureNBTSerialization.readComponentList(AdventureNBTSerialization.java:952) ~[grimac-2.3.56.jar:?]
        at ac.grim.grimac.shaded.com.github.retrooper.packetevents.util.adventure.AdventureNBTSerialization.readComponent(AdventureNBTSerialization.java:728) ~[grimac-2.3.56.jar:?]
        at ac.grim.grimac.shaded.com.github.retrooper.packetevents.util.adventure.AdventureNBTSerialization.readComponentList(AdventureNBTSerialization.java:952) ~[grimac-2.3.56.jar:?]
        at ac.grim.grimac.shaded.com.github.retrooper.packetevents.util.adventure.AdventureNBTSerialization.readComponent(AdventureNBTSerialization.java:728) ~[grimac-2.3.56.jar:?]
        at ac.grim.grimac.shaded.com.github.retrooper.packetevents.util.adventure.AdventureNBTSerialization.readComponentList(AdventureNBTSerialization.java:952) ~[grimac-2.3.56.jar:?]
        at ac.grim.grimac.shaded.com.github.retrooper.packetevents.util.adventure.AdventureNBTSerialization.readComponent(AdventureNBTSerialization.java:728) ~[grimac-2.3.56.jar:?]
        at ac.grim.grimac.shaded.com.github.retrooper.packetevents.util.adventure.AdventureNBTSerialization.readComponentList(AdventureNBTSerialization.java:952) ~[grimac-2.3.56.jar:?]
        at ac.grim.grimac.shaded.com.github.retrooper.packetevents.util.adventure.AdventureNBTSerialization.readComponent(AdventureNBTSerialization.java:728) ~[grimac-2.3.56.jar:?]
        at ac.grim.grimac.shaded.com.github.retrooper.packetevents.util.adventure.AdventureNBTSerialization.readComponent(AdventureNBTSerialization.java:604) ~[grimac-2.3.56.jar:?]
        at ac.grim.grimac.shaded.com.github.retrooper.packetevents.util.adventure.AdventureNBTSerialization.readComponent(AdventureNBTSerialization.java:600) ~[grimac-2.3.56.jar:?]
        at ac.grim.grimac.shaded.com.github.retrooper.packetevents.util.adventure.AdventureNBTSerialization.readComponent(AdventureNBTSerialization.java:595) ~[grimac-2.3.56.jar:?]
        at ac.grim.grimac.shaded.com.github.retrooper.packetevents.wrapper.PacketWrapper.readComponentAsNBT(PacketWrapper.java:529) ~[grimac-2.3.56.jar:?]
        at ac.grim.grimac.shaded.com.github.retrooper.packetevents.wrapper.PacketWrapper.readComponent(PacketWrapper.java:524) ~[grimac-2.3.56.jar:?]
        at ac.grim.grimac.shaded.com.github.retrooper.packetevents.protocol.entity.data.EntityDataTypes.lambda$readOptionalComponentDeserializer$34(EntityDataTypes.java:294) ~[grimac-2.3.56.jar:?]
        at ac.grim.grimac.shaded.com.github.retrooper.packetevents.wrapper.PacketWrapper.readEntityMetadata(PacketWrapper.java:817) ~[grimac-2.3.56.jar:?]
        at ac.grim.grimac.shaded.com.github.retrooper.packetevents.wrapper.play.server.WrapperPlayServerEntityMetadata.read(WrapperPlayServerEntityMetadata.java:52) ~[grimac-2.3.56.jar:?]
        at ac.grim.grimac.shaded.com.github.retrooper.packetevents.wrapper.PacketWrapper.readEvent(PacketWrapper.java:238) ~[grimac-2.3.56.jar:?]
        at ac.grim.grimac.shaded.com.github.retrooper.packetevents.wrapper.PacketWrapper.<init>(PacketWrapper.java:143) ~[grimac-2.3.56.jar:?]
        at ac.grim.grimac.shaded.com.github.retrooper.packetevents.wrapper.PacketWrapper.<init>(PacketWrapper.java:133) ~[grimac-2.3.56.jar:?]
        at ac.grim.grimac.shaded.com.github.retrooper.packetevents.wrapper.play.server.WrapperPlayServerEntityMetadata.<init>(WrapperPlayServerEntityMetadata.java:36) ~[grimac-2.3.56.jar:?]
        at ac.grim.grimac.events.packets.PacketSetWrapperNull.onPacketSend(PacketSetWrapperNull.java:34) ~[grimac-2.3.56.jar:?]
        at ac.grim.grimac.shaded.com.github.retrooper.packetevents.event.PacketSendEvent.call(PacketSendEvent.java:51) ~[grimac-2.3.56.jar:?]
        at ac.grim.grimac.shaded.com.github.retrooper.packetevents.event.EventManager.callEvent(EventManager.java:52) ~[grimac-2.3.56.jar:?]
        at ac.grim.grimac.shaded.com.github.retrooper.packetevents.util.PacketEventsImplHelper.handleClientBoundPacket(PacketEventsImplHelper.java:44) ~[grimac-2.3.56.jar:?]
        at ac.grim.grimac.shaded.io.github.retrooper.packetevents.injector.handlers.PacketEventsEncoder.handleClientBoundPacket(PacketEventsEncoder.java:82) ~[grimac-2.3.56.jar:?]
        at ac.grim.grimac.shaded.io.github.retrooper.packetevents.injector.handlers.PacketEventsEncoder.encode(PacketEventsEncoder.java:67) ~[grimac-2.3.56.jar:?]
        at ac.grim.grimac.shaded.io.github.retrooper.packetevents.injector.handlers.PacketEventsEncoder.encode(PacketEventsEncoder.java:46) ~[grimac-2.3.56.jar:?]
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:90) ~[netty-codec-4.1.97.Final.jar:4.1.97.Final]
        at ac.grim.grimac.shaded.io.github.retrooper.packetevents.injector.handlers.PacketEventsEncoder.write(PacketEventsEncoder.java:101) ~[grimac-2.3.56.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113) ~[netty-codec-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:120) ~[netty-codec-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:851) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.handler.codec.MessageToMessageEncoder.writePromiseCombiner(MessageToMessageEncoder.java:140) ~[netty-codec-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:120) ~[netty-codec-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at me.neznamy.tab.shared.features.injection.NettyPipelineInjector$TabChannelDuplexHandler.write(NettyPipelineInjector.java:134) ~[TAB.v4.1.2.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:879) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at dev.geco.gsit.mcv.v1_20_3.util.PackageUtil$1.write(PackageUtil.java:90) ~[GSit-1.7.0.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:879) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at de.codingair.tradesystem.lib.codingapi.player.data.PacketReader$1.write(PacketReader.java:77) ~[TradeSystem_v2.5.2.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:879) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at de.codingair.tradesystem.lib.codingapi.player.data.PacketReader$1.write(PacketReader.java:77) ~[TradeSystem_v2.5.2.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:879) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.DefaultChannelPipeline.write(DefaultChannelPipeline.java:1015) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannel.write(AbstractChannel.java:301) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.write(NettyChannelProxy.java:210) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.write(NettyChannelProxy.java:199) ~[ProtocolLib.jar:?]
        at net.minecraft.network.Connection.doSendPacket(Connection.java:448) ~[?:?]
        at net.minecraft.network.Connection.lambda$sendPacket$10(Connection.java:433) ~[?:?]
        at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.lambda$proxyAction$7(NettyChannelInjector.java:592) ~[ProtocolLib.jar:?]
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:413) ~[netty-transport-classes-epoll-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]

### How to replicate it if known

I don't know, it keeps spamming this in the console.

### Grim version

2.3.56

### Server version

This server is running Paper version git-Paper-409 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 9e171ef)

### Plugins

[22:41:44 INFO]: Bukkit Plugins:
ajLeaderboards, AutoMessage, BeastLib, BeastWithdraw, BetterRTP, Chunky Citizens, CMILib, DecentHolograms, DeluxeMenus, Essentials, EssentialsChat, EssentialsProtect, EssentialsSpawn, ExcellentCrates, GrimAC,  GSit, HeadDatabase, Images, ItemEdit, Jobs, LiteBans, LuckPerms, Marriage, Multiverse-Core, MyCommand, NexEngine, NoChatReports, Pl-Hide-Pro, PlaceholderAPI,  ProtocolLib, Quests, RealMines, Sellwand, ShopGUIPlus, Shopkeepers, TAB, TradeSystem, Vault, ViaBackwards, ViaVersion, Vouchers, WorldBorder, WorldEdit, WorldGuard, zAuctionHouseV3

**Comment by Tryflle** [comment]
god please fix this lmfao

**Comment by AoElite** [comment]
@ZatonDEV try updating to latest build

**Comment by xeri** [comment]
For me it still appears to have the same error spam. Running latest grim build
