### ISSUE TITLE
"Duplication of items"

### ISSUE THREAD

**Issue by vladyaso** [GrimAnticheat/Grim#1354]
### Describe the bug and how to replicate it

"Somehow, a player on my server got bugged in such a way that when they reconnect to the server, they die, effectively duplicating items (because they die each time they reconnect and drop resources)."

[14:49:28] [Server thread/INFO]: whzcarik issued server command: /clan home baza
[14:49:28] [Server thread/ERROR]: Could not pass event PlayerTeleportEvent to FunTimeNPC v1.0
java.lang.NullPointerException: Cannot read field "player" because "repository" is null
	at com.akamex.funtime.npc.bukkit.impl.entity.WorldRepository.addPlayerRepository(WorldRepository.java:44) ~[?:?]
	at com.akamex.funtime.npc.bukkit.impl.entity.EntityManager.updatePlayer(EntityManager.java:139) ~[?:?]
	at com.akamex.funtime.npc.bukkit.impl.entity.listener.PlayerListener.onPlayerTeleport(PlayerListener.java:30) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor101.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(:69) ~[patched_1.16.5.jar:git-Airplane-"e37fa86"]
	at co.aikar.timings.TimedEventExecutor.execute(:76) ~[patched_1.16.5.jar:git-Airplane-"e37fa86"]
	at org.bukkit.plugin.RegisteredListener.callEvent(:70) ~[patched_1.16.5.jar:git-Airplane-"e37fa86"]
	at org.bukkit.plugin.SimplePluginManager.callEvent(:624) ~[patched_1.16.5.jar:git-Airplane-"e37fa86"]
	at org.bukkit.craftbukkit.v1_16_R3.entity.CraftPlayer.teleport(:895) ~[patched_1.16.5.jar:git-Airplane-"e37fa86"]
	at org.bukkit.craftbukkit.v1_16_R3.entity.CraftEntity.teleport(:544) ~[patched_1.16.5.jar:git-Airplane-"e37fa86"]
	at basherclansft.player_commands.HomeCmd.lambda$2(HomeCmd.java:56) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(:101) ~[patched_1.16.5.jar:git-Airplane-"e37fa86"]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(:485) ~[patched_1.16.5.jar:git-Airplane-"e37fa86"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.b(:1501) ~[patched_1.16.5.jar:git-Airplane-"e37fa86"]
	at net.minecraft.server.v1_16_R3.DedicatedServer.b(:451) ~[patched_1.16.5.jar:git-Airplane-"e37fa86"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(:1414) ~[patched_1.16.5.jar:git-Airplane-"e37fa86"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(:1140) ~[patched_1.16.5.jar:git-Airplane-"e37fa86"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$1(:289) ~[patched_1.16.5.jar:git-Airplane-"e37fa86"]
	at java.lang.Thread.run(Thread.java:831) [?:?]
[14:49:28] [Server thread/WARN]: java.lang.Throwable: [ERROR] Illegal PlayerChunkMap::addEntity for world world: EntityPlayer['whzcarik'/632407, uuid='46c58502-ada3-33cb-9a49-9c983675b92f', l='ServerLevel[world_nether]', x=-1157.04, y=10.50, z=-2152.31, cx=-73, cz=-135, tl=5019992, v=true, d=false](whzcarik at -1157.0372899884119,10.5,-2152.314011618944)
[14:49:28] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.PlayerChunkMap.addEntity(:2104)
[14:49:28] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.ChunkProviderServer.addEntity(:1205)
[14:49:28] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.WorldServer.registerEntity(:2306)
[14:49:28] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.WorldServer.addPlayer0(:1919)
[14:49:28] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.WorldServer.addPlayerJoin(:1895)
[14:49:28] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.PlayerList.postChunkLoadJoin(:347)
[14:49:28] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.PlayerList.lambda$a$1(:300)
[14:49:28] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.PlayerConnection.tick(:259)
[14:49:28] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.NetworkManager.tick(:760)
[14:49:28] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.ServerConnection.c(:187)
[14:49:28] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.b(:1595)
[14:49:28] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.DedicatedServer.b(:451)
[14:49:28] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.a(:1414)
[14:49:28] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.w(:1140)
[14:49:28] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$1(:289)
[14:49:28] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:831)
[14:49:28] [Server thread/WARN]: java.lang.Throwable: [ERROR] Illegal PlayerChunkMap::addEntity for world world_nether: EntityPlayer['whzcarik'/632407, uuid='46c58502-ada3-33cb-9a49-9c983675b92f', l='ServerLevel[world_nether]', x=-1157.04, y=10.50, z=-2152.31, cx=-73, cz=-135, tl=5019992, v=true, d=false](whzcarik at -1157.0372899884119,10.5,-2152.314011618944) ALREADY CONTAINED (This would have crashed your server)
[14:49:28] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.PlayerChunkMap.addEntity(:2104)
[14:49:28] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.PlayerList.postChunkLoadJoin(:388)
[14:49:28] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.PlayerList.lambda$a$1(:300)
[14:49:28] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.PlayerConnection.tick(:259)
[14:49:28] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.NetworkManager.tick(:760)
[14:49:28] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.ServerConnection.c(:187)
[14:49:28] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.b(:1595)
[14:49:28] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.DedicatedServer.b(:451)
[14:49:28] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.a(:1414)
[14:49:28] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.w(:1140)
[14:49:28] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$1(:289)
[14:49:28] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:831)
[14:49:28] [Server thread/INFO]: whzcarik[/185.13.177.205:43774] logged in with entity id 632407 at ([world_nether]-1157.0372899884119, 10.5, -2152.314011618944)
[14:49:28] [Craft Scheduler Thread - 1177 - BasherSanta/WARN]: [BasherSanta] Plugin BasherSanta v1.0 generated an exception while executing task 836379
java.lang.IllegalArgumentException: Cannot measure distance between world_nether and world
	at org.bukkit.Location.distanceSquared(:510) ~[patched_1.16.5.jar:git-Airplane-"e37fa86"]
	at bashersanta.holograms.Hologram.run(Hologram.java:94) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(:101) ~[patched_1.16.5.jar:git-Airplane-"e37fa86"]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(:58) ~[patched_1.16.5.jar:git-Airplane-"e37fa86"]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(:22) ~[patched_1.16.5.jar:git-Airplane-"e37fa86"]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
	at java.lang.Thread.run(Thread.java:831) [?:?]

### Grim version

grimac 2.3.49

### Server version

![image](https://github.com/GrimAnticheat/Grim/assets/110984772/01f93972-d69a-4760-89dd-d919b1d90eb7)

### Plugins

![image](https://github.com/GrimAnticheat/Grim/assets/110984772/445c6d2e-6a2d-4824-84fe-ca6d3259d130)

**Comment by SamB440** [comment]
There is nothing related to Grim in those logs, this is almost certainly not Grim
