### ISSUE TITLE
Grim Packet Events API 

### ISSUE THREAD

**Issue by flufferyomada** [GrimAnticheat/Grim#1458]
### Stack trace

[19:54:25] [Netty Epoll Server IO #0/WARN]: [ac.grim.grimac.shaded.com.github.retrooper.packetevents.PacketEventsAPI] PacketEvents caught an unhandled exception while calling your listener.
java.lang.ClassCastException: class java.lang.String cannot be cast to class ac.grim.grimac.shaded.com.github.retrooper.packetevents.protocol.world.states.enums.East (java.lang.String is in module java.base of loader 'bootstrap'; ac.grim.grimac.shaded.com.github.retrooper.packetevents.protocol.world.states.enums.East is in unnamed module of loader 'grimac-2.3.62.jar' @f970d6e)
	at ac.grim.grimac.shaded.com.github.retrooper.packetevents.protocol.world.states.WrappedBlockState.getEast(WrappedBlockState.java:1160) ~[grimac-2.3.62.jar:?]
	at ac.grim.grimac.utils.collisions.blocks.connecting.DynamicWall.fetch(DynamicWall.java:126) ~[grimac-2.3.62.jar:?]
	at ac.grim.grimac.utils.collisions.datatypes.DynamicCollisionBox.isCollided(DynamicCollisionBox.java:26) ~[grimac-2.3.62.jar:?]
	at ac.grim.grimac.utils.nmsutil.Collisions.getCollisionBoxes(Collisions.java:283) ~[grimac-2.3.62.jar:?]
	at ac.grim.grimac.utils.nmsutil.Collisions.isEmpty(Collisions.java:327) ~[grimac-2.3.62.jar:?]
	at ac.grim.grimac.predictionengine.PlayerBaseTick.canEnterPose(PlayerBaseTick.java:27) ~[grimac-2.3.62.jar:?]
	at ac.grim.grimac.predictionengine.PlayerBaseTick.updatePlayerPose(PlayerBaseTick.java:161) ~[grimac-2.3.62.jar:?]
	at ac.grim.grimac.predictionengine.MovementCheckRunner.check(MovementCheckRunner.java:491) ~[grimac-2.3.62.jar:?]
	at ac.grim.grimac.predictionengine.MovementCheckRunner.processAndCheckMovementPacket(MovementCheckRunner.java:75) ~[grimac-2.3.62.jar:?]
	at ac.grim.grimac.checks.impl.movement.PredictionRunner.onPositionUpdate(PredictionRunner.java:16) ~[grimac-2.3.62.jar:?]
	at ac.grim.grimac.manager.CheckManager.onPositionUpdate(CheckManager.java:212) ~[grimac-2.3.62.jar:?]
	at ac.grim.grimac.events.packets.CheckManagerListener.handleFlying(CheckManagerListener.java:706) ~[grimac-2.3.62.jar:?]
	at ac.grim.grimac.events.packets.CheckManagerListener.onPacketReceive(CheckManagerListener.java:408) ~[grimac-2.3.62.jar:?]
	at ac.grim.grimac.shaded.com.github.retrooper.packetevents.event.PacketReceiveEvent.call(PacketReceiveEvent.java:45) ~[grimac-2.3.62.jar:?]
	at ac.grim.grimac.shaded.com.github.retrooper.packetevents.event.EventManager.callEvent(EventManager.java:52) ~[grimac-2.3.62.jar:?]
	at ac.grim.grimac.shaded.com.github.retrooper.packetevents.util.PacketEventsImplHelper.handleServerBoundPacket(PacketEventsImplHelper.java:82) ~[grimac-2.3.62.jar:?]
	at ac.grim.grimac.shaded.io.github.retrooper.packetevents.injector.handlers.PacketEventsDecoder.read(PacketEventsDecoder.java:56) ~[grimac-2.3.62.jar:?]
	at ac.grim.grimac.shaded.io.github.retrooper.packetevents.injector.handlers.PacketEventsDecoder.decode(PacketEventsDecoder.java:63) ~[grimac-2.3.62.jar:?]
	at ac.grim.grimac.shaded.io.github.retrooper.packetevents.injector.handlers.PacketEventsDecoder.decode(PacketEventsDecoder.java:40) ~[grimac-2.3.62.jar:?]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88) ~[netty-codec-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[netty-codec-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) ~[netty-codec-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318) ~[netty-codec-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) ~[netty-codec-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318) ~[netty-codec-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[netty-codec-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[netty-handler-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:152) ~[netty-handler-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800) ~[netty-transport-classes-epoll-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:509) ~[netty-transport-classes-epoll-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:407) ~[netty-transport-classes-epoll-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]

### How to replicate it if known

Build Grim from Source

Put on Server

### Grim version

2.3.62

### Server version

purpur 1.20.4 and paper 1.20.1

### Plugins

Purpur server
- AntiPopup, DiscordSRV, floodgate, FreedomChat, Geyser-Spigot, GrimAC, ImageFrame, ProtocolLib, spark, ViaBackwards, ViaVersion

Paper Server 
[21:00:16 INFO]: Paper Plugins:
[21:00:16 INFO]:  - BKCommonLib
[21:00:16 INFO]: Bukkit Plugins:
[21:00:16 INFO]:  - AnnouncerPlus, Amethystials, ChestCommands, *ColorCodes, ColoredSigns, ConditionalEvents, CoreProtect, CreativeItemControl, Duels, dynmap
[21:00:16 INFO]:  eGlow, Essentials, EssentialsChat, EssentialsDiscord, EssentialsSelectors, EssentialsSpawn, *FarmProtect, floodgate, FreedomChat, Geyser-Spigot
[21:00:16 INFO]:  GPFlags, *Green, GriefPrevention, GrimAC, HungerGames, KeepChunks, LastLoginAPI, LuckPerms, MessageAnnouncer, My_Worlds
[21:00:16 INFO]:  NoChatReports, PlaceholderAPI, PlayerHeads, PlayerKits2, ProtocolLib, ServerListPlus, spark, TAB, Vault, ViaBackwards
[21:00:16 INFO]:  ViaVersion, Vivecraft-Spigot-Extensions, voicechat, WorldEdit, WorldGuard

**Comment by SamB440** [comment]
You're compiling against alpha PacketEvents versions for 1.20.5, invalid issue, this was fixed by PE as well

**Comment by AoElite** [comment]
Packetevents is still being updated to 1.20.5
