### ISSUE TITLE
TeleportAsync on Folia

### ISSUE THREAD

**Issue by RitaSister** [GrimAnticheat/Grim#1540]
### Stack trace

[09:45:53 INFO]: RitaSister issued server command: /grim spectate AltShinki
[09:45:53 ERROR]: [GrimAC] [ACF] Exception in command: grim spectate AltShinki
[09:45:53 ERROR]: [GrimAC] [ACF] java.lang.UnsupportedOperationException: Must use teleportAsync while in region threading
[09:45:53 ERROR]: [GrimAC] [ACF]        at org.bukkit.craftbukkit.entity.CraftPlayer.teleport(CraftPlayer.java:1399)
[09:45:53 ERROR]: [GrimAC] [ACF]        at org.bukkit.craftbukkit.entity.CraftPlayer.teleport(CraftPlayer.java:1348)
[09:45:53 ERROR]: [GrimAC] [ACF]        at org.bukkit.craftbukkit.entity.CraftEntity.teleport(CraftEntity.java:226)
[09:45:53 ERROR]: [GrimAC] [ACF]        at org.bukkit.craftbukkit.entity.CraftEntity.teleport(CraftEntity.java:296)
[09:45:53 ERROR]: [GrimAC] [ACF]        at grimac-2.3.65.jar//ac.grim.grimac.commands.GrimSpectate.onSpectate(GrimSpectate.java:55)
[09:45:53 ERROR]: [GrimAC] [ACF]        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[09:45:53 ERROR]: [GrimAC] [ACF]        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
[09:45:53 ERROR]: [GrimAC] [ACF]        at grimac-2.3.65.jar//ac.grim.grimac.shaded.acf.RegisteredCommand.invoke(RegisteredCommand.java:152)
[09:45:53 ERROR]: [GrimAC] [ACF]        at grimac-2.3.65.jar//ac.grim.grimac.shaded.acf.BaseCommand.executeCommand(BaseCommand.java:578)
[09:45:53 ERROR]: [GrimAC] [ACF]        at grimac-2.3.65.jar//ac.grim.grimac.shaded.acf.BaseCommand.execute(BaseCommand.java:513)
[09:45:53 ERROR]: [GrimAC] [ACF]        at grimac-2.3.65.jar//ac.grim.grimac.shaded.acf.RootCommand.execute(RootCommand.java:99)
[09:45:53 ERROR]: [GrimAC] [ACF]        at grimac-2.3.65.jar//ac.grim.grimac.shaded.acf.BukkitRootCommand.execute(BukkitRootCommand.java:84)
[09:45:53 ERROR]: [GrimAC] [ACF]        at io.papermc.paper.command.brigadier.bukkit.BukkitCommandNode$BukkitBrigCommand.run(BukkitCommandNode.java:86)
[09:45:53 ERROR]: [GrimAC] [ACF]        at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73)
[09:45:53 ERROR]: [GrimAC] [ACF]        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:31)
[09:45:53 ERROR]: [GrimAC] [ACF]        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:19)
[09:45:53 ERROR]: [GrimAC] [ACF]        at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8)
[09:45:53 ERROR]: [GrimAC] [ACF]        at net.minecraft.commands.execution.CommandQueueEntry.execute(CommandQueueEntry.java:5)
[09:45:53 ERROR]: [GrimAC] [ACF]        at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:103)
[09:45:53 ERROR]: [GrimAC] [ACF]        at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:442)
[09:45:53 ERROR]: [GrimAC] [ACF]        at net.minecraft.commands.Commands.performCommand(Commands.java:349)
[09:45:53 ERROR]: [GrimAC] [ACF]        at net.minecraft.commands.Commands.performCommand(Commands.java:336)
[09:45:53 ERROR]: [GrimAC] [ACF]        at net.minecraft.commands.Commands.performCommand(Commands.java:331)
[09:45:53 ERROR]: [GrimAC] [ACF]        at net.minecraft.server.network.ServerGamePacketListenerImpl.performUnsignedChatCommand(ServerGamePacketListenerImpl.java:2254)
[09:45:53 ERROR]: [GrimAC] [ACF]        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$14(ServerGamePacketListenerImpl.java:2228)
[09:45:53 ERROR]: [GrimAC] [ACF]        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$tryHandleChat$17(ServerGamePacketListenerImpl.java:2392)
[09:45:53 ERROR]: [GrimAC] [ACF]        at io.papermc.paper.threadedregions.EntityScheduler.executeTick(EntityScheduler.java:173)
[09:45:53 ERROR]: [GrimAC] [ACF]        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1691)
[09:45:53 ERROR]: [GrimAC] [ACF]        at io.papermc.paper.threadedregions.TickRegions$ConcreteRegionTickHandle.tickRegion(TickRegions.java:407)
[09:45:53 ERROR]: [GrimAC] [ACF]        at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:404)
[09:45:53 ERROR]: [GrimAC] [ACF]        at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525)
[09:45:53 ERROR]: [GrimAC] [ACF]        at java.base/java.lang.Thread.run(Thread.java:1583)

### How to replicate it if known

just run command /spec <player>

### Grim version

grimac-2.3.65

### Server version

This server is running Folia version 1.20.6-DEV-master@36e5e83 (2024-05-31T05:54:47Z) (Implementing API version 1.20.6-R0.1-SNAPSHOT)
You are running the latest version
Previous version: 1.20.6-DEV-78f49e0 (MC: 1.20.6)

### Plugins

[09:45:39 INFO]: Paper Plugins:
[09:45:39 INFO]:  - CarbonChat, FancyNpcs, FoliaWorldLoader
[09:45:39 INFO]: Bukkit Plugins:
[09:45:39 INFO]:  - AElytra, AquaLimeAdmin, ArmorStandEditor, BreweryX, Chunky, CoreProtect, CoreProtectTNT, Craftorithm, Essentials, EssentialsSpawn
[09:45:39 INFO]:  GrimAC, GSit, HeadDatabase, InventoryRollbackPlus, InvisibleFrames, InvSeePlusPlus, JoinMessenger, LiteBans, LuckPerms, Maintenance
[09:45:39 INFO]:  Mclogs, MilkyPixelart, NBTAPI, NewbieFilter, OreAnnouncer, PlaceholderAPI, PlasmoVoice, PlayerHeads, ProtocolLib, pv-addon-discs
[09:45:39 INFO]:  pv-addon-groups, pv-addon-lavaplayer-lib, pv-addon-sculk, pv-addon-spectator, spark, squaremap, squaremarker, TAB, UltimateAutoRestart, UralChat
[09:45:39 INFO]:  Vault, ViaBackwards, ViaVersion, *WillCheck, WorldEdit, WorldGuard

**Comment by J4n-T** [comment]
Check https://github.com/GrimAnticheat/Grim/issues/1572

**Comment by Axionize** [comment]
This has long been fixed, please re-open if you somehow still experience similar issues.
