### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Yomamaeatstoes** [GrimAnticheat/Grim#1566]
### Stack trace

[23.06 06:21:24] [Server] [INFO] [GrimAC] [STDOUT] An error has occurred when running transactions for player: leyethym
[23.06 06:21:24] [Server] [WARN] Nag author(s): '[GrimAC]' of 'GrimAC v2.3.65' about their usage of System.out/err.print. Please use your plugin's logger instead (JavaPlugin#getLogger).
[23.06 06:21:24] [Server] [WARN] java.lang.NullPointerException: Cannot invoke "ac.grim.grimac.shaded.com.github.retrooper.packetevents.protocol.nbt.NBTCompound.getBoolean(String)" because the return value of "ac.grim.grimac.shaded.com.github.retrooper.packetevents.protocol.item.ItemStack.getNBT()" is null
[23.06 06:21:24] [Server] [WARN] 	at grimac-2.3.65.jar//ac.grim.grimac.events.packets.PacketPlayerDigging.handleUseItem(PacketPlayerDigging.java:82)
[23.06 06:21:24] [Server] [WARN] 	at grimac-2.3.65.jar//ac.grim.grimac.events.packets.PacketSelfMetadataListener.lambda$onPacketSend$7(PacketSelfMetadataListener.java:205)
[23.06 06:21:24] [Server] [WARN] 	at grimac-2.3.65.jar//ac.grim.grimac.utils.latency.LatencyUtils.handleNettySyncTransaction(LatencyUtils.java:56)
[23.06 06:21:24] [Server] [WARN] 	at grimac-2.3.65.jar//ac.grim.grimac.player.GrimPlayer.addTransactionResponse(GrimPlayer.java:328)
[23.06 06:21:24] [Server] [WARN] 	at grimac-2.3.65.jar//ac.grim.grimac.events.packets.PacketPingListener.onPacketReceive(PacketPingListener.java:62)
[23.06 06:21:24] [Server] [WARN] 	at grimac-2.3.65.jar//ac.grim.grimac.shaded.com.github.retrooper.packetevents.event.PacketReceiveEvent.call(PacketReceiveEvent.java:45)
[23.06 06:21:24] [Server] [WARN] 	at grimac-2.3.65.jar//ac.grim.grimac.shaded.com.github.retrooper.packetevents.event.EventManager.callEvent(EventManager.java:52)
[23.06 06:21:24] [Server] [WARN] 	at grimac-2.3.65.jar//ac.grim.grimac.shaded.com.github.retrooper.packetevents.util.PacketEventsImplHelper.handleServerBoundPacket(PacketEventsImplHelper.java:82)
[23.06 06:21:24] [Server] [WARN] 	at grimac-2.3.65.jar//ac.grim.grimac.shaded.io.github.retrooper.packetevents.injector.handlers.PacketEventsDecoder.read(PacketEventsDecoder.java:56)
[23.06 06:21:24] [Server] [WARN] 	at grimac-2.3.65.jar//ac.grim.grimac.shaded.io.github.retrooper.packetevents.injector.handlers.PacketEventsDecoder.decode(PacketEventsDecoder.java:63)
[23.06 06:21:24] [Server] [WARN] 	at grimac-2.3.65.jar//ac.grim.grimac.shaded.io.github.retrooper.packetevents.injector.handlers.PacketEventsDecoder.decode(PacketEventsDecoder.java:40)
[23.06 06:21:24] [Server] [WARN] 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88)
[23.06 06:21:24] [Server] [WARN] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[23.06 06:21:24] [Server] [WARN] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[23.06 06:21:24] [Server] [WARN] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[23.06 06:21:24] [Server] [WARN] 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
[23.06 06:21:24] [Server] [WARN] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[23.06 06:21:24] [Server] [WARN] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[23.06 06:21:24] [Server] [WARN] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[23.06 06:21:24] [Server] [WARN] 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
[23.06 06:21:24] [Server] [WARN] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[23.06 06:21:24] [Server] [WARN] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[23.06 06:21:24] [Server] [WARN] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[23.06 06:21:24] [Server] [WARN] 	at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.InboundProtocolReader.channelRead(InboundProtocolReader.java:25)
[23.06 06:21:24] [Server] [WARN] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[23.06 06:21:24] [Server] [WARN] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[23.06 06:21:24] [Server] [WARN] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[23.06 06:21:24] [Server] [WARN] 	at io.netty.handler.flow.FlowControlHandler.dequeue(FlowControlHandler.java:202)
[23.06 06:21:24] [Server] [WARN] 	at io.netty.handler.flow.FlowControlHandler.channelRead(FlowControlHandler.java:164)
[23.06 06:21:24] [Server] [WARN] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
[23.06 06:21:24] [Server] [WARN] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[23.06 06:21:24] [Server] [WARN] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[23.06 06:21:24] [Server] [WARN] 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
[23.06 06:21:24] [Server] [WARN] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[23.06 06:21:26] [Multicraft] Skipped 32 lines due to rate limit (100/s)
[23.06 06:21:26] [Server] [INFO] [GrimAC] [STDOUT] An error has occurred when running transactions for player: leyethym
[23.06 06:21:26] [Server] [WARN] java.lang.NullPointerException: Cannot invoke "ac.grim.grimac.shaded.com.github.retrooper.packetevents.protocol.nbt.NBTCompound.getBoolean(String)" because the return value of "ac.grim.grimac.shaded.com.github.retrooper.packetevents.protocol.item.ItemStack.getNBT()" is null
[23.06 06:21:26] [Server] [WARN] 	at grimac-2.3.65.jar//ac.grim.grimac.events.packets.PacketPlayerDigging.handleUseItem(PacketPlayerDigging.java:82)
[23.06 06:21:26] [Server] [WARN] 	at grimac-2.3.65.jar//ac.grim.grimac.events.packets.PacketSelfMetadataListener.lambda$onPacketSend$7(PacketSelfMetadataListener.java:205)
[23.06 06:21:26] [Server] [WARN] 	at grimac-2.3.65.jar//ac.grim.grimac.utils.latency.LatencyUtils.handleNettySyncTransaction(LatencyUtils.java:56)
[23.06 06:21:26] [Server] [WARN] 	at grimac-2.3.65.jar//ac.grim.grimac.player.GrimPlayer.addTransactionResponse(GrimPlayer.java:328)
[23.06 06:21:26] [Server] [WARN] 	at grimac-2.3.65.jar//ac.grim.grimac.events.packets.PacketPingListener.onPacketReceive(PacketPingListener.java:62)
[23.06 06:21:26] [Server] [WARN] 	at grimac-2.3.65.jar//ac.grim.grimac.shaded.com.github.retrooper.packetevents.event.PacketReceiveEvent.call(PacketReceiveEvent.java:45)
[23.06 06:21:26] [Server] [WARN] 	at grimac-2.3.65.jar//ac.grim.grimac.shaded.com.github.retrooper.packetevents.event.EventManager.callEvent(EventManager.java:52)
[23.06 06:21:26] [Server] [WARN] 	at grimac-2.3.65.jar//ac.grim.grimac.shaded.com.github.retrooper.packetevents.util.PacketEventsImplHelper.handleServerBoundPacket(PacketEventsImplHelper.java:82)
[23.06 06:21:26] [Server] [WARN] 	at grimac-2.3.65.jar//ac.grim.grimac.shaded.io.github.retrooper.packetevents.injector.handlers.PacketEventsDecoder.read(PacketEventsDecoder.java:56)
[23.06 06:21:26] [Server] [WARN] 	at grimac-2.3.65.jar//ac.grim.grimac.shaded.io.github.retrooper.packetevents.injector.handlers.PacketEventsDecoder.decode(PacketEventsDecoder.java:63)
[23.06 06:21:26] [Server] [WARN] 	at grimac-2.3.65.jar//ac.grim.grimac.shaded.io.github.retrooper.packetevents.injector.handlers.PacketEventsDecoder.decode(PacketEventsDecoder.java:40)
[23.06 06:21:26] [Server] [WARN] 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88)
[23.06 06:21:26] [Server] [WARN] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[23.06 06:21:26] [Server] [WARN] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[23.06 06:21:26] [Server] [WARN] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[23.06 06:21:26] [Server] [WARN] 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
[23.06 06:21:26] [Server] [WARN] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[23.06 06:21:26] [Server] [WARN] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[23.06 06:21:26] [Server] [WARN] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[23.06 06:21:26] [Server] [WARN] 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
[23.06 06:21:26] [Server] [WARN] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[23.06 06:21:26] [Server] [WARN] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[23.06 06:21:26] [Server] [WARN] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[23.06 06:21:26] [Server] [WARN] 	at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.InboundProtocolReader.channelRead(InboundProtocolReader.java:25)
[23.06 06:21:26] [Server] [WARN] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[23.06 06:21:26] [Server] [WARN] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[23.06 06:21:26] [Server] [WARN] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[23.06 06:21:26] [Server] [WARN] 	at io.netty.handler.flow.FlowControlHandler.dequeue(FlowControlHandler.java:202)
[23.06 06:21:26] [Server] [WARN] 	at io.netty.handler.flow.FlowControlHandler.channelRead(FlowControlHandler.java:164)
[23.06 06:21:26] [Server] [WARN] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
[23.06 06:21:26] [Server] [WARN] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[23.06 06:21:26] [Server] [WARN] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[23.06 06:21:26] [Server] [WARN] 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
[23.06 06:21:26] [Server] [WARN] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[23.06 06:21:26] [Server] [WARN] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[23.06 06:21:26] [Server] [WARN] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[23.06 06:21:26] [Server] [WARN] 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
[23.06 06:21:26] [Server] [WARN] 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
[23.06 06:21:26] [Server] [WARN] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[23.06 06:21:26] [Server] [WARN] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[23.06 06:21:26] [Server] [WARN] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[23.06 06:21:26] [Server] [WARN] 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
[23.06 06:21:26] [Server] [WARN] 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
[23.06 06:21:26] [Server] [WARN] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[23.06 06:21:26] [Server] [WARN] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[23.06 06:21:26] [Server] [WARN] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[23.06 06:21:26] [Server] [WARN] 	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
[23.06 06:21:26] [Server] [WARN] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
[23.06 06:21:26] [Server] [WARN] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[23.06 06:21:26] [Server] [WARN] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[23.06 06:21:26] [Server] [WARN] 	at io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:152)
[23.06 06:21:26] [Server] [WARN] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
[23.06 06:21:26] [Server] [WARN] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[23.06 06:21:26] [Server] [WARN] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[23.06 06:21:26] [Server] [WARN] 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
[23.06 06:21:26] [Server] [WARN] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
[23.06 06:21:26] [Server] [WARN] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[23.06 06:21:26] [Server] [WARN] 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
[23.06 06:21:26] [Server] [WARN] 	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
[23.06 06:21:26] [Server] [WARN] 	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:509)
[23.06 06:21:26] [Server] [WARN] 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:407)
[23.06 06:21:26] [Server] [WARN] 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[23.06 06:21:26] [Server] [WARN] 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[23.06 06:21:26] [Server] [WARN] 	at java.base/java.lang.Thread.run(Thread.java:1583)

### How to replicate it if known

Unkown

### Grim version

grimac-2.3.65

### Server version

This server is running Folia version 1.20.6-DEV-master@d797082 (2024-06-20T18:54:57Z) (Implementing API version 1.20.6-R0.1-SNAPSHOT)
You are running the latest version
Previous version: 1.20.6-DEV-36e5e83 (MC: 1.20.6)

### Plugins

AntiPopup, AutoPay, BetterBoard, BetterEconomy, BetterRTP, BetterRTPAddons, BisectHosting-Folia, BloCommands, ChatFilter, Chunky,ClansLite, CommandWhitelist, DeluxeMenus, DisableBreeding, DiscordSRV, ElytraSpeed, EpicHomes,  floodgate, GlobalTrackedMaps, GrimAC, GrimCheckup, HeadDrop, IllegalStack, ImageFrame, KeepInv, LuckPerms, mcMMO, ModularMob, MutePlus, NoExtraDamageTicks, PlaceholderAPI, PlayerBountiesPlus, PlayerKits2, PlugManX, ProtocolLib, RegularRank, ScoreboardChatShop, SilkySpawnersLITE, spark, stackMob, StormerAntiSpamReloaded, StormerWarpsReloaded, TAB, TerragenBiomesMockRegistry, VanillaBosses, Vault, ViaBackwards, ViaRewind, ViaVersion, Votifier, VotingPlugin, WorldEdit, WorldGuard, YATPA, ZNPCsPlus

**Comment by SamB440** [comment]
Update to the latest commit.
