### ISSUE TITLE
Error spam

### ISSUE THREAD

**Issue by Dg32z** [GrimAnticheat/Grim#1635]
### Stack trace
[QQ截图20240812130033](https://github.com/user-attachments/assets/d94d3ceb-8f90-4ef0-a442-03244f7c05e7)

[latest.log](https://github.com/user-attachments/files/16577548/latest.log)

### How to replicate it if known

it happen when player join

### Grim version

https://github.com/GrimAnticheat/Grim/actions/runs/10339944240

### Server version

paper-1.8.8-445

### Plugins

[12:55:20 INFO]: Plugins (3): LuckPerms, PlugManX, GrimAC

**Comment by SamB440** [comment]
1.8 packetevents issue, downgrade to https://github.com/GrimAnticheat/Grim/commit/1af04244d79f4043f9a1f8b68c87d9381018fb88

**Comment by MahadRegent** [comment]
too have this error on 1.16.5

**Comment by PSYCHEER** [comment]
1.21
```
[18:28:37 WARN]: [GrimAC] Plugin GrimAC v2.3.65 generated an exception while executing task 292
java.lang.ArrayIndexOutOfBoundsException: Index 53 out of bounds for length 3
at grimac-2.3.65.jar/ac.grim.grimac.shaded.com.github.retrooper.packetevents.wrapper.PacketWrapper.readEnum(PacketWrapper.java:1407) ~[grimac-2.3.65.jar:?]
at grimac-2.3.65.jar/ac.grim.grimac.shaded.com.github.retrooper.packetevents.protocol.component.builtin.item.ItemAttributeModifiers$Modifier.read(ItemAttributeModifiers.java:187) ~[grimac-2.3.65.jar:?]
at grimac-2.3.65.jar/ac.grim.grimac.shaded.com.github.retrooper.packetevents.protocol.component.builtin.item.ItemAttributeModifiers$ModifierEntry.read(ItemAttributeModifiers.java:113) ~[grimac-2.3.65.jar:?]
at grimac-2.3.65.jar/ac.grim.grimac.shaded.com.github.retrooper.packetevents.wrapper.PacketWrapper.readCollection(PacketWrapper.java:1379) ~[grimac-2.3.65.jar:?]
at grimac-2.3.65.jar/ac.grim.grimac.shaded.com.github.retrooper.packetevents.wrapper.PacketWrapper.readList(PacketWrapper.java:1392) ~[grimac-2.3.65.jar:?]
at grimac-2.3.65.jar/ac.grim.grimac.shaded.com.github.retrooper.packetevents.protocol.component.builtin.item.ItemAttributeModifiers.read(ItemAttributeModifiers.java:50) ~[grimac-2.3.65.jar:?]
at grimac-2.3.65.jar/ac.grim.grimac.shaded.com.github.retrooper.packetevents.protocol.component.ComponentTypes$1.read(ComponentTypes.java:88) ~[grimac-2.3.65.jar:?]
at grimac-2.3.65.jar/ac.grim.grimac.shaded.com.github.retrooper.packetevents.wrapper.PacketWrapper.readItemStackModern(PacketWrapper.java:430) ~[grimac-2.3.65.jar:?]
at grimac-2.3.65.jar/ac.grim.grimac.shaded.com.github.retrooper.packetevents.wrapper.PacketWrapper.readItemStack(PacketWrapper.java:449) ~[grimac-2.3.65.jar:?]
at grimac-2.3.65.jar/ac.grim.grimac.shaded.io.github.retrooper.packetevents.util.SpigotReflectionUtil.decodeBukkitItemStack(SpigotReflectionUtil.java:808) ~[grimac-2.3.65.jar:?]
at grimac-2.3.65.jar/ac.grim.grimac.shaded.io.github.retrooper.packetevents.util.SpigotConversionUtil.fromBukkitItemStack(SpigotConversionUtil.java:135) ~[grimac-2.3.65.jar:?]
at grimac-2.3.65.jar/ac.grim.grimac.utils.lists.CorrectingPlayerInventoryStorage.checkThatBukkitIsSynced(CorrectingPlayerInventoryStorage.java:104) ~[grimac-2.3.65.jar:?]
at grimac-2.3.65.jar/ac.grim.grimac.utils.lists.CorrectingPlayerInventoryStorage.tickWithBukkit(CorrectingPlayerInventoryStorage.java:148) ~[grimac-2.3.65.jar:?]
at grimac-2.3.65.jar/ac.grim.grimac.manager.tick.impl.TickInventory.tick(TickInventory.java:11) ~[grimac-2.3.65.jar:?]
at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422) ~[guava-32.1.2-jre.jar:?]
at grimac-2.3.65.jar/ac.grim.grimac.manager.TickManager.tickAsync(TickManager.java:34) ~[grimac-2.3.65.jar:?]
at grimac-2.3.65.jar/ac.grim.grimac.manager.init.start.TickRunner.lambda$start$2(TickRunner.java:21) ~[grimac-2.3.65.jar:?]
at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86) ~[purpur-1.21.jar:1.21-2284-4e55e26]
at org.bukkit.craftbukkit.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.21.jar:1.21-2284-4e55e26]
at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.21.jar:?]
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```
[latest](https://mclo.gs/vA7GvAG)

**Comment by SamB440** [comment]
Redownload the latest commit.

**Comment by SamB440** [comment]
> 1.21
> 
> ```
> [18:28:37 WARN]: [GrimAC] Plugin GrimAC v2.3.65 generated an exception while executing task 292
> java.lang.ArrayIndexOutOfBoundsException: Index 53 out of bounds for length 3
> at grimac-2.3.65.jar/ac.grim.grimac.shaded.com.github.retrooper.packetevents.wrapper.PacketWrapper.readEnum(PacketWrapper.java:1407) ~[grimac-2.3.65.jar:?]
> at grimac-2.3.65.jar/ac.grim.grimac.shaded.com.github.retrooper.packetevents.protocol.component.builtin.item.ItemAttributeModifiers$Modifier.read(ItemAttributeModifiers.java:187) ~[grimac-2.3.65.jar:?]
> at grimac-2.3.65.jar/ac.grim.grimac.shaded.com.github.retrooper.packetevents.protocol.component.builtin.item.ItemAttributeModifiers$ModifierEntry.read(ItemAttributeModifiers.java:113) ~[grimac-2.3.65.jar:?]
> at grimac-2.3.65.jar/ac.grim.grimac.shaded.com.github.retrooper.packetevents.wrapper.PacketWrapper.readCollection(PacketWrapper.java:1379) ~[grimac-2.3.65.jar:?]
> at grimac-2.3.65.jar/ac.grim.grimac.shaded.com.github.retrooper.packetevents.wrapper.PacketWrapper.readList(PacketWrapper.java:1392) ~[grimac-2.3.65.jar:?]
> at grimac-2.3.65.jar/ac.grim.grimac.shaded.com.github.retrooper.packetevents.protocol.component.builtin.item.ItemAttributeModifiers.read(ItemAttributeModifiers.java:50) ~[grimac-2.3.65.jar:?]
> at grimac-2.3.65.jar/ac.grim.grimac.shaded.com.github.retrooper.packetevents.protocol.component.ComponentTypes$1.read(ComponentTypes.java:88) ~[grimac-2.3.65.jar:?]
> at grimac-2.3.65.jar/ac.grim.grimac.shaded.com.github.retrooper.packetevents.wrapper.PacketWrapper.readItemStackModern(PacketWrapper.java:430) ~[grimac-2.3.65.jar:?]
> at grimac-2.3.65.jar/ac.grim.grimac.shaded.com.github.retrooper.packetevents.wrapper.PacketWrapper.readItemStack(PacketWrapper.java:449) ~[grimac-2.3.65.jar:?]
> at grimac-2.3.65.jar/ac.grim.grimac.shaded.io.github.retrooper.packetevents.util.SpigotReflectionUtil.decodeBukkitItemStack(SpigotReflectionUtil.java:808) ~[grimac-2.3.65.jar:?]
> at grimac-2.3.65.jar/ac.grim.grimac.shaded.io.github.retrooper.packetevents.util.SpigotConversionUtil.fromBukkitItemStack(SpigotConversionUtil.java:135) ~[grimac-2.3.65.jar:?]
> at grimac-2.3.65.jar/ac.grim.grimac.utils.lists.CorrectingPlayerInventoryStorage.checkThatBukkitIsSynced(CorrectingPlayerInventoryStorage.java:104) ~[grimac-2.3.65.jar:?]
> at grimac-2.3.65.jar/ac.grim.grimac.utils.lists.CorrectingPlayerInventoryStorage.tickWithBukkit(CorrectingPlayerInventoryStorage.java:148) ~[grimac-2.3.65.jar:?]
> at grimac-2.3.65.jar/ac.grim.grimac.manager.tick.impl.TickInventory.tick(TickInventory.java:11) ~[grimac-2.3.65.jar:?]
> at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422) ~[guava-32.1.2-jre.jar:?]
> at grimac-2.3.65.jar/ac.grim.grimac.manager.TickManager.tickAsync(TickManager.java:34) ~[grimac-2.3.65.jar:?]
> at grimac-2.3.65.jar/ac.grim.grimac.manager.init.start.TickRunner.lambda$start$2(TickRunner.java:21) ~[grimac-2.3.65.jar:?]
> at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86) ~[purpur-1.21.jar:1.21-2284-4e55e26]
> at org.bukkit.craftbukkit.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.21.jar:1.21-2284-4e55e26]
> at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.21.jar:?]
> at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
> at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
> at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
> ```
> 
> [latest](https://mclo.gs/vA7GvAG)

That is an unrelated error and you are also not running the latest Grim.

**Comment by PSYCHEER** [comment]
> > 1.21
> > ```
> > [18:28:37 WARN]: [GrimAC] Plugin GrimAC v2.3.65 generated an exception while executing task 292
> > java.lang.ArrayIndexOutOfBoundsException: Index 53 out of bounds for length 3
> > at grimac-2.3.65.jar/ac.grim.grimac.shaded.com.github.retrooper.packetevents.wrapper.PacketWrapper.readEnum(PacketWrapper.java:1407) ~[grimac-2.3.65.jar:?]
> > at grimac-2.3.65.jar/ac.grim.grimac.shaded.com.github.retrooper.packetevents.protocol.component.builtin.item.ItemAttributeModifiers$Modifier.read(ItemAttributeModifiers.java:187) ~[grimac-2.3.65.jar:?]
> > at grimac-2.3.65.jar/ac.grim.grimac.shaded.com.github.retrooper.packetevents.protocol.component.builtin.item.ItemAttributeModifiers$ModifierEntry.read(ItemAttributeModifiers.java:113) ~[grimac-2.3.65.jar:?]
> > at grimac-2.3.65.jar/ac.grim.grimac.shaded.com.github.retrooper.packetevents.wrapper.PacketWrapper.readCollection(PacketWrapper.java:1379) ~[grimac-2.3.65.jar:?]
> > at grimac-2.3.65.jar/ac.grim.grimac.shaded.com.github.retrooper.packetevents.wrapper.PacketWrapper.readList(PacketWrapper.java:1392) ~[grimac-2.3.65.jar:?]
> > at grimac-2.3.65.jar/ac.grim.grimac.shaded.com.github.retrooper.packetevents.protocol.component.builtin.item.ItemAttributeModifiers.read(ItemAttributeModifiers.java:50) ~[grimac-2.3.65.jar:?]
> > at grimac-2.3.65.jar/ac.grim.grimac.shaded.com.github.retrooper.packetevents.protocol.component.ComponentTypes$1.read(ComponentTypes.java:88) ~[grimac-2.3.65.jar:?]
> > at grimac-2.3.65.jar/ac.grim.grimac.shaded.com.github.retrooper.packetevents.wrapper.PacketWrapper.readItemStackModern(PacketWrapper.java:430) ~[grimac-2.3.65.jar:?]
> > at grimac-2.3.65.jar/ac.grim.grimac.shaded.com.github.retrooper.packetevents.wrapper.PacketWrapper.readItemStack(PacketWrapper.java:449) ~[grimac-2.3.65.jar:?]
> > at grimac-2.3.65.jar/ac.grim.grimac.shaded.io.github.retrooper.packetevents.util.SpigotReflectionUtil.decodeBukkitItemStack(SpigotReflectionUtil.java:808) ~[grimac-2.3.65.jar:?]
> > at grimac-2.3.65.jar/ac.grim.grimac.shaded.io.github.retrooper.packetevents.util.SpigotConversionUtil.fromBukkitItemStack(SpigotConversionUtil.java:135) ~[grimac-2.3.65.jar:?]
> > at grimac-2.3.65.jar/ac.grim.grimac.utils.lists.CorrectingPlayerInventoryStorage.checkThatBukkitIsSynced(CorrectingPlayerInventoryStorage.java:104) ~[grimac-2.3.65.jar:?]
> > at grimac-2.3.65.jar/ac.grim.grimac.utils.lists.CorrectingPlayerInventoryStorage.tickWithBukkit(CorrectingPlayerInventoryStorage.java:148) ~[grimac-2.3.65.jar:?]
> > at grimac-2.3.65.jar/ac.grim.grimac.manager.tick.impl.TickInventory.tick(TickInventory.java:11) ~[grimac-2.3.65.jar:?]
> > at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422) ~[guava-32.1.2-jre.jar:?]
> > at grimac-2.3.65.jar/ac.grim.grimac.manager.TickManager.tickAsync(TickManager.java:34) ~[grimac-2.3.65.jar:?]
> > at grimac-2.3.65.jar/ac.grim.grimac.manager.init.start.TickRunner.lambda$start$2(TickRunner.java:21) ~[grimac-2.3.65.jar:?]
> > at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86) ~[purpur-1.21.jar:1.21-2284-4e55e26]
> > at org.bukkit.craftbukkit.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.21.jar:1.21-2284-4e55e26]
> > at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.21.jar:?]
> > at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
> > at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
> > at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > [latest](https://mclo.gs/vA7GvAG)
> 
> That is an unrelated error and you are also not running the latest Grim.

![image](https://github.com/user-attachments/assets/762f071b-5a7a-4a07-a7ef-debe482205ec)
and I cant find any other source where to download "newer" version as this is latest you've uploaded on spigot

EDIT: I saw issue SPAM ERROR and this error is really spamming console so... I've posted it in here then
