### ISSUE TITLE
Warn Spam

### ISSUE THREAD

**Issue by MathsAnalysis** [GrimAnticheat/Grim#1636]
### Describe the bug and how to replicate it

 ```
Netty Server IO #2/WARN]: PacketEvents caught an unhandled exception while calling your listener.
java.lang.NullPointerException
	at ac.grim.grimac.predictionengine.PlayerBaseTick.updateInWaterStateAndDoFluidPushing(PlayerBaseTick.java:136) ~[grimac-2.3.66.jar:?]
	at ac.grim.grimac.predictionengine.PlayerBaseTick.doBaseTick(PlayerBaseTick.java:51) ~[grimac-2.3.66.jar:?]
	at ac.grim.grimac.predictionengine.MovementCheckRunner.check(MovementCheckRunner.java:485) ~[grimac-2.3.66.jar:?]
	at ac.grim.grimac.predictionengine.MovementCheckRunner.processAndCheckMovementPacket(MovementCheckRunner.java:72) ~[grimac-2.3.66.jar:?]
	at ac.grim.grimac.checks.impl.movement.PredictionRunner.onPositionUpdate(PredictionRunner.java:16) ~[grimac-2.3.66.jar:?]
	at ac.grim.grimac.manager.CheckManager.onPositionUpdate(CheckManager.java:221) ~[grimac-2.3.66.jar:?]
	at ac.grim.grimac.events.packets.CheckManagerListener.handleFlying(CheckManagerListener.java:739) ~[grimac-2.3.66.jar:?]
	at ac.grim.grimac.events.packets.CheckManagerListener.onPacketReceive(CheckManagerListener.java:431) ~[grimac-2.3.66.jar:?]
	at ac.grim.grimac.shaded.com.github.retrooper.packetevents.event.PacketReceiveEvent.call(PacketReceiveEvent.java:44) ~[grimac-2.3.66.jar:?]
	at ac.grim.grimac.shaded.com.github.retrooper.packetevents.event.EventManager.callEvent(EventManager.java:84) [grimac-2.3.66.jar:?]
	at ac.grim.grimac.shaded.com.github.retrooper.packetevents.util.PacketEventsImplHelper.handleServerBoundPacket(PacketEventsImplHelper.java:84) [grimac-2.3.66.jar:?]
	at ac.grim.grimac.shaded.io.github.retrooper.packetevents.injector.handlers.PacketEventsDecoder.read(PacketEventsDecoder.java:57) [grimac-2.3.66.jar:?]
	at ac.grim.grimac.shaded.io.github.retrooper.packetevents.injector.handlers.PacketEventsDecoder.decode(PacketEventsDecoder.java:64) [grimac-2.3.66.jar:?]
	at ac.grim.grimac.shaded.io.github.retrooper.packetevents.injector.handlers.PacketEventsDecoder.decode(PacketEventsDecoder.java:41) [grimac-2.3.66.jar:?]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:89) [paper-1.8.8-445.jar.jar:git-PaperSpigot-f6fba00-9935adc]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [paper-1.8.8-445.jar.jar:git-PaperSpigot-f6fba00-9935adc]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [paper-1.8.8-445.jar.jar:git-PaperSpigot-f6fba00-9935adc]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163) [paper-1.8.8-445.jar.jar:git-PaperSpigot-f6fba00-9935adc]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [paper-1.8.8-445.jar.jar:git-PaperSpigot-f6fba00-9935adc]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [paper-1.8.8-445.jar.jar:git-PaperSpigot-f6fba00-9935adc]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163) [paper-1.8.8-445.jar.jar:git-PaperSpigot-f6fba00-9935adc]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [paper-1.8.8-445.jar.jar:git-PaperSpigot-f6fba00-9935adc]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [paper-1.8.8-445.jar.jar:git-PaperSpigot-f6fba00-9935adc]
	at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:150) [paper-1.8.8-445.jar.jar:git-PaperSpigot-f6fba00-9935adc]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [paper-1.8.8-445.jar.jar:git-PaperSpigot-f6fba00-9935adc]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [paper-1.8.8-445.jar.jar:git-PaperSpigot-f6fba00-9935adc]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787) [paper-1.8.8-445.jar.jar:git-PaperSpigot-f6fba00-9935adc]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:130) [paper-1.8.8-445.jar.jar:git-PaperSpigot-f6fba00-9935adc]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511) [paper-1.8.8-445.jar.jar:git-PaperSpigot-f6fba00-9935adc]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468) [paper-1.8.8-445.jar.jar:git-PaperSpigot-f6fba00-9935adc]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382) [paper-1.8.8-445.jar.jar:git-PaperSpigot-f6fba00-9935adc]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354) [paper-1.8.8-445.jar.jar:git-PaperSpigot-f6fba00-9935adc]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [paper-1.8.8-445.jar.jar:git-PaperSpigot-f6fba00-9935adc]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202]
```
When a player without permissions moves grim starts spamming this warn,

### Grim version

grim 2.3.66

### Server version

1.8.8 

### Plugins

PacketsEvents and GrimAC

**Comment by SamB440** [comment]
See #1635

**Comment by MathsAnalysis** [comment]
If you mean to replace the part of the code shown within the 'commit you indicated in that issue I have already done that but it still yields error.
