### ISSUE TITLE
About TeamHandler Error

### ISSUE THREAD

**Issue by RegotlyLong** [GrimAnticheat/Grim#1638]
### Stack trace

[05:56:11 WARN]: PacketEvents caught an unhandled exception while calling your listener.
java.lang.RuntimeException: The received string length is longer than maximum allowed (26 > 16)
        at ac.grim.grimac.shaded.com.github.retrooper.packetevents.wrapper.PacketWrapper.readString(PacketWrapper.java:621) ~[?:?]
        at ac.grim.grimac.shaded.com.github.retrooper.packetevents.wrapper.play.server.WrapperPlayServerTeams.read(WrapperPlayServerTeams.java:165) ~[?:?]
        at ac.grim.grimac.shaded.com.github.retrooper.packetevents.wrapper.PacketWrapper.readEvent(PacketWrapper.java:254) ~[?:?]
        at ac.grim.grimac.shaded.com.github.retrooper.packetevents.wrapper.PacketWrapper.<init>(PacketWrapper.java:159) ~[?:?]
        at ac.grim.grimac.shaded.com.github.retrooper.packetevents.wrapper.PacketWrapper.<init>(PacketWrapper.java:149) ~[?:?]
        at ac.grim.grimac.shaded.com.github.retrooper.packetevents.wrapper.play.server.WrapperPlayServerTeams.<init>(WrapperPlayServerTeams.java:122) ~[?:?]
        at ac.grim.grimac.utils.team.TeamHandler.onPacketSend(TeamHandler.java:94) ~[?:?]
        at ac.grim.grimac.manager.CheckManager.onPacketSend(CheckManager.java:214) ~[?:?]
        at ac.grim.grimac.events.packets.CheckManagerListener.onPacketSend(CheckManagerListener.java:841) ~[?:?]
        at ac.grim.grimac.shaded.com.github.retrooper.packetevents.event.PacketSendEvent.call(PacketSendEvent.java:51) ~[?:?]
        at ac.grim.grimac.shaded.com.github.retrooper.packetevents.event.EventManager.callEvent(EventManager.java:84) ~[?:?]
        at ac.grim.grimac.shaded.com.github.retrooper.packetevents.util.PacketEventsImplHelper.handleClientBoundPacket(PacketEventsImplHelper.java:45) ~[?:?]
        at ac.grim.grimac.shaded.io.github.retrooper.packetevents.injector.handlers.PacketEventsEncoder.handleClientBoundPacket(PacketEventsEncoder.java:82) ~[?:?]
        at ac.grim.grimac.shaded.io.github.retrooper.packetevents.injector.handlers.PacketEventsEncoder.encode(PacketEventsEncoder.java:67) ~[?:?]
        at ac.grim.grimac.shaded.io.github.retrooper.packetevents.injector.handlers.PacketEventsEncoder.encode(PacketEventsEncoder.java:46) ~[?:?]

### How to replicate it if known

Server version 1.8.8
Player Client version 1.8.8**（But through via cross Client version to 1.13+）**
![image](https://github.com/user-attachments/assets/616194a2-3eb1-4ad4-8e06-fd473c1797d5)

### Grim version

packetevent version: 2.5.0

Grimversion:
Commit
Merge pull request https://github.com/GrimAnticheat/Grim/pull/1600 from SamB440/feat/entity-pushing-2
Limit entity push abuse

### Server version

This server is running CraftBukkit version git-PaperSpigot-445 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

### Plugins

WorldEdit, PlaceholderAPI, PlugMan, spark, ViaVersion, PlugManX, LiteBans, ViaBackwards, ProtocolLib, LuckPerms, Citizens, BridgingAnalyzer, GrimAC

**Comment by SamB440** [comment]
You have a plugin sending longer than possible team prefixes.

**Comment by RegotlyLong** [comment]
sorry
