### ISSUE TITLE
Major error spam from latest patch

### ISSUE THREAD

**Issue by ghost** [GrimAnticheat/Grim#1640]
### Stack trace

[12:24:13] [Netty Epoll Server IO #1/WARN]: [ac.grim.grimac.shaded.com.github.retrooper.packetevents.PacketEventsAPI] PacketEvents caught an unhandled exception while calling your listener.
java.lang.NullPointerException: Cannot invoke "java.util.UUID.toString()" because the return value of "ac.grim.grimac.utils.data.packetentity.PacketEntity.getUuid()" is null
	at grim.jar/ac.grim.grimac.utils.team.TeamHandler.getEntityTeam(TeamHandler.java:37) ~[grim.jar:?]
	at grim.jar/ac.grim.grimac.utils.team.EntityPredicates.canBePushedBy(EntityPredicates.java:14) ~[grim.jar:?]
	at grim.jar/ac.grim.grimac.predictionengine.movementtick.MovementTicker.handleEntityCollisions(MovementTicker.java:58) ~[grim.jar:?]
	at grim.jar/ac.grim.grimac.predictionengine.movementtick.MovementTicker.livingEntityAIStep(MovementTicker.java:207) ~[grim.jar:?]
	at grim.jar/ac.grim.grimac.predictionengine.MovementCheckRunner.check(MovementCheckRunner.java:488) ~[grim.jar:?]
	at grim.jar/ac.grim.grimac.predictionengine.MovementCheckRunner.processAndCheckMovementPacket(MovementCheckRunner.java:74) ~[grim.jar:?]
	at grim.jar/ac.grim.grimac.checks.impl.movement.PredictionRunner.onPositionUpdate(PredictionRunner.java:16) ~[grim.jar:?]
	at grim.jar/ac.grim.grimac.manager.CheckManager.onPositionUpdate(CheckManager.java:223) ~[grim.jar:?]

### How to replicate it if known

probably packet entities?

### Grim version

43595675e4abe39b94ef1f1a8b8fc9e564008648

### Server version

1.21.1 latest paper

### Plugins

grim

**Comment by SamB440** [comment]
That doesn't look like you're using only Grim, you must be using some other plugin that's sending invalid entity data, all entities should have a uuid associated with them on 1.9+

**Comment by bbb908** [comment]
> That doesn't look like you're using only Grim, you must be using some other plugin that's sending invalid entity data, all entities should have a uuid associated with them on 1.9+

I also get this issue I saw on the packets event github they have 2.4.0 (first release supporting 1.21) which could be more stable and fix it
