### ISSUE TITLE
Player cannot climb 

### ISSUE THREAD

**Issue by Dg32z** [GrimAnticheat/Grim#1657]
### Stack trace

[10:55:51 WARN]: [ac.grim.grimac.shaded.com.github.retrooper.packetevents.PacketEventsAPI] PacketEvents caught an unhandled exception while calling your listener.
java.lang.NullPointerException: Cannot invoke "ac.grim.grimac.shaded.com.github.retrooper.packetevents.protocol.world.states.type.StateType$Mapped.getStateType()" because the return value of "ac.grim.grimac.shaded.com.github.retrooper.packetevents.protocol.world.states.type.StateTypes.getMappedById(ac.grim.grimac.shaded.com.github.retrooper.packetevents.protocol.player.ClientVersion, int)" is null
        at grimac-2.3.67.jar/ac.grim.grimac.shaded.com.github.retrooper.packetevents.protocol.world.states.type.StateTypes.getById(StateTypes.java:67) ~[grimac-2.3.67.jar:?]
        at grimac-2.3.67.jar/ac.grim.grimac.utils.data.tags.SyncedTags.lambda$new$0(SyncedTags.java:34) ~[grimac-2.3.67.jar:?]
        at grimac-2.3.67.jar/ac.grim.grimac.utils.data.tags.SyncedTag.readTagValues(SyncedTag.java:39) ~[grimac-2.3.67.jar:?]
        at grimac-2.3.67.jar/ac.grim.grimac.utils.data.tags.SyncedTags.lambda$handleTagSync$1(SyncedTags.java:61) ~[grimac-2.3.67.jar:?]
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1596) ~[?:?]
        at grimac-2.3.67.jar/ac.grim.grimac.utils.data.tags.SyncedTags.lambda$handleTagSync$2(SyncedTags.java:59) ~[grimac-2.3.67.jar:?]
        at java.base/java.util.HashMap.forEach(HashMap.java:1429) ~[?:?]
        at grimac-2.3.67.jar/ac.grim.grimac.utils.data.tags.SyncedTags.handleTagSync(SyncedTags.java:56) ~[grimac-2.3.67.jar:?]
        at grimac-2.3.67.jar/ac.grim.grimac.events.packets.PacketServerTags.onPacketSend(PacketServerTags.java:24) ~[grimac-2.3.67.jar:?]
        at grimac-2.3.67.jar/ac.grim.grimac.shaded.com.github.retrooper.packetevents.event.PacketSendEvent.call(PacketSendEvent.java:51) ~[grimac-2.3.67.jar:?]
        at grimac-2.3.67.jar/ac.grim.grimac.shaded.com.github.retrooper.packetevents.event.EventManager.callEvent(EventManager.java:84) ~[grimac-2.3.67.jar:?]
        at grimac-2.3.67.jar/ac.grim.grimac.shaded.com.github.retrooper.packetevents.util.PacketEventsImplHelper.handleClientBoundPacket(PacketEventsImplHelper.java:45) ~[grimac-2.3.67.jar:?]
        at grimac-2.3.67.jar/ac.grim.grimac.shaded.io.github.retrooper.packetevents.injector.handlers.PacketEventsEncoder.handleClientBoundPacket(PacketEventsEncoder.java:87) ~[grimac-2.3.67.jar:?]
        at grimac-2.3.67.jar/ac.grim.grimac.shaded.io.github.retrooper.packetevents.injector.handlers.PacketEventsEncoder.encode(PacketEventsEncoder.java:72) ~[grimac-2.3.67.jar:?]
        at grimac-2.3.67.jar/ac.grim.grimac.shaded.io.github.retrooper.packetevents.injector.handlers.PacketEventsEncoder.encode(PacketEventsEncoder.java:51) ~[grimac-2.3.67.jar:?]
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:90) ~[netty-codec-4.1.97.Final.jar:4.1.97.Final]
        at grimac-2.3.67.jar/ac.grim.grimac.shaded.io.github.retrooper.packetevents.injector.handlers.PacketEventsEncoder.write(PacketEventsEncoder.java:106) ~[grimac-2.3.67.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113) ~[netty-codec-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.ChannelOutboundHandlerAdapter.write(ChannelOutboundHandlerAdapter.java:113) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at net.minecraft.network.Connection$2.write(Connection.java:819) ~[luminol-1.21.1.jar:1.21.1-DEV-7c312e7]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:940) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:966) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:934) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:984) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at net.minecraft.network.Connection.doSendPacket(Connection.java:540) ~[luminol-1.21.1.jar:1.21.1-DEV-7c312e7]
        at net.minecraft.network.Connection.lambda$sendPacket$13(Connection.java:525) ~[luminol-1.21.1.jar:1.21.1-DEV-7c312e7]
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[10:55:51 INFO]: Dg32z_ joined the game

### How to replicate it if known

When players under version 1.20.4 join the server, it happen

### Grim version

> ver GrimAC
[10:57:25 INFO]: GrimAC version 2.3.67
[10:57:25 INFO]: Libre simulation anticheat designed for 1.21 with 1.8-1.21 support, powered by PacketEvents 2.0.
[10:57:25 INFO]: Author: GrimAC
>

### Server version

[10:57:09 INFO]: Checking version, please wait...
[10:57:10 INFO]: This server is running Luminol version 1.21.1-DEV-dev/1.21.1@7c312e7 (2024-08-17T05:31:51Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)
You are 4 version(s) behind
Download the new version at: https://github.com/LuminolMC/Luminol
Previous version: 1.21-54-f250ec0 (MC: 1.21)

### Plugins

[10:57:19 INFO]: Server Plugins (8):
[10:57:19 INFO]: Bukkit Plugins:
[10:57:19 INFO]:  - FastCrystal, GrimAC, LiteBans, LuckPerms, PlaceholderAPI, PlugManX, ViaBackwards, ViaVersio

**Comment by SamB440** [comment]
Is your server sending custom blocks or something...?

**Comment by SamB440** [comment]
I guess it needs to use server version instead of client version, but then the question is how do we determine what blocks are climbable on a player's version...
