### ISSUE TITLE
The permission grim.exempt.reach is already defined!

### ISSUE THREAD

**Issue by NO-UUID** [GrimAnticheat/Grim#1771]
### Stack trace

```
[06:32:01] [Netty Epoll Server IO #3/WARN]: [io.netty.util.concurrent.DefaultPromise] An exception was thrown by ac.grim.grimac.shaded.io.github.retrooper.packetevents.injector.handlers.PacketEventsEncoder$$Lambda/0x00007fcad218c000.operationComplete()
java.lang.IllegalArgumentException: The permission grim.exempt.reach is already defined!
	at io.papermc.paper.plugin.manager.PaperPermissionManager.addPermission(PaperPermissionManager.java:56) ~[sakura-1.21.1.jar:1.21.1-DEV-f156073]
	at io.papermc.paper.plugin.manager.PaperPermissionManager.addPermission(PaperPermissionManager.java:40) ~[sakura-1.21.1.jar:1.21.1-DEV-f156073]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.addPermission(PaperPluginManagerImpl.java:158) ~[sakura-1.21.1.jar:1.21.1-DEV-f156073]
	at org.bukkit.plugin.SimplePluginManager.addPermission(SimplePluginManager.java:772) ~[sakura-api-1.21.1-R0.1-SNAPSHOT.jar:?]
	at GrimAC.jar/ac.grim.grimac.manager.CheckManager.init(CheckManager.java:340) ~[GrimAC.jar:?]
	at GrimAC.jar/ac.grim.grimac.manager.CheckManager.<init>(CheckManager.java:180) ~[GrimAC.jar:?]
	at GrimAC.jar/ac.grim.grimac.player.GrimPlayer.<init>(GrimPlayer.java:229) ~[GrimAC.jar:?]
	at GrimAC.jar/ac.grim.grimac.utils.anticheat.PlayerDataManager.addUser(PlayerDataManager.java:68) ~[GrimAC.jar:?]
	at GrimAC.jar/ac.grim.grimac.events.packets.PacketPlayerJoinQuit.lambda$onPacketSend$0(PacketPlayerJoinQuit.java:18) ~[GrimAC.jar:?]
	at GrimAC.jar/ac.grim.grimac.shaded.io.github.retrooper.packetevents.injector.handlers.PacketEventsEncoder.lambda$handleClientBoundPacket$0(PacketEventsEncoder.java:91) ~[GrimAC.jar:?]
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:590) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:583) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:559) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:492) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:636) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:625) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:105) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.util.internal.PromiseNotificationUtil.trySuccess(PromiseNotificationUtil.java:48) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.ChannelOutboundBuffer.safeSuccess(ChannelOutboundBuffer.java:727) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.ChannelOutboundBuffer.remove(ChannelOutboundBuffer.java:282) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.ChannelOutboundBuffer.removeBytes(ChannelOutboundBuffer.java:362) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.epoll.AbstractEpollChannel.doWriteBytes(AbstractEpollChannel.java:364) ~[netty-transport-classes-epoll-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.epoll.AbstractEpollStreamChannel.writeBytes(AbstractEpollStreamChannel.java:260) ~[netty-transport-classes-epoll-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.epoll.AbstractEpollStreamChannel.doWriteSingle(AbstractEpollStreamChannel.java:471) ~[netty-transport-classes-epoll-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.epoll.AbstractEpollStreamChannel.doWrite(AbstractEpollStreamChannel.java:429) ~[netty-transport-classes-epoll-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:931) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.flush0(AbstractEpollChannel.java:557) ~[netty-transport-classes-epoll-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush(AbstractChannel.java:895) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.flush(DefaultChannelPipeline.java:1372) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:921) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:907) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:893) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.handler.flush.FlushConsolidationHandler.flushNow(FlushConsolidationHandler.java:204) ~[netty-handler-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.handler.flush.FlushConsolidationHandler.flush(FlushConsolidationHandler.java:138) ~[netty-handler-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:923) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:907) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:893) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.ChannelOutboundHandlerAdapter.flush(ChannelOutboundHandlerAdapter.java:125) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:925) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:941) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:966) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:934) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:984) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at net.minecraft.network.Connection.doSendPacket(Connection.java:513) ~[sakura-1.21.1.jar:1.21.1-DEV-f156073]
	at net.minecraft.network.Connection.lambda$sendPacket$13(Connection.java:498) ~[sakura-1.21.1.jar:1.21.1-DEV-f156073]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:413) ~[netty-transport-classes-epoll-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

Seems to be happening kinda randomly, for nofall, reach, etc... different permissions.

### How to replicate it if known

Not sure, it happens on server start up, before any of players would join.

### Grim version

> ver GrimAC
[11:49:33 INFO]: GrimAC version 2.3.68
[11:49:33 INFO]: Libre simulation anticheat designed for 1.21 with 1.8-1.21 support, powered by PacketEvents 2.0.
[11:49:33 INFO]: Website: https://grim.ac/
[11:49:33 INFO]: Author: GrimAC

Latest version from github actions

### Server version

Latest paper/sakura 1.21.1

### Plugins

[11:50:15 INFO]: Bukkit Plugins:
[11:50:16 INFO]:  - AdditionalFeatures, AuctionHouse, AxSmithing, BentoBox, BentoBox-Bank, BentoBox-Biomes, BentoBox-BSkyBlock, BentoBox-Challenges, BentoBox-CheckMeOut, BentoBox-IslandFly
[11:50:16 INFO]:  BentoBox-Likes, BentoBox-MagicCobblestoneGenerator, BentoBox-Warps, BentoBoxPlus, Citizens, Crates, DecentHolograms, EchoPet, FastAsyncWorldEdit, GrimAC
[11:50:16 INFO]:  GSit, LockettePro, LogBlock, mcMMO, NoCheatEnforcer, ServerManager, ShopManager, SimpleTrading, SkyGrid, UserManager
[11:50:16 INFO]:  Vault, ViaBackwards, ViaRewind, ViaRewind-Legacy-Support, ViaVersion, WorldGuard

**Comment by AoElite** [comment]
@IAISI Exception should be catched if it occurs now faa471b19721ac60334bff582f83ed5e50f9dd8e
