### ISSUE TITLE
error in console on reload command

### ISSUE THREAD

**Issue by makegodhere** [GrimAnticheat/Grim#1778]
### Stack trace

[13:21:06 INFO]: PalladiuM issued server command: /grimac reload
[13:21:06 WARN]: [io.netty.util.concurrent.AbstractEventExecutor] A task raised an exception. Task: ac.grim.grimac.GrimExternalAPI$$Lambda/0x00007f605f1f9160@4bed8889
java.lang.NullPointerException: Cannot invoke "String.toLowerCase()" because "this.checkName" is null
	at grimac-2.3.67.jar/ac.grim.grimac.checks.Check.reload(Check.java:108) ~[grimac-2.3.67.jar:?]
	at grimac-2.3.67.jar/ac.grim.grimac.GrimExternalAPI.lambda$reload$1(GrimExternalAPI.java:93) ~[grimac-2.3.67.jar:?]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:413) ~[netty-transport-classes-epoll-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[13:21:06 WARN]: [io.netty.util.concurrent.AbstractEventExecutor] A task raised an exception. Task: ac.grim.grimac.GrimExternalAPI$$Lambda/0x00007f605f1f9160@34aceb40
java.lang.NullPointerException: Cannot invoke "String.toLowerCase()" because "this.checkName" is null
	at grimac-2.3.67.jar/ac.grim.grimac.checks.Check.reload(Check.java:108) ~[grimac-2.3.67.jar:?]
	at grimac-2.3.67.jar/ac.grim.grimac.GrimExternalAPI.lambda$reload$1(GrimExternalAPI.java:93) ~[grimac-2.3.67.jar:?]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:413) ~[netty-transport-classes-epoll-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

### How to replicate it if known

call command /grimac reload

### Grim version

2.3.67

### Server version

1.21.1

### Plugins

all working good - only error in logs

**Comment by ManInMyVan** [comment]
update to the latest commit

**Comment by makegodhere** [comment]
> update to the latest commit

where to find last build for download?

**Comment by Anthony01M** [comment]
> > update to the latest commit
> 
> where to find last build for download?

https://github.com/GrimAnticheat/Grim/actions/runs/11632786554/artifacts/2133873098

**Comment by ManInMyVan** [comment]
pretty this can be closed now
