### ISSUE TITLE
Cannot get attribute minecraft:attack_speed for entity minecraft:player!

### ISSUE THREAD

**Issue by Dg32z** [GrimAnticheat/Grim#1870]
### Describe the bug and how to replicate it

[00:20:37 WARN]: [ac.grim.grimac.shaded.com.github.retrooper.packetevents.PacketEventsAPI] PacketEvents caught an unhandled exception while calling your listener.
java.lang.IllegalArgumentException: Cannot get attribute minecraft:attack_speed for entity minecraft:player!
        at grimac.jar/ac.grim.grimac.utils.data.packetentity.PacketEntity.getAttributeValue(PacketEntity.java:108) ~[grimac.jar:?]
        at grimac.jar/ac.grim.grimac.events.packets.PacketPlayerAttack.onPacketReceive(PacketPlayerAttack.java:118) ~[grimac.jar:?]
        at grimac.jar/ac.grim.grimac.shaded.com.github.retrooper.packetevents.event.PacketReceiveEvent.call(PacketReceiveEvent.java:44) ~[grimac.jar:?]
        at grimac.jar/ac.grim.grimac.shaded.com.github.retrooper.packetevents.event.EventManager.callEvent(EventManager.java:84) ~[grimac.jar:?]
        at grimac.jar/ac.grim.grimac.shaded.com.github.retrooper.packetevents.util.PacketEventsImplHelper.handleServerBoundPacket(PacketEventsImplHelper.java:101) ~[grimac.jar:?]
        at grimac.jar/ac.grim.grimac.shaded.io.github.retrooper.packetevents.injector.handlers.PacketEventsDecoder.read(PacketEventsDecoder.java:57) ~[grimac.jar:?]
        at grimac.jar/ac.grim.grimac.shaded.io.github.retrooper.packetevents.injector.handlers.PacketEventsDecoder.decode(PacketEventsDecoder.java:64) ~[grimac.jar:?]
        at grimac.jar/ac.grim.grimac.shaded.io.github.retrooper.packetevents.injector.handlers.PacketEventsDecoder.decode(PacketEventsDecoder.java:41) ~[grimac.jar:?]

### Grim version

2.3.68

### Server version

> ver
[00:25:08 INFO]: Checking version, please wait...
[00:25:09 INFO]: This server is running Paper version 1.21.1-116-master@e7e1ab5 (2024-09-30T23:17:54Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)
You are 16 version(s) behind
Download the new version at: https://papermc.io/downloads/paper
Previous version: 1.21.1-41-fcedb49 (MC: 1.21.1)

### Plugins

[00:25:38 INFO]: Server Plugins (13):
[00:25:38 INFO]: Bukkit Plugins:
[00:25:38 INFO]:  - FastAsyncWorldEdit, FastCrystal, GrimAC, hadesForBukkit, LiteBans, LuckPerms, Matrix, PlaceholderAPI, pvp
[00:25:38 INFO]:  Vault, ViaBackwards, ViaVersion, XConomy

**Comment by SamB440** [comment]
You are running a fork of grim, those line numbers don't add up. This is impossible - attack speed is tracked in the player entity.
