### ISSUE TITLE
Listener Warning After Every Join for Latest Version

### ISSUE THREAD

**Issue by zikehalil3535** [GrimAnticheat/Grim#1891]
### Stack trace

`[15:27:55 WARN]: [ac.grim.grimac.shaded.com.github.retrooper.packetevents.PacketEventsAPI] PacketEvents caught an unhandled exception while calling your listener.
ac.grim.grimac.shaded.kyori.adventure.text.minimessage.internal.parser.ParsingExceptionImpl: Legacy formatting codes have been detected in a MiniMessage string - this is unsupported behaviour. Please refer to the Adventure documentation (https://docs.advntr.dev) for more information.
        §x§F<dark_red>§C<dark_red>§F<dark_aqua>ɢ§x§F<gold>§B<dark_blue>§F<dark_red>ʟ§x§F<gray><blue>§F§F<gold>ᴀ§x§F<blue><dark_gray>§C§F<gray>ᴅ§x§F§A<gray>§A§F<blue>ɪ§x§F§C<gold><gray>§F§Aᴏ <dark_gray>» <white>Alerts enabled
          ^^
        at grimac-2.3.68.jar/ac.grim.grimac.shaded.kyori.adventure.text.minimessage.internal.parser.TokenParser.parseString(TokenParser.java:170) ~[grimac-2.3.68.jar:?]
        at grimac-2.3.68.jar/ac.grim.grimac.shaded.kyori.adventure.text.minimessage.internal.parser.TokenParser.resolvePreProcessTags(TokenParser.java:112) ~[grimac-2.3.68.jar:?]
        at grimac-2.3.68.jar/ac.grim.grimac.shaded.kyori.adventure.text.minimessage.MiniMessageParser.parseToTree(MiniMessageParser.java:195) ~[grimac-2.3.68.jar:?]
        at grimac-2.3.68.jar/ac.grim.grimac.shaded.kyori.adventure.text.minimessage.MiniMessageParser.parseFormat(MiniMessageParser.java:209) ~[grimac-2.3.68.jar:?]
        at grimac-2.3.68.jar/ac.grim.grimac.shaded.kyori.adventure.text.minimessage.MiniMessageImpl.deserialize(MiniMessageImpl.java:80) ~[grimac-2.3.68.jar:?]
        at grimac-2.3.68.jar/ac.grim.grimac.shaded.kyori.adventure.text.minimessage.MiniMessageImpl.deserialize(MiniMessageImpl.java:46) ~[grimac-2.3.68.jar:?]
        at grimac-2.3.68.jar/ac.grim.grimac.utils.anticheat.MessageUtil.miniMessage(MessageUtil.java:87) ~[grimac-2.3.68.jar:?]
        at grimac-2.3.68.jar/ac.grim.grimac.manager.AlertManagerImpl.toggleAlerts(AlertManagerImpl.java:28) ~[grimac-2.3.68.jar:?]
        at grimac-2.3.68.jar/ac.grim.grimac.events.packets.PacketPlayerJoinQuit.onUserLogin(PacketPlayerJoinQuit.java:38) ~[grimac-2.3.68.jar:?]
        at grimac-2.3.68.jar/ac.grim.grimac.shaded.com.github.retrooper.packetevents.event.UserLoginEvent.call(UserLoginEvent.java:44) ~[grimac-2.3.68.jar:?]
        at grimac-2.3.68.jar/ac.grim.grimac.shaded.com.github.retrooper.packetevents.event.EventManager.callEvent(EventManager.java:84) ~[grimac-2.3.68.jar:?]
        at grimac-2.3.68.jar/ac.grim.grimac.shaded.com.github.retrooper.packetevents.event.EventManager.callEvent(EventManager.java:67) ~[grimac-2.3.68.jar:?]
        at grimac-2.3.68.jar/ac.grim.grimac.shaded.io.github.retrooper.packetevents.injector.SpigotChannelInjector.updatePlayer(SpigotChannelInjector.java:50) ~[grimac-2.3.68.jar:?]
        at grimac-2.3.68.jar/ac.grim.grimac.shaded.io.github.retrooper.packetevents.bukkit.InternalBukkitListener.onJoin(InternalBukkitListener.java:61) ~[grimac-2.3.68.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1173.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:1.21.1-21-cfa3c61]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[pufferfish-1.21.1.jar:1.21.1-21-cfa3c61]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[pufferfish-1.21.1.jar:1.21.1-21-cfa3c61]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:630) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.players.PlayerList.placeNewPlayer(PlayerList.java:347) ~[pufferfish-1.21.1.jar:1.21.1-21-cfa3c61]
        at net.minecraft.server.network.ServerConfigurationPacketListenerImpl.handleConfigurationFinished(ServerConfigurationPacketListenerImpl.java:173) ~[pufferfish-1.21.1.jar:1.21.1-21-cfa3c61]
        at net.minecraft.network.protocol.configuration.ServerboundFinishConfigurationPacket.handle(ServerboundFinishConfigurationPacket.java:22) ~[pufferfish-1.21.1.jar:1.21.1-21-cfa3c61]
        at net.minecraft.network.protocol.configuration.ServerboundFinishConfigurationPacket.handle(ServerboundFinishConfigurationPacket.java:13) ~[pufferfish-1.21.1.jar:1.21.1-21-cfa3c61]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:56) ~[pufferfish-1.21.1.jar:1.21.1-21-cfa3c61]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[pufferfish-1.21.1.jar:1.21.1-21-cfa3c61]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[pufferfish-1.21.1.jar:1.21.1-21-cfa3c61]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[pufferfish-1.21.1.jar:1.21.1-21-cfa3c61]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1542) ~[pufferfish-1.21.1.jar:1.21.1-21-cfa3c61]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[pufferfish-1.21.1.jar:1.21.1-21-cfa3c61]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[pufferfish-1.21.1.jar:1.21.1-21-cfa3c61]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1519) ~[pufferfish-1.21.1.jar:1.21.1-21-cfa3c61]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1512) ~[pufferfish-1.21.1.jar:1.21.1-21-cfa3c61]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[pufferfish-1.21.1.jar:1.21.1-21-cfa3c61]
        at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1471) ~[pufferfish-1.21.1.jar:1.21.1-21-cfa3c61]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1478) ~[pufferfish-1.21.1.jar:1.21.1-21-cfa3c61]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1323) ~[pufferfish-1.21.1.jar:1.21.1-21-cfa3c61]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[pufferfish-1.21.1.jar:1.21.1-21-cfa3c61]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]`

### How to replicate it if known

Step 1. Join the server
Step 2. Take the warning.

### Grim version

GrimAC version 2.3.68

### Server version

 Pufferfish version 1.21.1-21-HEAD@cfa3c61

### Plugins

I dont want to give my plugins list.

**Comment by ManInMyVan** [comment]
use &# for hex codes

**Comment by zikehalil3535** [comment]
> Contributor

`[21:53:03 INFO]: I'm sorry, but there was an error performing this command.
[21:53:03 ERROR]: [GrimAC] [ACF] Exception in command: grim reload
[21:53:03 ERROR]: [GrimAC] [ACF] java.lang.IndexOutOfBoundsException: No group 1
[21:53:03 ERROR]: [GrimAC] [ACF]        at java.base/java.util.regex.Matcher.checkGroup(Matcher.java:1847)
[21:53:03 ERROR]: [GrimAC] [ACF]        at java.base/java.util.regex.Matcher.group(Matcher.java:688)
[21:53:03 ERROR]: [GrimAC] [ACF]        at grimac-2.3.68.jar//ac.grim.grimac.utils.anticheat.MessageUtil.miniMessage(MessageUtil.java:56)
[21:53:03 ERROR]: [GrimAC] [ACF]        at grimac-2.3.68.jar//ac.grim.grimac.commands.GrimReload.onReload(GrimReload.java:18)
[21:53:03 ERROR]: [GrimAC] [ACF]        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[21:53:03 ERROR]: [GrimAC] [ACF]        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
[21:53:03 ERROR]: [GrimAC] [ACF]        at grimac-2.3.68.jar//ac.grim.grimac.shaded.acf.RegisteredCommand.invoke(RegisteredCommand.java:152)
[21:53:03 ERROR]: [GrimAC] [ACF]        at grimac-2.3.68.jar//ac.grim.grimac.shaded.acf.BaseCommand.executeCommand(BaseCommand.java:578)
[21:53:03 ERROR]: [GrimAC] [ACF]        at grimac-2.3.68.jar//ac.grim.grimac.shaded.acf.BaseCommand.execute(BaseCommand.java:513)
[21:53:03 ERROR]: [GrimAC] [ACF]        at grimac-2.3.68.jar//ac.grim.grimac.shaded.acf.RootCommand.execute(RootCommand.java:99)
[21:53:03 ERROR]: [GrimAC] [ACF]        at grimac-2.3.68.jar//ac.grim.grimac.shaded.acf.BukkitRootCommand.execute(BukkitRootCommand.java:84)
[21:53:03 ERROR]: [GrimAC] [ACF]        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:165)
[21:53:03 ERROR]: [GrimAC] [ACF]        at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:1001)
[21:53:03 ERROR]: [GrimAC] [ACF]        at org.bukkit.craftbukkit.CraftServer.dispatchServerCommand(CraftServer.java:986)
[21:53:03 ERROR]: [GrimAC] [ACF]        at net.minecraft.server.dedicated.DedicatedServer.handleConsoleInputs(DedicatedServer.java:529)
[21:53:03 ERROR]: [GrimAC] [ACF]        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:477)
[21:53:03 ERROR]: [GrimAC] [ACF]        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1603)
[21:53:03 ERROR]: [GrimAC] [ACF]        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1303)
[21:53:03 ERROR]: [GrimAC] [ACF]        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330)
[21:53:03 ERROR]: [GrimAC] [ACF]        at java.base/java.lang.Thread.run(Thread.java:1583)`

Still same problem.

**Comment by zikehalil3535** [comment]
Okey I found the solution, so messages.yml has changed I need to update it. Tysm.
