### ISSUE TITLE
Error When I use Reload Command

### ISSUE THREAD

**Issue by whiskeytr** [GrimAnticheat/Grim#1897]
### Stack trace

```> grimac reload
[00:03:04 INFO]: I'm sorry, but there was an error performing this command.
[00:03:04 ERROR]: [GrimAC] [ACF] Exception in command: grim reload
[00:03:04 ERROR]: [GrimAC] [ACF] java.lang.IndexOutOfBoundsException: No group 1
[00:03:04 ERROR]: [GrimAC] [ACF]        at java.base/java.util.regex.Matcher.checkGroup(Matcher.java:1847)
[00:03:04 ERROR]: [GrimAC] [ACF]        at java.base/java.util.regex.Matcher.group(Matcher.java:688)
[00:03:04 ERROR]: [GrimAC] [ACF]        at grimac-2.3.68.jar//ac.grim.grimac.utils.anticheat.MessageUtil.miniMessage(MessageUtil.java:56)
[00:03:04 ERROR]: [GrimAC] [ACF]        at grimac-2.3.68.jar//ac.grim.grimac.commands.GrimReload.onReload(GrimReload.java:18)
[00:03:04 ERROR]: [GrimAC] [ACF]        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[00:03:04 ERROR]: [GrimAC] [ACF]        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
[00:03:04 ERROR]: [GrimAC] [ACF]        at grimac-2.3.68.jar//ac.grim.grimac.shaded.acf.RegisteredCommand.invoke(RegisteredCommand.java:152)
[00:03:04 ERROR]: [GrimAC] [ACF]        at grimac-2.3.68.jar//ac.grim.grimac.shaded.acf.BaseCommand.executeCommand(BaseCommand.java:578)
[00:03:04 ERROR]: [GrimAC] [ACF]        at grimac-2.3.68.jar//ac.grim.grimac.shaded.acf.BaseCommand.execute(BaseCommand.java:513)
[00:03:04 ERROR]: [GrimAC] [ACF]        at grimac-2.3.68.jar//ac.grim.grimac.shaded.acf.RootCommand.execute(RootCommand.java:99)
[00:03:04 ERROR]: [GrimAC] [ACF]        at grimac-2.3.68.jar//ac.grim.grimac.shaded.acf.BukkitRootCommand.execute(BukkitRootCommand.java:84)
[00:03:04 ERROR]: [GrimAC] [ACF]        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:165)
[00:03:04 ERROR]: [GrimAC] [ACF]        at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:1001)
[00:03:04 ERROR]: [GrimAC] [ACF]        at org.bukkit.craftbukkit.CraftServer.dispatchServerCommand(CraftServer.java:986)
[00:03:04 ERROR]: [GrimAC] [ACF]        at net.minecraft.server.dedicated.DedicatedServer.handleConsoleInputs(DedicatedServer.java:529)
[00:03:04 ERROR]: [GrimAC] [ACF]        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:477)
[00:03:04 ERROR]: [GrimAC] [ACF]        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1603)
[00:03:04 ERROR]: [GrimAC] [ACF]        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1303)
[00:03:04 ERROR]: [GrimAC] [ACF]        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330)
[00:03:04 ERROR]: [GrimAC] [ACF]        at java.base/java.lang.Thread.run(Thread.java:1583)
>```

### How to replicate it if known

Step 1. Try to reload plugin like use /grimac reload.
Step 2. Get the error after that.

### Grim version

 GrimAC version 2.3.68

### Server version

 Pufferfish version 1.21.1-21-HEAD@cfa3c61

### Plugins

I dont want to give my plugins in here.

**Comment by whiskeytr** [comment]
Problem caused by Hex format so dont use it for dev fix it.

**Comment by SamB440** [comment]
What hex format are you using

**Comment by whiskeytr** [comment]
> What hex format are you using

§ format and &# format same error.

**Comment by ManInMyVan** [comment]
70d0fa96c29016e42e03d1abcab9c5160204f4f9
