### ISSUE TITLE
Console spam when actively hitting a mob with a sword

### ISSUE THREAD

**Issue by DeJoin** [GrimAnticheat/Grim#1899]
### Stack trace

[20:47:23] [Netty Epoll Server IO #0/WARN]: [ac.grim.grimac.shaded.com.github.retrooper.packetevents.PacketEventsAPI] PacketEvents caught an unhandled exception while calling your listener.
java.lang.NullPointerException: Cannot invoke "ac.grim.grimac.utils.collisions.datatypes.SimpleCollisionBox.expand(double)" because "box" is null
	at ac.grim.grimac.utils.nmsutil.BlockRayTrace.getNearestHitResult(BlockRayTrace.java:364) ~[?:?]
	at ac.grim.grimac.checks.impl.combat.Reach.didRayTraceHit(Reach.java:326) ~[?:?]
	at ac.grim.grimac.checks.impl.combat.Reach.checkReach(Reach.java:266) ~[?:?]
	at ac.grim.grimac.checks.impl.combat.Reach.tickBetterReachCheckWithAngle(Reach.java:174) ~[?:?]
	at ac.grim.grimac.checks.impl.combat.Reach.onPacketReceive(Reach.java:138) ~[?:?]
	at ac.grim.grimac.manager.CheckManager.onPacketReceive(CheckManager.java:250) ~[?:?]
	at ac.grim.grimac.events.packets.CheckManagerListener.onPacketReceive(CheckManagerListener.java:533) ~[?:?]
	at ac.grim.grimac.shaded.com.github.retrooper.packetevents.event.PacketReceiveEvent.call(PacketReceiveEvent.java:44) ~[?:?]
	at ac.grim.grimac.shaded.com.github.retrooper.packetevents.event.EventManager.callEvent(EventManager.java:84) ~[?:?]
	at ac.grim.grimac.shaded.com.github.retrooper.packetevents.util.PacketEventsImplHelper.handleServerBoundPacket(PacketEventsImplHelper.java:101) ~[?:?]
	at ac.grim.grimac.shaded.io.github.retrooper.packetevents.injector.handlers.PacketEventsDecoder.read(PacketEventsDecoder.java:57) ~[?:?]
	at ac.grim.grimac.shaded.io.github.retrooper.packetevents.injector.handlers.PacketEventsDecoder.decode(PacketEventsDecoder.java:64) ~[?:?]
	at ac.grim.grimac.shaded.io.github.retrooper.packetevents.injector.handlers.PacketEventsDecoder.decode(PacketEventsDecoder.java:41) ~[?:?]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:91) ~[ShieldSpigot.jar:git-ShieldSpigot-f467abd]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[ShieldSpigot.jar:git-ShieldSpigot-f467abd]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[ShieldSpigot.jar:git-ShieldSpigot-f467abd]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[ShieldSpigot.jar:git-ShieldSpigot-f467abd]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:107) ~[ShieldSpigot.jar:git-ShieldSpigot-f467abd]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[ShieldSpigot.jar:git-ShieldSpigot-f467abd]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[ShieldSpigot.jar:git-ShieldSpigot-f467abd]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[ShieldSpigot.jar:git-ShieldSpigot-f467abd]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:107) ~[ShieldSpigot.jar:git-ShieldSpigot-f467abd]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[ShieldSpigot.jar:git-ShieldSpigot-f467abd]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[ShieldSpigot.jar:git-ShieldSpigot-f467abd]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[ShieldSpigot.jar:git-ShieldSpigot-f467abd]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:107) ~[ShieldSpigot.jar:git-ShieldSpigot-f467abd]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[ShieldSpigot.jar:git-ShieldSpigot-f467abd]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[ShieldSpigot.jar:git-ShieldSpigot-f467abd]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[ShieldSpigot.jar:git-ShieldSpigot-f467abd]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:107) ~[ShieldSpigot.jar:git-ShieldSpigot-f467abd]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[ShieldSpigot.jar:git-ShieldSpigot-f467abd]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[ShieldSpigot.jar:git-ShieldSpigot-f467abd]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[ShieldSpigot.jar:git-ShieldSpigot-f467abd]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) ~[ShieldSpigot.jar:git-ShieldSpigot-f467abd]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318) ~[ShieldSpigot.jar:git-ShieldSpigot-f467abd]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[ShieldSpigot.jar:git-ShieldSpigot-f467abd]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[ShieldSpigot.jar:git-ShieldSpigot-f467abd]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[ShieldSpigot.jar:git-ShieldSpigot-f467abd]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) ~[ShieldSpigot.jar:git-ShieldSpigot-f467abd]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:333) ~[ShieldSpigot.jar:git-ShieldSpigot-f467abd]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:455) ~[ShieldSpigot.jar:git-ShieldSpigot-f467abd]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290) ~[ShieldSpigot.jar:git-ShieldSpigot-f467abd]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[ShieldSpigot.jar:git-ShieldSpigot-f467abd]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[ShieldSpigot.jar:git-ShieldSpigot-f467abd]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[ShieldSpigot.jar:git-ShieldSpigot-f467abd]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[ShieldSpigot.jar:git-ShieldSpigot-f467abd]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[ShieldSpigot.jar:git-ShieldSpigot-f467abd]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[ShieldSpigot.jar:git-ShieldSpigot-f467abd]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[ShieldSpigot.jar:git-ShieldSpigot-f467abd]
	at io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:152) ~[ShieldSpigot.jar:git-ShieldSpigot-f467abd]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[ShieldSpigot.jar:git-ShieldSpigot-f467abd]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[ShieldSpigot.jar:git-ShieldSpigot-f467abd]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[ShieldSpigot.jar:git-ShieldSpigot-f467abd]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1357) ~[ShieldSpigot.jar:git-ShieldSpigot-f467abd]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[ShieldSpigot.jar:git-ShieldSpigot-f467abd]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[ShieldSpigot.jar:git-ShieldSpigot-f467abd]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:868) ~[ShieldSpigot.jar:git-ShieldSpigot-f467abd]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:799) ~[ShieldSpigot.jar:git-ShieldSpigot-f467abd]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:501) ~[ShieldSpigot.jar:git-ShieldSpigot-f467abd]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:399) ~[ShieldSpigot.jar:git-ShieldSpigot-f467abd]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[ShieldSpigot.jar:git-ShieldSpigot-f467abd]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[ShieldSpigot.jar:git-ShieldSpigot-f467abd]
	at java.base/java.lang.Thread.run(Thread.java:1589) [?:?]

### How to replicate it if known

You just need to hit the mob or player with a sword, sometimes this error appears

### Grim version

2.3.69-b40

### Server version

Paper 1.16.5

### Plugins

AbstractMenus, ACubelets, AnimatedScoreboard, BAirDropX, BAuction, BLib, BottledExp, Chunky, ChunkyBorder, CMI, CMILib, CraftEnhance, CrazyCrates, DecentHolograms, DeluxeMenus, EnchantsSquared, fairy-lib-plugin, GrimAC, KillerMoney*, LuckPerms, Multiverse-Core, MyCommand, MythicMobs, OvRandomTeleport, packetevents, PlaceholderAPI, PlayerPoints, ProtocolLib, raytraced-antixray, ReActions, SCore, TerraformGenerator, Vault, ViaVersion, ViewDistanceTweaks, Vulcan, WorldEdit, WorldGuard, ZNPCsPlus

**Comment by SamB440** [comment]
You are running a fork.

**Comment by Axionize** [comment]
Please make an issue here and tell me how you managed to do this. What entity in the game has a null/no hitbox in Grim's modeling?

https://github.com/Axionize/LightningGrim/issues
