### ISSUE TITLE
Error when stopping server

### ISSUE THREAD

**Issue by DontNeedAName** [GrimAnticheat/Grim#576]
**Describe the bug**
Sometimes when I stop the server I get this error:
```
[22:42:24] [Server thread/ERROR]: Error occurred while disabling GrimAC v2.3.7 (Is it up to date?)
java.util.NoSuchElementException: pe-connection-handler-grimac
	at io.netty.channel.DefaultChannelPipeline.getContextOrDie(DefaultChannelPipeline.java:1073) ~[patched_1.17.1.jar:git-Paper-409]
	at io.netty.channel.DefaultChannelPipeline.remove(DefaultChannelPipeline.java:423) ~[patched_1.17.1.jar:git-Paper-409]
	at ac.grim.grimac.shaded.io.github.retrooper.packetevents.injector.SpigotChannelInjector.uninjectServerChannel(SpigotChannelInjector.java:188) ~[grimac-2.3.7-all.jar:?]
	at ac.grim.grimac.shaded.io.github.retrooper.packetevents.injector.SpigotChannelInjector.uninject(SpigotChannelInjector.java:131) ~[grimac-2.3.7-all.jar:?]
	at ac.grim.grimac.shaded.io.github.retrooper.packetevents.factory.spigot.SpigotPacketEventsBuilder$1.terminate(SpigotPacketEventsBuilder.java:236) ~[grimac-2.3.7-all.jar:?]
	at ac.grim.grimac.manager.init.stop.TerminatePacketEvents.start(TerminatePacketEvents.java:11) ~[grimac-2.3.7-all.jar:?]
	at ac.grim.grimac.manager.InitManager.stop(InitManager.java:52) ~[grimac-2.3.7-all.jar:?]
	at ac.grim.grimac.GrimAPI.stop(GrimAPI.java:36) ~[grimac-2.3.7-all.jar:?]
	at ac.grim.grimac.GrimAC.onDisable(GrimAC.java:14) ~[grimac-2.3.7-all.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[patched_1.17.1.jar:git-Paper-409]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:399) ~[patched_1.17.1.jar:git-Paper-409]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:537) ~[patched_1.17.1.jar:git-Paper-409]
	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:514) ~[patched_1.17.1.jar:git-Paper-409]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.disablePlugins(CraftServer.java:495) ~[patched_1.17.1.jar:git-Paper-409]
	at net.minecraft.server.MinecraftServer.stopServer(MinecraftServer.java:1053) ~[patched_1.17.1.jar:git-Paper-409]
	at net.minecraft.server.dedicated.DedicatedServer.stopServer(DedicatedServer.java:817) ~[patched_1.17.1.jar:git-Paper-409]
	at net.minecraft.server.MinecraftServer.close(MinecraftServer.java:1013) ~[patched_1.17.1.jar:git-Paper-409]
	at org.spigotmc.RestartCommand.shutdownServer(RestartCommand.java:92) ~[patched_1.17.1.jar:git-Paper-409]
	at org.spigotmc.RestartCommand.restart(RestartCommand.java:61) ~[patched_1.17.1.jar:git-Paper-409]
	at org.spigotmc.RestartCommand.restart(RestartCommand.java:40) ~[patched_1.17.1.jar:git-Paper-409]
	at org.spigotmc.RestartCommand$1.run(RestartCommand.java:31) ~[patched_1.17.1.jar:git-Paper-409]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1580) ~[patched_1.17.1.jar:git-Paper-409]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:490) ~[patched_1.17.1.jar:git-Paper-409]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1483) ~[patched_1.17.1.jar:git-Paper-409]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1282) ~[patched_1.17.1.jar:git-Paper-409]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-409]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**To Reproduce**
1. Start the server.
2. Stop it.
3. You should see the error. (If not you can try to join and leave and then stop the server)

**Server Version:**
Paper 1.17.1

**Grim Version (Git commit or the version in the jar's name)**
2.3.7

**Comment by MWHunter** [comment]
Plugins?

**Comment by DontNeedAName** [comment]
> Plugins?

AntiHealthIndicator, BungeeServerSigns, CustomHeads*, GrimAC, LuckPerms, LunarClient-API, LunarClient-Impl, NoteBlockAPI, OpenInv, PluginHiderPlus, PluginManager, ProtocolLib, spark, TAB, ViaBackwards, ViaVersion, WorldEdit

Yes this is still a thing after all those months.

**Comment by MWHunter** [comment]
Closing due to rewritten injector
