### ISSUE TITLE
Grim Packetevent error using new commit 985f249

### ISSUE THREAD

**Issue by noobi04** [GrimAnticheat/Grim#611]
**Describe the bug**
Errors are getting spammed in console using the new comit (id 985f249).

(not aware of how to upload log)

[00:21:09 WARN]: PacketEvents caught an unhandled exception while calling your listener.
java.lang.ClassCastException: class java.lang.Integer cannot be cast to class java.lang.Long (java.lang.Integer and java.lang.Long are in module java.base of loader 'bootstrap')
        at ac.grim.grimac.shaded.com.github.retrooper.packetevents.wrapper.play.client.WrapperPlayClientKeepAlive.read(WrapperPlayClientKeepAlive.java:46) ~[grimac-2.3.9-all.jar:?]
        at ac.grim.grimac.shaded.com.github.retrooper.packetevents.wrapper.PacketWrapper.readEvent(PacketWrapper.java:169) ~[grimac-2.3.9-all.jar:?]
        at ac.grim.grimac.shaded.com.github.retrooper.packetevents.wrapper.PacketWrapper.<init>(PacketWrapper.java:99) ~[grimac-2.3.9-all.jar:?]
        at ac.grim.grimac.shaded.com.github.retrooper.packetevents.wrapper.PacketWrapper.<init>(PacketWrapper.java:89) ~[grimac-2.3.9-all.jar:?]
        at ac.grim.grimac.shaded.com.github.retrooper.packetevents.wrapper.play.client.WrapperPlayClientKeepAlive.<init>(WrapperPlayClientKeepAlive.java:36) ~[grimac-2.3.9-all.jar:?]
        at ac.grim.grimac.checks.impl.badpackets.BadPacketsO.onPacketReceive(BadPacketsO.java:35) ~[grimac-2.3.9-all.jar:?]
        at ac.grim.grimac.manager.CheckManager.lambda$onPacketReceive$1(CheckManager.java:161) ~[grimac-2.3.9-all.jar:?]
        at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
        at ac.grim.grimac.manager.CheckManager.onPacketReceive(CheckManager.java:161) ~[grimac-2.3.9-all.jar:?]
        at ac.grim.grimac.events.packets.CheckManagerListener.onPacketReceive(CheckManagerListener.java:462) ~[grimac-2.3.9-all.jar:?]
        at ac.grim.grimac.shaded.com.github.retrooper.packetevents.event.PacketReceiveEvent.call(PacketReceiveEvent.java:45) ~[grimac-2.3.9-all.jar:?]
        at ac.grim.grimac.shaded.com.github.retrooper.packetevents.event.EventManager.callEvent(EventManager.java:51) [grimac-2.3.9-all.jar:?]
        at ac.grim.grimac.shaded.com.github.retrooper.packetevents.util.PacketEventsImplHelper.handleServerBoundPacket(PacketEventsImplHelper.java:81) [grimac-2.3.9-all.jar:?]
        at ac.grim.grimac.shaded.io.github.retrooper.packetevents.injector.handlers.PacketEventsDecoder.read(PacketEventsDecoder.java:67) [grimac-2.3.9-all.jar:?]
        at ac.grim.grimac.shaded.io.github.retrooper.packetevents.injector.handlers.PacketEventsDecoder.decode(PacketEventsDecoder.java:89) [grimac-2.3.9-all.jar:?]
        at jdk.internal.reflect.GeneratedMethodAccessor55.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at com.viaversion.viaversion.util.PipelineUtil.callDecode(PipelineUtil.java:75) [ViaVersion-4.3.1.jar:?]
        at com.viaversion.viaversion.bukkit.handlers.BukkitDecodeHandler.decode(BukkitDecodeHandler.java:59) [ViaVersion-4.3.1.jar:?]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:249) [spigot.jar:git-Spigot-21fe707-741a1bd]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:149) [spigot.jar:git-Spigot-21fe707-741a1bd]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [spigot.jar:git-Spigot-21fe707-741a1bd]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [spigot.jar:git-Spigot-21fe707-741a1bd]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163) [spigot.jar:git-Spigot-21fe707-741a1bd]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [spigot.jar:git-Spigot-21fe707-741a1bd]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [spigot.jar:git-Spigot-21fe707-741a1bd]
        at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:150) [spigot.jar:git-Spigot-21fe707-741a1bd]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [spigot.jar:git-Spigot-21fe707-741a1bd]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [spigot.jar:git-Spigot-21fe707-741a1bd]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787) [spigot.jar:git-Spigot-21fe707-741a1bd]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:130) [spigot.jar:git-Spigot-21fe707-741a1bd]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511) [spigot.jar:git-Spigot-21fe707-741a1bd]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468) [spigot.jar:git-Spigot-21fe707-741a1bd]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382) [spigot.jar:git-Spigot-21fe707-741a1bd]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354) [spigot.jar:git-Spigot-21fe707-741a1bd]
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [spigot.jar:git-Spigot-21fe707-741a1bd]
        at java.lang.Thread.run(Thread.java:829) [?:?]

**To Reproduce**
Build new commit and start server

**Server Version:**
Spigot 1.8.8

**Grim Version (Git commit or the version in the jar's name)**
2.3.9

**Comment by Wesley51** [comment]
Stick to the releases, not dev builds

**Comment by MWHunter** [comment]
PacketEvents commit causing this was reverted
