### ISSUE TITLE
Discord webhooks url parse error if ues proxy server

### ISSUE THREAD

**Issue by caoli5288** [GrimAnticheat/Grim#734]
### Stack trace

```
[17:26:21] [Server thread/INFO]: [GrimAC] Registering tick schedulers...
[17:26:21] [Server thread/WARN]: java.lang.IllegalArgumentException: Failed to parse webhook URL
[17:26:21] [Server thread/WARN]: 	at ac.grim.grimac.shaded.discord-webhooks.discord.webhook.WebhookClient.withUrl(WebhookClient.java:165)
[17:26:21] [Server thread/WARN]: 	at ac.grim.grimac.manager.DiscordManager.start(DiscordManager.java:26)
[17:26:21] [Server thread/WARN]: 	at ac.grim.grimac.manager.InitManager.start(InitManager.java:50)
[17:26:21] [Server thread/WARN]: 	at ac.grim.grimac.GrimAPI.start(GrimAPI.java:33)
[17:26:21] [Server thread/WARN]: 	at ac.grim.grimac.GrimAC.onEnable(GrimAC.java:19)
[17:26:21] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
[17:26:21] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332)
[17:26:21] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:393)
[17:26:21] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:392)
[17:26:21] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:351)
[17:26:21] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:402)
[17:26:21] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:366)
[17:26:21] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:328)
[17:26:21] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:294)
[17:26:21] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:565)
[17:26:21] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:829)
```

### How to replicate it if known

1. Use https://hooks.hyra.io/ as discord webhook proxy

### Grim version

2.3.21

### Server version

unrelated

### Plugins

unrelated

**Comment by AoElite** [comment]
Fixed by 897f88b74906d3349c4d45a1cd3b37e33ae91f9f
