### ISSUE TITLE
Sometimes there is a warning at startup

### ISSUE THREAD

**Issue by rejomy** [GrimAnticheat/Grim#743]
### Describe the bug and how to replicate it

[16:19:20 INFO]: [GrimAC] Loading PacketEvents...
[16:19:20 INFO]: Spigot injector failed to inject into an existing channel.
[16:19:20 WARN]: java.lang.IllegalStateException: PacketEvents failed to add a decoder to the netty pipeline. Pipeline handlers: [DefaultChannelPipeline$TailContext#0]
[16:19:20 WARN]:        at ac.grim.grimac.shaded.io.github.retrooper.packetevents.injector.connection.ServerConnectionInitializer.initChannel(ServerConnectionInitializer.java:98)
[16:19:20 WARN]:        at ac.grim.grimac.shaded.io.github.retrooper.packetevents.injector.SpigotChannelInjector.inject(SpigotChannelInjector.java:117)
[16:19:20 WARN]:        at ac.grim.grimac.shaded.io.github.retrooper.packetevents.factory.spigot.SpigotPacketEventsBuilder$1.load(SpigotPacketEventsBuilder.java:115)
[16:19:20 WARN]:        at ac.grim.grimac.manager.init.load.PacketEventsInit.start(PacketEventsInit.java:16)
[16:19:20 WARN]:        at ac.grim.grimac.manager.InitManager.load(InitManager.java:44)
[16:19:20 WARN]:        at ac.grim.grimac.GrimAPI.load(GrimAPI.java:28)
[16:19:20 WARN]:        at ac.grim.grimac.GrimAC.onLoad(GrimAC.java:9)
[16:19:20 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:323)
[16:19:20 WARN]:        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:222)
[16:19:20 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616)
[16:19:20 WARN]:        at java.base/java.lang.Thread.run(Thread.java:834)
[16:19:20 WARN]: Caused by: java.util.NoSuchElementException: splitter
[16:19:20 WARN]:        at io.netty.channel.DefaultChannelPipeline.getContextOrDie(DefaultChannelPipeline.java:1119)
[16:19:20 WARN]:        at io.netty.channel.DefaultChannelPipeline.addAfter(DefaultChannelPipeline.java:320)
[16:19:20 WARN]:        at io.netty.channel.DefaultChannelPipeline.addAfter(DefaultChannelPipeline.java:308)
[16:19:20 WARN]:        at ac.grim.grimac.shaded.io.github.retrooper.packetevents.injector.connection.ServerConnectionInitializer.initChannel(ServerConnectionInitializer.java:95)
[16:19:20 WARN]:        ... 10 more

### Grim version

Latest

### Server version

git-Paper-1620 (MC: 1.12.2)

### Plugins

AuctionHouse, Citizens, CommandBlocker, CommandNPC, DeluxeMenus, Essentials, EssentialsChat, EssentialsSpawn, GrimAC, HolographicDisplays, LuckPerms, PlaceholderAPI, ProtocolLib, RandomChest, TAB, TimeIsMoney, Vault, ViaBackwards, ViaRewind, ViaVersion, WorldEdit, WorldGuard

**Comment by MWHunter** [comment]
Report on PacketEvents github, this isn't a grim error
