### ISSUE TITLE
Exception

### ISSUE THREAD

**Issue by Xayanix** [GrimAnticheat/Grim#745]
### Stack trace
```
[08:27:44] [WARN]: PacketEvents caught an unhandled exception while calling your listener.
java.lang.IndexOutOfBoundsException: readerIndex(6) + length(8) exceeds writerIndex(11): UnpooledUnsafeDirectByteBuf(ridx: 6, widx: 11, cap: 256)
	at io.netty.buffer.AbstractByteBuf.checkReadableBytes(AbstractByteBuf.java:1175) ~[netty-all-4.0.23.Final.jar:4.0.23.Final]
	at io.netty.buffer.AbstractByteBuf.readLong(AbstractByteBuf.java:632) ~[netty-all-4.0.23.Final.jar:4.0.23.Final]
	at ac.grim.grimac.shaded.io.github.retrooper.packetevents.netty.buffer.ByteBufOperatorModernImpl.readLong(ByteBufOperatorModernImpl.java:94) ~[?:?]
	at ac.grim.grimac.shaded.com.github.retrooper.packetevents.netty.buffer.ByteBufHelper.readLong(ByteBufHelper.java:119) ~[?:?]
	at ac.grim.grimac.shaded.com.github.retrooper.packetevents.wrapper.PacketWrapper.readLong(PacketWrapper.java:476) ~[?:?]
	at ac.grim.grimac.shaded.com.github.retrooper.packetevents.wrapper.PacketWrapper.readUUID(PacketWrapper.java:625) ~[?:?]
	at ac.grim.grimac.shaded.com.github.retrooper.packetevents.wrapper.play.server.WrapperPlayServerSpawnPlayer.read(WrapperPlayServerSpawnPlayer.java:75) ~[?:?]
	at ac.grim.grimac.shaded.com.github.retrooper.packetevents.wrapper.PacketWrapper.readEvent(PacketWrapper.java:173) ~[?:?]
	at ac.grim.grimac.shaded.com.github.retrooper.packetevents.wrapper.PacketWrapper.<init>(PacketWrapper.java:118) ~[?:?]
	at ac.grim.grimac.shaded.com.github.retrooper.packetevents.wrapper.PacketWrapper.<init>(PacketWrapper.java:108) ~[?:?]
	at ac.grim.grimac.shaded.com.github.retrooper.packetevents.wrapper.play.server.WrapperPlayServerSpawnPlayer.<init>(WrapperPlayServerSpawnPlayer.java:50) ~[?:?]
	at ac.grim.grimac.events.packets.PacketEntityReplication.onPacketSend(PacketEntityReplication.java:90) ~[?:?]
	at ac.grim.grimac.manager.CheckManager.lambda$onPacketSend$4(CheckManager.java:175) ~[?:?]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:1.8.0_202]
	at ac.grim.grimac.manager.CheckManager.onPacketSend(CheckManager.java:175) ~[?:?]
	at ac.grim.grimac.events.packets.CheckManagerListener.onPacketSend(CheckManagerListener.java:763) ~[?:?]
	at ac.grim.grimac.shaded.com.github.retrooper.packetevents.event.PacketSendEvent.call(PacketSendEvent.java:48) ~[?:?]
	at ac.grim.grimac.shaded.com.github.retrooper.packetevents.event.EventManager.callEvent(EventManager.java:51) ~[?:?]
	at ac.grim.grimac.shaded.com.github.retrooper.packetevents.util.PacketEventsImplHelper.handleClientBoundPacket(PacketEventsImplHelper.java:41) ~[?:?]
	at ac.grim.grimac.shaded.io.github.retrooper.packetevents.injector.handlers.PacketEventsEncoder.encode(PacketEventsEncoder.java:66) ~[?:?]
	at ac.grim.grimac.shaded.io.github.retrooper.packetevents.injector.handlers.PacketEventsEncoder.write(PacketEventsEncoder.java:80) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658) ~[netty-all-4.0.23.Final.jar:4.0.23.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716) ~[netty-all-4.0.23.Final.jar:4.0.23.Final]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:706) ~[netty-all-4.0.23.Final.jar:4.0.23.Final]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:741) ~[netty-all-4.0.23.Final.jar:4.0.23.Final]
	at com.viaversion.viaversion.connection.UserConnectionImpl.lambda$sendRawPacket$1(UserConnectionImpl.java:154) ~[?:?]
	at com.viaversion.viaversion.connection.UserConnectionImpl.sendRawPacket(UserConnectionImpl.java:157) ~[?:?]
	at com.viaversion.viaversion.connection.UserConnectionImpl.sendRawPacket(UserConnectionImpl.java:139) ~[?:?]
	at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.send0(PacketWrapperImpl.java:255) ~[?:?]
	at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.send(PacketWrapperImpl.java:241) ~[?:?]
	at com.viaversion.viaversion.api.protocol.packet.PacketWrapper.send(PacketWrapper.java:179) ~[?:?]
	at com.viaversion.viaversion.protocols.protocol1_13to1_12_2.blockconnections.ConnectionData.update(ConnectionData.java:70) ~[?:?]
	at com.viaversion.viaversion.protocols.protocol1_13to1_12_2.packets.WorldPackets$4$1.handle(WorldPackets.java:206) ~[?:?]
	at com.viaversion.viaversion.api.protocol.remapper.PacketRemapper.remap(PacketRemapper.java:158) ~[?:?]
	at com.viaversion.viaversion.api.protocol.AbstractProtocol.transform(AbstractProtocol.java:324) ~[?:?]
	at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:371) ~[?:?]
	at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:359) ~[?:?]
	at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:46) ~[?:?]
	at com.viaversion.viaversion.protocol.ProtocolPipelineImpl.transform(ProtocolPipelineImpl.java:123) ~[?:?]
	at com.viaversion.viaversion.connection.UserConnectionImpl.transform(UserConnectionImpl.java:313) ~[?:?]
	at com.viaversion.viaversion.connection.UserConnectionImpl.transformClientbound(UserConnectionImpl.java:292) ~[?:?]
	at com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.transform(BukkitEncodeHandler.java:90) ~[?:?]
	at com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:83) ~[?:?]
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107) ~[netty-all-4.0.23.Final.jar:4.0.23.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658) ~[netty-all-4.0.23.Final.jar:4.0.23.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716) ~[netty-all-4.0.23.Final.jar:4.0.23.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:651) ~[netty-all-4.0.23.Final.jar:4.0.23.Final]
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:120) ~[netty-all-4.0.23.Final.jar:4.0.23.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658) ~[netty-all-4.0.23.Final.jar:4.0.23.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716) ~[netty-all-4.0.23.Final.jar:4.0.23.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:651) ~[netty-all-4.0.23.Final.jar:4.0.23.Final]
	at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:106) ~[netty-all-4.0.23.Final.jar:4.0.23.Final]
	at org.inventivetalent.packetlistener.channel.INCChannel$ChannelHandler.write(INCChannel.java:171) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658) ~[netty-all-4.0.23.Final.jar:4.0.23.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716) ~[netty-all-4.0.23.Final.jar:4.0.23.Final]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:706) ~[netty-all-4.0.23.Final.jar:4.0.23.Final]
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:890) ~[netty-all-4.0.23.Final.jar:4.0.23.Final]
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:245) ~[netty-all-4.0.23.Final.jar:4.0.23.Final]
	at com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:227) ~[?:?]
	at com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:233) ~[?:?]
	at net.minecraft.server.v1_8_R3.NetworkManager.writeInternal(SourceFile:273) ~[spigot.jar:git-iSpigot-PaperEdition]
	at net.minecraft.server.v1_8_R3.NetworkManager.lambda$write$2(SourceFile:261) ~[spigot.jar:git-iSpigot-PaperEdition]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380) ~[netty-all-4.0.23.Final.jar:4.0.23.Final]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:268) ~[netty-all-4.0.23.Final.jar:4.0.23.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) ~[netty-all-4.0.23.Final.jar:4.0.23.Final]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202]
```
### How to replicate it if known

Just spams in logs randomly, sometimes does and sometimes not.

### Grim version

grimac-2.3.23.jar

### Server version

ImanitySpigot 3

### Plugins

GrimAC ProtocolLib

**Comment by MWHunter** [comment]
Closing due to updated packetevents
