### ISSUE TITLE
Occasional injection errors

### ISSUE THREAD

**Issue by caoli5288** [GrimAnticheat/Grim#764]
### Stack trace

Occasionally happens, about 1/5 or 1/10. Not sure how to stabilize reproduce.

```
[23:16:33] [Server thread/INFO]: [GrimAC] Loading GrimAC v2.3.23
[23:16:33] [Server thread/INFO]: [GrimAC] Loading PacketEvents...
[23:16:33] [Server thread/INFO]: Spigot injector failed to inject into an existing channel.
[23:16:33] [Server thread/WARN]: java.lang.IllegalStateException: PacketEvents failed to add a decoder to the netty pipeline. Pipeline handlers: [DefaultChannelPipeline$TailContext#0]
[23:16:33] [Server thread/WARN]: 	at ac.grim.grimac.shaded.io.github.retrooper.packetevents.injector.connection.ServerConnectionInitializer.initChannel(ServerConnectionInitializer.java:98)
[23:16:33] [Server thread/WARN]: 	at ac.grim.grimac.shaded.io.github.retrooper.packetevents.injector.SpigotChannelInjector.inject(SpigotChannelInjector.java:117)
[23:16:33] [Server thread/WARN]: 	at ac.grim.grimac.shaded.io.github.retrooper.packetevents.factory.spigot.SpigotPacketEventsBuilder$1.load(SpigotPacketEventsBuilder.java:115)
[23:16:33] [Server thread/WARN]: 	at ac.grim.grimac.manager.init.load.PacketEventsInit.start(PacketEventsInit.java:16)
[23:16:33] [Server thread/WARN]: 	at ac.grim.grimac.manager.InitManager.load(InitManager.java:44)
[23:16:33] [Server thread/WARN]: 	at ac.grim.grimac.GrimAPI.load(GrimAPI.java:28)
[23:16:33] [Server thread/WARN]: 	at ac.grim.grimac.GrimAC.onLoad(GrimAC.java:9)
[23:16:33] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:323)
[23:16:33] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:222)
[23:16:33] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616)
[23:16:33] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:829)
[23:16:33] [Server thread/WARN]: Caused by: java.util.NoSuchElementException: splitter
[23:16:33] [Server thread/WARN]: 	at io.netty.channel.DefaultChannelPipeline.getContextOrDie(DefaultChannelPipeline.java:1119)
[23:16:33] [Server thread/WARN]: 	at io.netty.channel.DefaultChannelPipeline.addAfter(DefaultChannelPipeline.java:320)
[23:16:33] [Server thread/WARN]: 	at io.netty.channel.DefaultChannelPipeline.addAfter(DefaultChannelPipeline.java:308)
[23:16:33] [Server thread/WARN]: 	at ac.grim.grimac.shaded.io.github.retrooper.packetevents.injector.connection.ServerConnectionInitializer.initChannel(ServerConnectionInitializer.java:95)
[23:16:33] [Server thread/WARN]: 	... 10 more
```

### How to replicate it if known

Just run server

### Grim version

2.3.23

### Server version

This server is running Paper version git-Paper-1620 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

### Plugins

[23:16:31] [Server thread/INFO]: [ProtocolLib] Loading ProtocolLib v5.0.0-SNAPSHOT-b598

**Comment by MWHunter** [comment]
report on packetevents bug tracker not grim
