### ISSUE TITLE
inventory stack trace

### ISSUE THREAD

**Issue by MWHunter** [GrimAnticheat/Grim#855]
### Stack trace

[21:08:21 INFO]: [GrimAC] [STDOUT] An error has occurred when running transactions for player: _Dodo_13
[21:08:21 WARN]: java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
[21:08:21 WARN]:        at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
[21:08:21 WARN]:        at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
[21:08:21 WARN]:        at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
[21:08:21 WARN]:        at java.base/java.util.Objects.checkIndex(Objects.java:359)
[21:08:21 WARN]:        at java.base/java.util.ArrayList.get(ArrayList.java:427)
[21:08:21 WARN]:        at grimac-2.3.30.jar//ac.grim.grimac.utils.inventory.inventory.AbstractContainerMenu.getSlot(AbstractContainerMenu.java:418)
[21:08:21 WARN]:        at grimac-2.3.30.jar//ac.grim.grimac.utils.latency.CompensatedInventory.lambda$onPacketSend$5(CompensatedInventory.java:406)
[21:08:21 WARN]:        at grimac-2.3.30.jar//ac.grim.grimac.utils.latency.LatencyUtils.handleNettySyncTransaction(LatencyUtils.java:44)
[21:08:21 WARN]:        at grimac-2.3.30.jar//ac.grim.grimac.player.GrimPlayer.addTransactionResponse(GrimPlayer.java:314)
[21:08:21 WARN]:        at grimac-2.3.30.jar//ac.grim.grimac.events.packets.PacketPingListener.onPacketReceive(PacketPingListener.java:50)
[21:08:21 WARN]:        at grimac-2.3.30.jar//com.github.retrooper.packetevents.event.PacketReceiveEvent.call(PacketReceiveEvent.java:45)
[21:08:21 WARN]:        at grimac-2.3.30.jar//com.github.retrooper.packetevents.event.EventManager.callEvent(EventManager.java:51)
[21:08:21 WARN]:        at grimac-2.3.30.jar//com.github.retrooper.packetevents.util.PacketEventsImplHelper.handleServerBoundPacket(PacketEventsImplHelper.java:43)
[21:08:21 WARN]:        at grimac-2.3.30.jar//io.github.retrooper.packetevents.injector.handlers.PacketEventsDecoder.read(PacketEventsDecoder.java:54)
[21:08:21 WARN]:        at grimac-2.3.30.jar//io.github.retrooper.packetevents.injector.handlers.PacketEventsDecoder.decode(PacketEventsDecoder.java:64)
[21:08:21 WARN]:        at grimac-2.3.30.jar//io.github.retrooper.packetevents.injector.handlers.PacketEventsDecoder.decode(PacketEventsDecoder.java:36)
[21:08:21 WARN]:        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88)
[21:08:21 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[21:08:21 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[21:08:21 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[21:08:21 WARN]:        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
[21:08:21 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[21:08:21 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[21:08:21 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[21:08:21 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
[21:08:21 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
[21:08:21 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[21:08:21 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[21:08:21 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[21:08:21 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
[21:08:21 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
[21:08:21 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[21:08:21 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[21:08:21 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[21:08:21 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
[21:08:21 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:311)
[21:08:21 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:432)
[21:08:21 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
[21:08:21 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[21:08:21 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[21:08:21 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[21:08:21 WARN]:        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
[21:08:21 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[21:08:21 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[21:08:21 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[21:08:21 WARN]:        at io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:152)
[21:08:21 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[21:08:21 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[21:08:21 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[21:08:21 WARN]:        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
[21:08:21 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[21:08:21 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[21:08:21 WARN]:        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
[21:08:21 WARN]:        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795)
[21:08:21 WARN]:        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480)
[21:08:21 WARN]:        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
[21:08:21 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
[21:08:21 WARN]:        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[21:08:21 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)

### Grim version

e

### Server version

e

### Plugins

e

**Comment by MWHunter** [comment]
https://github.com/GrimAnticheat/Grim/commit/bfe07179193710598a97c6d3321c3f427ce3a52a
