### ISSUE TITLE
Random exception and kick player while do inventory operations

### ISSUE THREAD

**Issue by caoli5288** [GrimAnticheat/Grim#909]
### Stack trace

```
[02:59:02] [epollEventLoopGroup-3-4/WARN]: A task raised an exception. Task: ac.grim.grimac.utils.latency.CompensatedInventory$$Lambda$1760/0x000000010102ac40@2de42ac1
java.lang.IndexOutOfBoundsException: Index 49 out of bounds for length 46
	at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64) ~[?:?]
	at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70) ~[?:?]
	at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248) ~[?:?]
	at java.util.Objects.checkIndex(Objects.java:372) ~[?:?]
	at java.util.ArrayList.get(ArrayList.java:459) ~[?:?]
	at ac.grim.grimac.utils.inventory.inventory.AbstractContainerMenu.getSlot(AbstractContainerMenu.java:418) ~[GrimAC.jar:?]
	at ac.grim.grimac.utils.latency.CompensatedInventory.lambda$onPacketSend$7(CompensatedInventory.java:450) ~[GrimAC.jar:?]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[NachoSpigot.jar:git-NachoSpigot-78b83c0]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[NachoSpigot.jar:git-NachoSpigot-78b83c0]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[NachoSpigot.jar:git-NachoSpigot-78b83c0]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:403) ~[NachoSpigot.jar:git-NachoSpigot-78b83c0]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[NachoSpigot.jar:git-NachoSpigot-78b83c0]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[NachoSpigot.jar:git-NachoSpigot-78b83c0]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[NachoSpigot.jar:git-NachoSpigot-78b83c0]
	at java.lang.Thread.run(Thread.java:829) ~[?:?]
```

### How to replicate it if known

1. not very clear exactly what steps to reproduce, it happens randomly.

### Grim version

tested both 2.3.31 and 2.3.32

### Server version

`This server is running NachoSpigot version git-NachoSpigot-78b83c0 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)`

### Plugins

Grim-2.3.32 with ViaVersion-4.5.1

**Comment by c0dingnoobi** [comment]
ig client version also 1.8?

**Comment by MWHunter** [comment]
Duplicate https://github.com/GrimAnticheat/Grim/issues/902

**Comment by caoli5288** [comment]
@MWHunter Still not fixed

```
[16:17:04] [epollEventLoopGroup-3-3/WARN]: A task raised an exception. Task: ac.grim.grimac.utils.latency.CompensatedInventory$$Lambda$1799/0x0000000101060040@292c6690
java.lang.IndexOutOfBoundsException: Index 49 out of bounds for length 46
	at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64) ~[?:?]
	at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70) ~[?:?]
	at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248) ~[?:?]
	at java.util.Objects.checkIndex(Objects.java:372) ~[?:?]
	at java.util.ArrayList.get(ArrayList.java:459) ~[?:?]
	at ac.grim.grimac.utils.inventory.inventory.AbstractContainerMenu.getSlot(AbstractContainerMenu.java:423) ~[GrimAC.jar:?]
	at ac.grim.grimac.utils.latency.CompensatedInventory.lambda$onPacketSend$7(CompensatedInventory.java:451) ~[GrimAC.jar:?]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[NachoSpigot.jar:git-NachoSpigot-78b83c0]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[NachoSpigot.jar:git-NachoSpigot-78b83c0]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[NachoSpigot.jar:git-NachoSpigot-78b83c0]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:403) ~[NachoSpigot.jar:git-NachoSpigot-78b83c0]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[NachoSpigot.jar:git-NachoSpigot-78b83c0]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[NachoSpigot.jar:git-NachoSpigot-78b83c0]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[NachoSpigot.jar:git-NachoSpigot-78b83c0]
	at java.lang.Thread.run(Thread.java:829) ~[?:?]
```

**Comment by MWHunter** [comment]
your server is sending bad packets

https://github.com/GrimAnticheat/Grim/commit/b6e86c8f6bd45fe600cd09b973c23948255e25e7
