### ISSUE TITLE
PacketEvents exception

### ISSUE THREAD

**Issue by SkyWaves123** [GrimAnticheat/Grim#919]
### Stack trace

[00:07:17] [Netty Server IO #1/WARN]: PacketEvents caught an unhandled exception while calling your listener.
ac.grim.grimac.shaded.com.github.retrooper.packetevents.exception.PacketProcessException: java.lang.IndexOutOfBoundsException: readerIndex(1) + length(1) exceeds writerIndex(1): UnpooledHeapByteBuf(ridx: 1, widx: 1, cap: 256)
	at ac.grim.grimac.shaded.com.github.retrooper.packetevents.wrapper.handshaking.client.WrapperHandshakingClientHandshake.read(WrapperHandshakingClientHandshake.java:64) ~[grimac-2.3.32%20(1).jar:?]
	at ac.grim.grimac.shaded.com.github.retrooper.packetevents.wrapper.PacketWrapper.readEvent(PacketWrapper.java:178) ~[grimac-2.3.32%20(1).jar:?]
	at ac.grim.grimac.shaded.com.github.retrooper.packetevents.wrapper.PacketWrapper.<init>(PacketWrapper.java:108) ~[grimac-2.3.32%20(1).jar:?]
	at ac.grim.grimac.shaded.com.github.retrooper.packetevents.wrapper.PacketWrapper.<init>(PacketWrapper.java:98) ~[grimac-2.3.32%20(1).jar:?]
	at ac.grim.grimac.shaded.com.github.retrooper.packetevents.wrapper.handshaking.client.WrapperHandshakingClientHandshake.<init>(WrapperHandshakingClientHandshake.java:40) ~[grimac-2.3.32%20(1).jar:?]
	at ac.grim.grimac.shaded.io.github.retrooper.packetevents.manager.InternalBukkitPacketListener.onPacketReceive(InternalBukkitPacketListener.java:21) ~[grimac-2.3.32%20(1).jar:?]
	at ac.grim.grimac.shaded.com.github.retrooper.packetevents.event.PacketReceiveEvent.call(PacketReceiveEvent.java:45) ~[grimac-2.3.32%20(1).jar:?]
	at ac.grim.grimac.shaded.com.github.retrooper.packetevents.event.EventManager.callEvent(EventManager.java:51) [grimac-2.3.32%20(1).jar:?]
	at ac.grim.grimac.shaded.com.github.retrooper.packetevents.util.PacketEventsImplHelper.handleServerBoundPacket(PacketEventsImplHelper.java:43) [grimac-2.3.32%20(1).jar:?]
	at ac.grim.grimac.shaded.io.github.retrooper.packetevents.injector.handlers.PacketEventsDecoder.read(PacketEventsDecoder.java:51) [grimac-2.3.32%20(1).jar:?]
	at ac.grim.grimac.shaded.io.github.retrooper.packetevents.injector.handlers.PacketEventsDecoder.decode(PacketEventsDecoder.java:58) [grimac-2.3.32%20(1).jar:?]
	at ac.grim.grimac.shaded.io.github.retrooper.packetevents.injector.handlers.PacketEventsDecoder.decode(PacketEventsDecoder.java:35) [grimac-2.3.32%20(1).jar:?]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:89) [patched_1.8.8.jar:git-PaperSpigot-445]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [patched_1.8.8.jar:git-PaperSpigot-445]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [patched_1.8.8.jar:git-PaperSpigot-445]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [patched_1.8.8.jar:git-PaperSpigot-445]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [patched_1.8.8.jar:git-PaperSpigot-445]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [patched_1.8.8.jar:git-PaperSpigot-445]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163) [patched_1.8.8.jar:git-PaperSpigot-445]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [patched_1.8.8.jar:git-PaperSpigot-445]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [patched_1.8.8.jar:git-PaperSpigot-445]
	at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:150) [patched_1.8.8.jar:git-PaperSpigot-445]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [patched_1.8.8.jar:git-PaperSpigot-445]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [patched_1.8.8.jar:git-PaperSpigot-445]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787) [patched_1.8.8.jar:git-PaperSpigot-445]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:130) [patched_1.8.8.jar:git-PaperSpigot-445]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511) [patched_1.8.8.jar:git-PaperSpigot-445]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:430) [patched_1.8.8.jar:git-PaperSpigot-445]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:384) [patched_1.8.8.jar:git-PaperSpigot-445]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354) [patched_1.8.8.jar:git-PaperSpigot-445]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [patched_1.8.8.jar:git-PaperSpigot-445]
	at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.IndexOutOfBoundsException: readerIndex(1) + length(1) exceeds writerIndex(1): UnpooledHeapByteBuf(ridx: 1, widx: 1, cap: 256)
	at io.netty.buffer.AbstractByteBuf.checkReadableBytes(AbstractByteBuf.java:1175) ~[patched_1.8.8.jar:git-PaperSpigot-445]
	at io.netty.buffer.AbstractByteBuf.readByte(AbstractByteBuf.java:570) ~[patched_1.8.8.jar:git-PaperSpigot-445]
	at ac.grim.grimac.shaded.io.github.retrooper.packetevents.netty.buffer.ByteBufOperatorModernImpl.readByte(ByteBufOperatorModernImpl.java:74) ~[grimac-2.3.32%20(1).jar:?]
	at ac.grim.grimac.shaded.com.github.retrooper.packetevents.netty.buffer.ByteBufHelper.readByte(ByteBufHelper.java:67) ~[grimac-2.3.32%20(1).jar:?]
	at ac.grim.grimac.shaded.com.github.retrooper.packetevents.wrapper.PacketWrapper.readByte(PacketWrapper.java:221) ~[grimac-2.3.32%20(1).jar:?]
	at ac.grim.grimac.shaded.com.github.retrooper.packetevents.wrapper.PacketWrapper.readVarInt(PacketWrapper.java:253) ~[grimac-2.3.32%20(1).jar:?]
	at ac.grim.grimac.shaded.com.github.retrooper.packetevents.wrapper.handshaking.client.WrapperHandshakingClientHandshake.read(WrapperHandshakingClientHandshake.java:57) ~[grimac-2.3.32%20(1).jar:?]
	... 31 more

### Grim version

grim version 2.3.32

### Server version

This server is running CraftBukkit version git-PaperSpigot-445 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

### Plugins

Plugins (40): WorldEdit, killStats, PlaceholderAPI, PlugMan, spark, WeatherTimeLock, Votifier, WorldGuard, PebbleAntiVPN, zVoteParty, ChunkCollector, KSpawn, SetHub, ViaVersion, PlugManX, ViaRewind, LuckPerms, CrazyCrates, Scoreboard-revision, ProtocolLib, SkinsRestorer, Vault, TokenManager, DecentHolograms, Essentials, BKCommonLib, GrimAC, AuthMe, Economy, LiteBans, AuctionHouse, TabList, ShopGUIPlus, Tokens, SuperiorSkyblock2, SuperiorFall, My_Worlds, WildStacker, WildTools, JetsMinions

**Comment by MWHunter** [comment]
packetevents issue, report on their issue tracker

**Comment by SkyWaves123** [comment]
> packetevents issue, report on their issue tracker

Can you give me a link? I can't find where I'm supposed to open an issue

**Comment by vytskalt** [comment]
https://github.com/retrooper/packetevents

**Comment by SkyWaves123** [comment]
Btw i dont event have Packetevents api installed on my server. Does paper automatically install it or what?

**Comment by vytskalt** [comment]
> Btw i dont event have Packetevents api installed on my server. Does paper automatically install it or what?

Grim does that automatically

**Comment by MWHunter** [comment]
It's shaded into the jar
